eciis/web

setup_google_credential.sh

Backend requests to Firebase running on local server needs an file to specify the credentials used to perform the request. The created script creates a file on local_home, ecis-firebase-identity.json, which provides the necessarily information, and export an environment variable to point the local file.

Script to setup google identity

---

admin.py
handlers/post_collection_handler.py
models/user.py
test/institution_timeline_handler_test.py
test/post_collection_handler_test.py
test/user_timeline_handler_test.py

The condition to validate user permission was to have publish_post, using Utils._assert, but the that function works with the opposite condition to thrown an error. So, the correct validation is not to have publish_post.

Fix wrong condition to validate permission on post handler

---

models/institution.py

When the institution stub is created the function was appending the institution key directly to the user instead of use the user function, this modification wasn't giving the right permissions to the user.

Fix add institution to user when creating stub

---

app/invites/invite.js
app/invites/inviteInstHierarchieController.js
app/invites/inviteInstitutionController.js
app/invites/inviteUserController.js
app/invites/newInviteController.js
app/invites/new_invite_page.html
app/test/specs/inviteInsHierarchieSpec.js
app/test/specs/inviteUserControllerSpec.js
app/test/specs/newInviteControllerSpec.js
models/invite.py
test/institution_handler_test.py
test/invite_collection_handler_test.py

The invite saves the inviter_key instead of email inviter, to show in invite page who is the inviter.

add inviter name and institution inviter name in invites

---

app/app.js
app/auth/authService.js
utils.py

When the user session expired, a key error was returned by the server, the solution was to export the certs.json (file that stores the oauth2 certificates to verify user token) to a single file in the cloud storage, and handles properly the error 401 in the client side.

Fix token expiration error

---

custom_exceptions/entityException.py
handlers/post_comment_handler.py
test/post_comment_handler_test.py

If the user try to comment a deleted post an exception is raised and the procedure is interrupted.

Fix user permission to comment on a deleted post

---

app/post/postDetailsDirective.js
app/test/specs/postDetailsControllerSpec.js

The pattern to recognize URL on text post was matching with any string with a dot "." between two words, like name.name. The solution was rethink the pattern to accomplish the correct match.

Fix match url pattern on post text

---

app/post/post_details.html
app/styles/custom.css

**Bug**: It occurs when a post has a text line too long on title or on the post's message.
**Effect**: The text overflows the post card.
**Solution**: It was created a CSS class with the word-break property and this class was used on the 
affected elements.

Fix bug on long lines in posts

---

app/post/postDirective.js
app/post/save_post.html

**Cause**: It occurs when the user is logged in with a different institution from that on the post that is being edited.
**Effect**: The institution image and name shown are from the user current institution when it should be from the post institution.
**Solution**: It was created functions to get the correct institution name and photo_url depending on whether the post is being edited or not.

Bug on showing Institution name and image on edit post dialog

---

app/home/home.html
app/home/homeController.js
app/institution/institutionController.js
app/institution/institution_page.html
app/styles/custom.css
app/user/profile.html
app/user/profileService.js

<p><b>Feature/Bug description:</b> When timeline in home page or institution page is loading posts the following messages is displayed: "O usuário não tem perfil" e "A instituição ainda não possui publicações.", respectively.</p>
<p><b>Solution:</b> Added boolean variable in profileCtrl, homeCtrl and institutionCtrl to know when the information is loaded. When is not loaded, the html show progress circular animation.</p>

Circular loading when loading posts and profile

---

app/invites/inviteInstHierarchieController.js
app/invites/invite_institution_hierarchie.html
models/institution.py

<p><b>Bug description:</b> The parent institution suggestion name was being shown when the logged user was not the one who requested the creation of this institution</p>
<p><b>Solution:</b> It was created a function to verify if the user logged in is the user who requested the creation of the parent institution</p>

Bug on showing parent institution

---

handlers/post_collection_handler.py
test/post_collection_handler_test.py

<p><b>Feature/Bug description:</b> When user is author of post and shared the post, the application send notification to own user.</p>
<p><b>Solution:</b> Added verification if user.key is equal shared_post.author in post_collection_handler in POST request.</p>

Fixing the self notification bug in shared-posts

---

handlers/request_handler.py
handlers/user_request_collection_handler.py
models/user.py
test/model_test/institution_profile_test.py
test/model_test/user_test.py
test/user_request_collection_handler_test.py

<p><b>Bug description:</b> The institution photo and name was not being shown on a recent created user profile</p>
<p><b>Solution:</b> When a new user requests to become member of an institution, it is created a profile.
Previously, the institution name and photo_url were not being set on profile creation, now they are.</p>

Bug on showing institution photo and name in user profile

---

app/invites/inviteUserController.js
handlers/request_handler.py
models/user.py
test/request_handler_test.py

<p><b>Bug description:</b> When an user request to become member of an institution was rejected the corresponding user profile was not being removed.</p>
<p><b>Solution:</b> Now it is called the user method remove_profile in the request_handler delete method to remove the profile related to that request.</p>

Fix exclusion of user profile when institution rejects his membership

---

app/post/comment.html
app/post/postDetailsDirective.js
app/test/specs/commentControllerSpec.js
handlers/post_comment_handler.py
test/post_comment_handler_test.py

<p><b>Feature/Bug description:</b> User can delete comments and replies in deleted posts.</p>
<p><b>Solution:</b> In back-end: added exception in delete comment when post state is deleted.
In front-end: added some verifications to not allow delete comments in posts with deleted state.</p>

Remove delete of comments in deleted posts

---

app/invites/existing_institutions.html
app/invites/inviteInstitutionController.js
app/invites/invite_institution.html
app/invites/new_invite_page.html
app/invites/suggestInstitutionController.js
handlers/invite_handler.py
models/institution.py
models/invite.py
test/invite_handler_test.py
test/model_test/request_user_test.py

<p><b>Bug description:</b> Rejected institution invites were being shown as pending invites when the user tries to create an institution invite with the same name as one that has already been rejected.</p>
<p><b>Solution:</b> On invite handler delete method, when an invite is deleted, the corresponding stub institution has its state changed to inactive as well as its document.</p>

Fix institutions rejected invites

---

app/notification/notificationDirective.js
app/notification/notificationService.js
handlers/institution_children_request_handler.py
handlers/institution_parent_request_handler.py
handlers/invite_handler.py
models/institution.py
models/invite_institution.py
models/invite_user.py
models/request_institution_children.py
models/request_institution_parent.py
test/institution_children_request_handler_test.py
test/institution_handler_test.py
test/institution_parent_request_handler_test.py
test/invite_handler_test.py

<p><b>Feature/Bug description:</b> When invites or requests is accepted or rejected the sender is not notified when is accepted or rejected.</p>
<p><b>Solution:</b> When user or admin accept or reject invite (or request), invite_handler send notification to sender of invite.</p>

Sending notification when invite or request is accepted or rejected

---

backend/models/invite.py

<p><b>Feature/Bug description:</b> If the user is a new user, when sending a request to some institution, the sender_name of the user is Unknow or the last sender_name from another invite.</p>
<p><b>Solution:</b> Changing the logic in creating invite to construct RequestUser with correct sender_name.</p>

fixing the unknow sender_name in request user

---

frontend/post/pdfDialog.html

<p><b>Feature/Bug description:</b> Broken pdfs preview layout on very large or very small screens.</p>
<p><b>Solution:</b> I used the fill layout so that the pdf preview mode would fill the entire area available on the screen.</p>

Fix layout of pdf view

---

backend/handlers/institution_followers_handler.py

<p><b>Feature/Bug description:</b> If the institution that user is a member is deleted, the user state is changed to inactive, however, the institutions followed by the user display the user even if his inactive.</p>
<p><b>Solution:</b> The solution is very simple: in getFollowers, the server side sends only followers with the active state.</p>

removing the inactive user from display of followers

---

frontend/home/home.html
frontend/institution/institution_page.html
frontend/invites/invite_institution_hierarchie.html

<p><b>Feature/Bug description:</b> The text displayed in right side of timeline is "Evento" and in institution page is "Instituições subordinadas" and "Instituição superior".</p>
<p><b>Solution:</b> Changed "Evento" to "Próximos eventos", "Instituições subordinadas" to "Instituições hierarquicamente subordinadas" and "Instituição superior" to "Instituição hierarquicamente superior".</p>

improving the texts displayed in events widget, management Inst. and Inst. page

---

frontend/institution/managementMembersController.js
frontend/test/specs/managementMembersControllerSpec.js

When the admin tried to invite an user that had already been invited or that was a member he was redirected to the error page because the frontend wasn't catching the error.
</p>
_.includes and _.some weren't doing what they were supposed to do when were implemented. Then, I've fixed inviteeIsMember and inviteeIsInvited, the functions that used to use the first ones.
</p>

Fixing inviteIsMember and inviteeIsInvited functions

---

backend/search_module.py
backend/test/search_handler_test.py
frontend/institution/institution_page.html
frontend/institution/submit_form.html

Now it's possible to search by the institution's occupation area.
</p>
I've added another field in the docs and changed the language that the occupation area was saved from english to portuguese, to avoid translate and to keep the full text search. 
</p>

Search by occupation area

---

backend/admin.py
backend/handlers/institution_members_handler.py
backend/service_messages.py
backend/test/institution_member_handler_test.py
frontend/notification/notificationDirective.js
frontend/notification/notificationService.js

Send notification when a member is removed from an institution.
</p>
I've called send_notification method from the handler where the user is removed and adapted the notification's message.
</p>
<p><b>TODO/FIXME:</b>
Refactor send_message_email to receive the subject dynamically and change its calls.
</p>

Sending notification when the user is removed

---

backend/models/invite.py
backend/service_messages.py

The method send_message_email had a default and static subject, which have made it impossible to send an email with different subjects, for example.
</p>
Now the subject is received as a parameter, what made it became dynamic.
</p>

Receive subject as a parameter in send_message_email

---

backend/index.yaml
backend/models/invite_institution.py
backend/models/invite_user.py
backend/models/request_institution.py
backend/models/request_institution_children.py
backend/models/request_institution_parent.py
backend/models/request_user.py
frontend/app.js
frontend/frontend.yaml
frontend/test/specs/suggestInstitutionControllerSpec.js

<p><b>Feature/Bug description:</b> The frontend used a hash (#) on it's URL to be able to understand which state was reffered.</p>
<p><b>Solution:</b> Enabling html5mode on AngularJs, it's possible to remove that hash and have a clean URL displayed to the user. A URL mapping on frontend.yaml was needed to AppEngine understand the redirection.</p>

Enable html5 on angularJS

---

frontend/notification/notificationService.js

<p><b>Feature/Bug description:</b> The notification send when the user accept one invite to be admin of one institution was undefined</p>
<p><b>Solution:</b> The problem is on translate message because the correct name of notification is ACCEPT_INVITE_INSTITUTION </p>

Fix name of message notification

---

ecis

<p><b>Feature/Bug description:</b> The variable BACKEND_DOMAIN has been accessed without the $ character, turning the variable into a string.</p>
<p><b>Solution:</b> Add the $ to the variable.</p>

Fix wrong variable sintaxe on main script

---

backend/test/post_handler_test.py

<p><b>Feature/Bug description:</b> When patch_method in post_handler_test throw an error, this error message is not verified.</p>
<p><b>Solution:</b> Verifying if the specific message is thrown when the method crash.</p>

adding specific expected exception in post_handler_test

---

backend/handlers/reply_comment_handler.py
backend/test/reply_comment_handler_test.py

<p><b>Feature/Bug description:</b> Tests that expected an exception to be thrown were not verifying that the exception thrown was expected.</p>
<p><b>Solution:</b> I added checks for the thrown exceptions to see if they match  expected.</p>

Fix tests of reply comment handler test

---

backend/test/post_comment_handler_test.py

<p><b>Feature/Bug description:</b> When some methods in post_comment_handler_test throw an error, this error message is not verified.</p>
<p><b>Solution:</b> Verifying if the specific message is thrown when the method crash.</p>

Adding specific expects exceptions messages in post_comment_handler_test

---

backend/test/institution_handler_test.py

<p><b>Feature/Bug description:</b> Tests that expected an exception to be thrown were not verifying that the exception thrown was expected.</p>
<p><b>Solution:</b> I added checks for the thrown exceptions to see if they match expected.</p>

Fix tests of institution handler test

---

frontend/post/post_details.html

Most of the post's buttons came out of the md-card-actions to the upper right corner encapsulated in a menu.
</p>
I've moved the buttons to a md-menu directive that is inside of md-card-header.
</p>

Refactoring the post button's design

---

frontend/home/home.html
frontend/post/save_post.html

<p><b>Feature/Bug description:</b> The timeline on the home page had the height larger than the screen size, causing an unnecessary scrollbar, as well as, the post creation card width. </p>
<p><b>Solution:</b> Use the right set of layout rules of the angular material.</p>

Fix home layout and post creation card

---

frontend/styles/custom.css

<p><b>Feature/Bug description:</b> Angular Material don't have small icon buttons and the new system design needs them.</p>
<p><b>Solution:</b> Create a new css class to style the md-buttons.</p>

CSS for small icon buttons

---

frontend/post/post.js
frontend/post/postDetailsDirective.js
frontend/test/specs/postSpec.js

<p><b>Bug description:</b> When the post was deleted, the last_modified_by property was not been updated on frontend. So, it was been showing the name of the last person who modified the post and not the user who deleted it</p>
<p><b>Solution:</b> Set post property last_modified_by to current user name after the post is successfully  deleted</p>

Bug on showing the name of who deleted the post

---

frontend/event/eventController.js

When an event with the end_time >= start_time was created, an exception was raised and the event's image showed twice in the dialog, if there was one in the event previously.
</p>
I've added another verification into showEventImage method.
</p>

Adding a missing verification in showEventImage()

---

frontend/app.js

<p><b>Feature/Bug description:</b> After the user receives multiple invites to create institution only the last one can actualy be accessed and filled.</p>
<p><b>Solution:</b> Create a list of ignored routes on the invite interceptor, that ignores the create institution form state.</p>

Fix wrong redirect after accept invite

---

frontend/post/postDirective.js

<p><b>Feature/Bug description:</b> When the type of post is changed of common to survey, the files in post keep displayed in post.</p>
<p><b>Solution:</b> Added different behavior in clearPost function when type of post is common or survey.</p>

fixing showing files when post is changed of common to survey

---

frontend/main/main.html

<p><b>Feature/Bug description:</b> The input search div was floating over the toolbar and overlaping elements from the content.</p>
<p><b>Solution:</b> Apply a 0px margin to the 3 parent nodes of the input field.</p>

Fix input search margin

---

frontend/search/search.html

<p><b>Feature/Bug description:</b> Search filter content layout is too large and passing from the screen.</p>
<p><b>Solution:</b> Create a select that encapsulates all the options.</p>

Create new layout of search filter

---

frontend/invites/existing_institutions.html
frontend/invites/suggestInstitutionController.js
frontend/test/specs/suggestInstitutionControllerSpec.js

<p><b>Feature/Bug description:</b> When the admin of institution invite institution without hierarchy the dialog displayed is the same when the invite is to hierarchy. Also, button "ver detalhes" is behaving unexpectedly, not redirecting to institution page.</p>
<p><b>Solution:</b> Changing the display to be different in case of invite are without hierarchy and delegate the responsibility of redirect to institution page to $state of ui-router library.</p>

Changing display of institution suggestions

---

backend/handlers/institution_children_request_handler.py
backend/handlers/institution_parent_request_handler.py
backend/permissions.py
backend/test/institution_children_request_handler_test.py
backend/test/institution_parent_request_handler_test.py

<p><b>Feature/Bug description:</b> Changing decorator verification to permissions verification in institution_parent_request_handler and institution_children_request_handler.</p>
<p><b>Solution:</b> Removing decorator from put and delete methods and verifying if the user has permission to link institutions.</p>

Remove is_admin_of_requested_inst from request institution links handlers

---

frontend/institution/portfolioDialog.html

<p><b>Feature/Bug description:</b> PDF preview is broken when the screen is too large.</p>
<p><b>Solution:</b> Modify the layout of the preview so that it fills the screen.</p>

Fix pdf visualization in institution page

---

landing/styles/custom.css

<p><b>Feature/Bug description:</b> The landing page when turned into mobile responsive version and rotated the screen to landscape mode, it was causing the section content to overflow the div.
</p>
<p><b>Solution:</b> Use CSS media query with a orientation parameter, that tell's the browser to respond accordingly to the internal styles. In this case, it was necessary to set a minimum height to prevent that the section content overflows.
```
@media screen and (max-width: 960px) and (orientation:landscape) {
.section {
min-height: 1000px;
}
}
```
</p>

Fix landing page responsiveness with css media orientation

---

frontend/invites/invite_institution.html

<p><b>Feature/Bug description:</b> The toolbar of pending requests not display notification when have new requests.</p>
<p><b>Solution:</b> Adding notification in toolbar of pending requests in inivite_institution page.</p>

Adding notification in pending requests toolbar on invite_inst page

---

landing/index.html

<p><b>Feature/Bug description:</b> The landing page is broken in some browsers, like Internet Explorer, because those are out of date with the new web technologies (CSS3, HTML5, etc).</p>
<p><b>Solution:</b> Display an alert that tells the user that his browser needs to be updated to a new browser or a new version.
This solution was implemented using the [Browser Update](https://github.com/browser-update/browser-update) module, under MIT license.
</p>
<b>PS.:</b> In case the need to test, It is just type the key value `test:true` to the variable `buoop`.

Add alert to update browser

---

Jenkinsfile
ecis

<p><b>Feature/Bug description:</b> The ecis run script not allow pass parameters to the dev_appserver,
difficulting to set some flags when serving the server.</p>
<p><b>Solution:</b> Add a new parameter to the script that can receive any of the dev_appserver flags,
like sendmail flag.</p>

Add generic param to ecis run script

---

frontend/institution/create_inst_form.html

When the description was too large the view would break.
</p>
I've inserted max-height and overflow-y css' property into <textarea>.
</p>

Fixing description height

---

frontend/user/userInactiveController.js
frontend/user/user_inactive.html

<p><b>Feature/Bug description:</b> The button 'AVANÇAR' of user_inactive was showing all time but should show only when exists institutions searched by user</p>
<p><b>Solution:</b> Added verification if there are institutions found.</p>

Fixed bug in view user inactive

---

backend/models/event.py
frontend/event/eventController.js
frontend/event/event_details.html
frontend/event/event_dialog.html

<p><b>Feature/Bug description:</b> The start and end date and time is not specific. Also the official site is not defined in creation of event.</p>
<p><b>Solution:</b> Added the start and end date, hours and year and added the official site field in creation of event.</p>

Improving display of hours and adding official site in event page

---

frontend/post/share_post_dialog.html

The shared post's title in the modal shouldn't be clickable.
</p>
I've removed ng-click, "<a>" and href.
</p>

Fix shared post title in modal

---

backend/handlers/institution_followers_handler.py
backend/test/followers_institution_handler_test.py
backend/utils.py
frontend/institution/base_institution_page.html
frontend/institution/institutionController.js

<p><b>Feature/Bug description:</b>All users of platform have to follow Health Ministry Institution if exists</p>
<p><b>Solution:</b>Search for Health Ministry Institution when create_user method is called and follow this Institution if exists. The Handler throw error if the user tries to unfollow this Institution. In frontend, the button to follow/unfollow is hidden if the institution is Health Ministry.</p>

All users have to follow MS Institution

---

frontend/institution/management_institution_page.html

The content wasn't fulfilling the view when it was smaller than 1280px.
</p>
I've added some flex-md properties.
</p>

Fix responsiveness of management institution page

---

backend/handlers/resend_invite_handler.py
backend/main.py
backend/test/mocks.py
backend/test/resend_invite_handler_test.py
frontend/institution/managementMembersController.js
frontend/institution/management_members.html
frontend/invites/inviteService.js
frontend/styles/custom.css
frontend/test/specs/managementMembersControllerSpec.js

Resend the email and the notification to the user that received an invite to be an institution's member.
</p>
I've created a handler that with its post method calls invite.sendInvite().
</p>

Resend invite member

---

backend/admin.py

<p><b>Feature/Bug description:</b>When reset the datastore to create MS, the profile of admin is not created.</p>
<p><b>Solution:</b>Create profile for admin of MS institution</p>

Fix the reset MS to create the admin profile.

---

frontend/index.html
frontend/main/main.html

<p><b>Feature/Bug description:</b> Add a script that checks the version of the browser that is accessing the platform to block access to old browsers that no longer has support and adjust the platform logo to support the Mozilla browser.</p>
<p><b>Solution:</b> Add the same script already added in the index.html from the landing page to the index.html of the frontend and change the size of the platform logo to pixels.</p>

Add script for check browser version in frontend

---

backend/search_module/search_institution.py
backend/search_module/search_user.py

<p><b>Feature/Bug description:</b> The error, `'NoneType' has no attributes fields`, occurred when the user attempted to do any modification in the institution or user entities. That was happening because the document wasn't created when the modification occurred, once the _post_put was triggered calling the create_document, the system does the following verification:
```
if not index.get(user.key.urlsafe()):
// CREATE DOCUMENT
else:
self.updateDocument(user)
```
The first line negates the return of the call to get index, that call returns an **object** _NoneType_ that is the object form of none. Them implicates in the execution of the update of an inexistent document.
</p>
<p><b>Solution:</b> Change the verification to: 
```
if index.get(user.key.urlsafe()) is None:
// CREATE DOCUMENT …
```

Fix none type error when editing user or institution

---

frontend/home/home.html
frontend/home/homeController.js
frontend/test/specs/homeControllerSpec.js

<p><b>Feature/Bug description:</b> Hide preview events that are already finalized on the home page.</p>
<p><b>Solution:</b> I created a function in homeController that checks if the end date of the event has passed, if yes it does not let the event be viewed.</p>

Hide finalized events in home page

---

frontend/styles/custom.css

<p><b>Feature/Bug description:</b> In the square "following" there are sizes of the screen, in which the images are very close.
</p>
<p><b>Solution:</b> Put minimum size to image.</p>

Fix square "following"

---

backend/search_module/search_document.py

<p><b>Feature/Bug description:</b> Wrong comment sintax</p>
<p><b>Solution:</b> Use # instead of // to write comments.</p>

Fix comment sintax in search document

---

frontend/notification/notificationService.js

The back button wasn't working.
The error was that AuthService.$onLogout() was trying to call $destroy from firebaseArrayNotifications,
but sometimes this array was undefined.
</p>
I've added a verification to AuthService.$onLogout() method.
</p>

Fix user inactive page's back button

---

frontend/post/post_details.html

The post's "more button" was in post page with no action.
</p>
I've added a verification that doesn't allow the more button to be in post page. This verification uses the directive's property "isPostPage".
</p>

Hide more button in post page

---

frontend/post/post_details.html

<p><b>Feature/Bug description:</b> The button to submit comment in post is not compatible with the system set of colors.</p>
<p><b>Solution:</b> Adding md-colors teal-500 and changing "ESCREVER" to "ENVIAR" in exhibition of button.</p>

Changing color and text of the submit comment button in post

---

frontend/institution/configInstDirective.js
frontend/institution/submit_form.html
frontend/test/specs/configInstDirectiveSpec.js

The portfolio button's message was wrong, It was "Adicionar portfólio" even if the institution's already have one.
</p>
I've created a two functions that handles with some conditions to know if there is a portfolio or not. Thus the controller can choose the right message and icon.
</p>

Fix portfolio's button

---

frontend/auth/configProfileController.js
frontend/auth/config_profile.html
frontend/imageUpload/cropImageService.js
frontend/institution/configInstDirective.js
frontend/institution/create_inst_form.html
frontend/institution/submit_form.html
frontend/styles/custom.css

It wasn't possible to edit the profile's image in mozilla because the browser doesn't work with percentage in the height property and It was missing a $event in the html.
</p>
I've changed the height property from percentage to vh and added $event where it was missing.
</p>

Fix edit profile's image in mozilla

---

frontend/post/post_details.html

Hide update button from post's author
</p>
I've added ng-if="!isPostAuthor()" in the md-menu-item.
</p>

Hide update button from post's author

---

frontend/post/postDirective.js
frontend/post/save_post.html

The pdfs with size greater 5mb weren't attached and the user wasn't informed about it.
</p>
I've added a showToast that is called if the pdf's size is greater than 5mb.
</p>

Fix attach pdf with size greater than 5 mb

---

frontend/app.js
frontend/event/eventController.js
frontend/event/eventDetailsDirective.js
frontend/home/homeController.js
frontend/post/postDetailsDirective.js
frontend/test/specs/postDetailsControllerSpec.js

When a post was deleted its state wasn't been refreshed in the timeline posts. Beyond that, a event that has just been shared wasn't in the timeline till it gets refreshed.
</p>
I've refreshed the timeline's posts in the deletePost method and added the shared event to the timeline's posts, as well.
</p>

Fix delete post and event's consistency

---

backend/models/request_user.py
frontend/institution/managementMembersController.js
frontend/test/specs/managementMembersControllerSpec.js

When a request was accepted, it wasn't removed from the controller.
Besides, the REQUEST_USER notification wasn't been sent because it was missing receiver_key property in requestUser.send_notification method.
</p>
I've removed the request from the controller in acceptRequest function.
I've added receiver_key in requestUser.send_notification method and fixed the sender_key field.
</p>

Fix the accepted requests weren't removed from the controller

---

frontend/home/post_dialog.html
frontend/styles/custom.css

<p><b>Feature/Bug description:</b> The dialog had a white background.</p>
<p><b>Solution:</b> Changed background to transparent and without shadow.</p>
Firefox

Change edit post view

---

frontend/notification/notificationDirective.js
frontend/notification/notifications.html

It was missing $event in some notification actions. This param is required by the mozilla firefox.
</p>
I've added $event where It was missing.
</p>

Adding the missing events in notifications' action

---

frontend/main/main.html

<p><b>Feature/Bug description:</b> Size of backgroud content</p>
<p><b>Solution:</b>Insert flex in main content.
</p>
Before: 
After:

Fix firefox layout

---

frontend/event/eventController.js
frontend/event/event_dialog.html

The create event's button wasn't blocked if it had already been clicked.
</p>
I've added a ng-disabled and controlled it in the dialogController.
</p>

Fix creation of many events at once

---

frontend/post/comment.html

<p><b>Feature/Bug description:</b> Breakline is not displayed in comments and replies.</p>
<p><b>Solution:</b> Adding ng-bind-html to show breakline in comments and replies of post.</p>

Adding breakline in comments and replies

---

frontend/home/color_picker.html

<p><b>Feature/Bug description:</b> Give more spacing between the colors of the user's color picker.</p>
<p><b>Solution:</b> Using the flex-lg and flex-xl directives I added more space in the user's color picker on large screens.</p>

Fix color picker visualization in large screen

---

frontend/styles/custom.css

<p><b>Feature/Bug description:</b> Fix the position of the like and reply buttons that are decentralized in the comments screen.</p>
<p><b>Solution:</b> I changed the CSS of the buttons so that they were centralized.</p>

Fix position of icons buttons like and reply

---

frontend/post/post_details.html

The shared post wasn't showing the line's break.
</p>
Change the css' class in p tag
</p>

Fix missing of broke lines in shared post

---

frontend/home/homeController.js

<p><b>Feature/Bug description:</b>When the user is on home view and click on 'Meu Perfil' or 'Eventos' and then click on home button on toobar, the sidebar selected option does not update to 'Inicio'</p>
<p><b>Solution:</b> it was called the loadStateView function to update the stateView variable before use it in getSelectedItemClass function</p>

fix bug on side menu

---

frontend/event/eventController.js
frontend/event/eventDetailsDirective.js

<p><b>Feature/Bug description:</b> When the edition of event is canceled, the edited informations keep in event page.</p>
<p><b>Solution:</b> Passing function to dialog to reset event object of event_page.</p>

Fixing bug in edit of event

---

frontend/post/postDetailsDirective.js
frontend/test/specs/postDetailsControllerSpec.js

<p><b>Feature/Bug description:</b> Fix view of the user they like in the post on the post details page.</p>
<p><b>Solution:</b> I removed the variable showLikes that was preventing the likes from being viewed in the post.</p>

Fix visulization of likes in post page

---

frontend/event/eventController.js
frontend/event/eventDetailsDirective.js
frontend/event/event_details.html
frontend/test/specs/eventDetailsControllerSpec.js

<p><b>Feature/Bug description:</b>When an event has an image, and that one is removed through the edit event dialog, the image is still shown on the event details view.</p>
<p><b>Solution:</b>It was created a function to verify if the edited event has image. If don't, the image is hidden from the view. </p>

fix bug on event image after editing

---

frontend/post/save_post.html

<p><b>Feature/Bug description:</b> Hide the message that the post must contain a title when the post is empty.</p>
<p><b>Solution:</b> Using the ng-show directive I created a check to know if the post is empty or not if it is, does not show the message that the post should contain a title.</p>

Hide message of required title in save post html

---

frontend/institution/create_inst_form.html

<p><b>Feature/Bug description:</b> That form on google chrome is too close to the top of the page.</p>
<p><b>Solution:</b> The height was changed from 100 to 80.</p>

change create_inst_form height

---

backend/handlers/request_handler.py
backend/handlers/user_request_collection_handler.py
backend/test/request_handler_test.py
backend/test/user_request_collection_handler_test.py

<p><b>Feature/Bug description:</b> When making a request to be a member of an institution the profile of the user is already created before the request is accepted, which causes a bug when selecting the current institution, since the requested institution already appears even without the request being accepted.</p>
<p><b>Solution:</b> I moved the user profile creation of the user request collection handler to the request handler, so that the profile is created only if the request is accepted.</p>

Fix bug of create profile in request user

---

backend/handlers/institution_request_collection_handler.py
backend/handlers/request_handler.py
backend/handlers/user_request_collection_handler.py
backend/service_messages.py
backend/test/institution_request_collection_handler_test.py
backend/test/user_request_collection_handler_test.py
frontend/requests/requestInvitationService.js

<p><b>Feature/Bug description:</b> The user current Institution was not being passed to the appropriate methods to create the notifications for user requests</p>
<p><b>Solution:</b> On institution request collection handler and on request handler, it was added the current institution to the methods send_invites and send_message_notification, respectively. Besides that, it was changed the way the data is sent on user requests </p>

add current institution to user requests

---

backend/handlers/institution_members_handler.py
backend/test/institution_member_handler_test.py

<p><b>Feature/Bug description:</b> The current institution name was not being send on delete members notifications</p>
<p><b>Solution:</b> It was added the user current institution to send_message_notification call and the related tests were updated</p>

Add current institution to delete members notifications

---

frontend/event/event_dialog.html

Even if a state was selected the message "Escolha um estado primeiro" in the city field was showing.
</p>
I've added a missing verification.
</p>

Fix edit event: City verification

---

backend/handlers/institution_handler.py
backend/test/institution_handler_test.py
backend/worker.py

<p><b>Feature/Bug description:</b> The current institution name is not present on delete institution notification</p>
<p><b>Solution:</b> It was added current institution to notification params at institution handler delete method</p>

Add current institution to delete institution notification

---

backend/models/survey_post.py
backend/test/model_test/survey_post_test.py

<p><b>Feature/Bug description:</b>The flow to vote in a survey must pass through two methods in order to vote</p>
<p><b>Solution:</b>Simplify to use only one method, that is generic to binary survey and multiple options survey. In addition, insert a verification to check if the vote for binary survey has only one option selected.</p>

Simplify vote method

---

frontend/post/postDetailsDirective.js
frontend/test/specs/commentControllerSpec.js

<p><b>Feature/Bug description:</b> After deletion of a comment in post page, the comment continue appearing in post page (disappearing after refresh the page).</p>
<p><b>Solution:</b> Changing the delete in array to a filter to the correct deletion of the comment.</p>

Adding filter to correct deletion of a comment by id.

---

backend/handlers/institution_hierarchy_handler.py
backend/test/institution_hierarchy_handler_test.py

<p><b>Feature/Bug description:</b> The user current institution was not being send on notification when the link between two institutions is removed</p>
<p><b>Solution:</b> It was added the user current institution key to the call of send_message_notification,  on delete method, at institution_hierarchy_handler</p>

Add current inst to removed links notifications

---

frontend/post/postDetailsDirective.js
frontend/post/post_details.html

<p><b>Feature/Bug description:</b> When the user open the post page and try to submit a comment, the application hangs. This problem was caused by inconsistency in the handling of comments coming from the backend, in the timeline, they are treated as a comment object and in the post page as a list. This inconsistency made the method of adding comments not work as expected, since the addition was being done using the comment id as the index of the object, for example, comments [id] = comment. When the comments were in the form of the list (On the post page) the addition did not work as expected because the comment id is a very large number, and this causes a very high index to be added to the list, causing an infinite loop in the ng-repeat of comments.</p>
<p><b>Solution:</b> Treat the …

Fix comment in post page

---

frontend/post/timeline.html

<p><b>Feature/Bug description:</b> Add load circle in the timeline if load more posts.</p>
<p><b>Solution:</b> I added load circle in the timeline using load-circle directive.</p>

Add load circle in timeline

---

frontend/auth/configProfileController.js
frontend/auth/config_profile.html

<p><b>Feature/Bug description:</b> The name and acronym of institutions in config_profile page is not clickable.</p>
<p><b>Solution:</b> Adding href in html to make name and acronym of institutions clickable and opening the institution page in a new window of browser.</p>

Making the name of institution clickable in config_profile page

---

frontend/invites/welcome_dialog.html

The tutorial's dialog was broken in small screens
</p>
I've tried to find a position that works in both small and large screens.
</p>

Fix tutorial dialog in small screens

---

frontend/survey/save_survey.html

The survey options' height was higher than It should be.
</p>
I've decreased the max-height property.
</p>

Fixing the survey options' max-height

---

frontend/app.js

<p><b>Feature/Bug description:</b> Preview PDF files wasn't working because of CORS error acusing unaccepted Header "Institution-Authorization".</p>
<p><b>Solution:</b> Restrict the inclusion of that header only to requests to backend api.</p>

Fix introdution of institution authorization header only to backend api requests

---

frontend/event/eventDetailsDirective.js

<p><b>Feature/Bug description:</b> The console show following error in event page: "TypeError: Cannot read property 'official_site' of null".</p>
<p><b>Solution:</b> Adding verification if the property exists before return.</p>

Adding verification before return

---

backend/models/post.py
frontend/post/postDetailsDirective.js
frontend/utils/messageService.js

The reply_comment method wasn't checking if the comment really exists before add the reply.
</p>
I've added a verification in the method and sent a message to the user warning him that the comment has been deleted.
</p>

Fix reply deleted comment

---

frontend/post/postDetailsDirective.js
frontend/post/share_post_dialog.html

Share survey's view was broken. The options was overcoming the card.
</p>
I've changed the html becoming it responsive by adding some flex tags and fixing some css' properties.
For xs-devices I've hidden the content and warned the user with a message.
</p>

Fix share survey view

---

frontend/post/postDetailsDirective.js
frontend/post/post_details.html
frontend/test/specs/postDetailsControllerSpec.js

The comment button wasn't looking like clickable in a deleted post when the post had comments.
</p>
I've fixed the verification in getButtonColor method.
</p>

Fix the comment button color in deleted post

---

frontend/post/post.js
frontend/post/postDirective.js

<p><b>Feature/Bug description:</b> If in youtube url has properties like start time of video (ex.: #t=2m10s), feature like "youtu.be", mobile (m.youtube.com...) and other types of youtube url links, the post doesn't recognize the video and don't plays the video.</p>
<p><b>Solution:</b> Adding a new regex to recognize more youtube url types and adding a match to get only video id to make embed link to plays the video in post.</p>

Adding a new regex to accept more youtube url types and match to get id of video

---

frontend/auth/loginController.js
frontend/auth/reset_password_dialog.html

<p><b>Feature/Bug description:</b> Create new layout for modal reset password.</p>
<p><b>Solution:</b> Using the angular directives, I created the new layout for the dialog of password reset according to what was passed by the design.</p>

Create new layout of reset password modal

---

frontend/post/save_post.html

<p><b>Feature/Bug description:</b> Card-actions are appearing on the create post card even if the post is empty, making the post card larger than necessary.</p>
<p><b>Solution:</b> I added a ng-show in the card-action directive that checks whether the post was populated or not, if yes, displays the buttons.</p>

Fix save post card visualization when the post isn't filled

---

frontend/institution/management_institution_page.html

<p><b>Feature/Bug description:</b> The alignment of the institution's edit information page is right and not centered as it should be.</p>
<p><b>Solution:</b> Change the layout of the edit institution information page (from space-between to space-around).</p>

Fix alignment of edit institution page

---

frontend/institution/institutionController.js

<p><b>Feature/Bug description:</b> When the website of institution don't has http or https the page opened after click is the home page of cis.</p>
<p><b>Solution:</b> Reusing function in Utils.js to add https in url of website of institution.</p>

Fix bug in opening of institution website without http(s).

---

frontend/event/event_page.html

<p><b>Feature/Bug description:</b> The event page in small display was big margins.</p>
<p><b>Solution:</b> Removed margins and used responsiviness.</p>

Fix responsiveness of event page to small screens.

---

frontend/post/pdfDialog.html
frontend/post/pdfViewDirective.js

<p><b>Feature/Bug description:</b> The PDF view dialog is taking a long time to open, allowing the user to click several times to open it.</p>
<p><b>Solution:</b> I added a circular load that allows the modal to open as soon as the user clicks and it waits until the pdf is fully loaded.</p>

 Fix possible multiple click to open PDF dialog 

---

frontend/search/search.html
frontend/search/searchController.js
frontend/test/specs/searchControllerSpec.js

<p><b>Feature/Bug description:</b> When searching for an institution and the angular filter does not find an institution with the specified characteristics, no message appears to the user, making him believe that the search is still being processed.</p>
<p><b>Solution:</b> I created a check that checks if the filter result is empty, if yes it displays a message to the user stating that no such institution has been found.</p>

Fix show message of empty filtered institutions in search page

---

.gitignore
ecis

<p><b>Feature/Bug description:</b> The script to deploy to support app isn't changing the backend URL,
leaving the deployed version accessing an unexistent API.</p>
<p><b>Solution:</b> Change the script to set the correct backend URL before deploy the application. Also, add to the git ignore file the changes made to config.js under support folder.</p>

Fix script to configure backend url when deploying to support app

---

ecis
frontend/config.js
frontend/main/main.html
frontend/main/mainController.js
frontend/styles/custom.css
support/config.js
support/report/reportController.js
support/support/support.html
support/support/supportController.js

<p><b>Feature/Bug description:</b> The platform needs to display which version is running on the browser, to be able to track bugs and new versions available.</p>
<p><b>Solution:</b> Add to the config.js files (on support and frontend) a variable that stores the versions of the app. That variable is controlled by the script, setting up the version right after execute **run** or **deploy** commands. The version will appear on the left lower side of the screen.</p>

Script to add an App Version to be displayed on Frontend and Support apps 

---

frontend/institution/management_institution_page.html

<p><b>Feature/Bug description:</b> The left menu alignment of the institution management screen is different from the home page menu (far right).</p>
<p><b>Solution:</b> I changed the layout-align from space-around to space-between and centralized the cards of edit institution and manage members.</p>

Fix alignment of management institution page

---

frontend/institution/create_inst_form.html

<p><b>Feature/Bug description:</b> Ao criar uma instituição por meio de um convite e inserir a url do website, a mesma não é salva.</p>
<p><b>Solution:</b> I added an ng-model in the input of the website for when the user inserts the site, the same is saved in the model.</p>

Fix save website url when create institution

---

backend/handlers/invite_collection_handler.py
backend/handlers/invite_handler.py
backend/models/institution.py
backend/models/invite_user.py
backend/test/invite_collection_handler_test.py
backend/test/invite_handler_test.py
backend/test/model_test/invite_user_test.py
backend/worker.py
frontend/institution/managementMembersController.js
frontend/institution/management_members.html
frontend/invites/invite.js
frontend/invites/newInviteController.js
frontend/survey/surveyDirective.js
frontend/test/specs/managementMembersControllerSpec.js
frontend/test/specs/newInviteControllerSpec.js
frontend/utils/messageService.js

Make it possible to send many user invites at once.
</p>
Now, the frontend send a list of emails and the invite body to the backend. The backend on the other hand iterates over the list creating an invite for each email and lastly send all the invites' keys to the queue, where the invites are really sent.
</p>

Send multiple user invites

---

frontend/auth/configProfileController.js
frontend/auth/config_profile.html

The system wasn't giving a feedback of user edition. No message, no loading progress.
</p>
I've added the loading-cicle directive and called showToast to shows up when the editing is done.
</p>

Fix missing feedback when editing user profile

---

frontend/event/eventController.js
frontend/event/event_dialog.html

<p><b>Feature/Bug description:</b> When clicking the button to publish the event, the button to return to the previous step is still enabled giving the user the possibility to go back to the previous step and if an error occurs in the publication, it is prevented from proceeding to the next step because the buttons forward and cancel no longer appear.</p>
<p><b>Solution:</b> I disabled the back button when the event is being published so that the user can not return to the previous step, and if an error occurs, the buttons are activated again so that the user will try to publish again.</p>

Fix posibility of return step when saving event

---

frontend/event/event_details.html

<p><b>Feature/Bug description:</b> The date square was out of card.</p>
<p><b>Solution:</b> Set the max heigth of square.</p>

Fix design of event's date in firefox.

---

frontend/institution/configInstDirective.js
frontend/institution/submit_form.html

<p><b>Feature/Bug description:</b> The submit button was available to click again, even after the user has submitted the form, because of the time needed to upload the pdf and/or the image file.</p>
<p><b>Solution:</b>It was set a circular progess to appear when there is image or pdf to upload on submit</p>
<b>When submitting an image</b>
<b>When submitting a pdf</b>

Fix multiple clicks on institution form submit button

---

backend/handlers/reply_comment_handler.py
backend/test/reply_comment_handler_test.py
frontend/notification/notificationDirective.js
frontend/notification/notificationService.js

To differ reply comment from comment notification's message.
</p>
Change the entity_type in the notification and handle this type in the notification's directive.
</p>

Refact reply comment notification's message

---

backend/handlers/post_handler.py
backend/test/post_handler_test.py
frontend/notification/notificationDirective.js
frontend/notification/notificationService.js

Send notification when the admin delete a post from another user.
</p>
I've called send_message_notification if the user is admin in the post_handler
</p>

Send notification when the admin delete a post

---

backend/worker.py

**Feature/Bug description:** When a post is created, a notification is sent to all the post's institution's followers. However, the institution key was being used as entity_key, instead of the post key. So, the follower was unable to access the post page via its notification. 
**Solution:**  The variable inst_key was replaced by entity_key on send_message_notification call, at NotifyFollowersHandler

Fix post notification with unknown key

---

frontend/institution/institutions.html

**Feature/Bug description:** The view if institutions card is not ok for all screen sizes 
**Solution:** Fix to show 3 columns only for extra large screens

Fix institutions page layout

---

frontend/institution/submit_form.html

Change "Adicionar imagem" to "Trocar imagem" in edit institution form.
**Solution:** 

Fix button name in edit institution form

---

frontend/institution/managementMembersController.js

The "Convidado por" field was appearing only when the page was refreshed
**Solution:** 
I've added the sender_name into the invite before its creation

Fix sender_name in invite member

---

backend/handlers/institution_request_handler.py
backend/handlers/invite_handler.py
backend/test/institution_request_handler_test.py
backend/test/invite_handler_test.py

In some handlers the invite's status verification was wrong. It was checking if the invite wasn't accepted but It should check if it was sent.
**Solution:**
Change the verification and add it when it was missing.

Fix invite status verification

---

backend/handlers/institution_collection_handler.py
backend/test/institution_collection_handler_test.py

**Feature/Bug description:** The GET of Institution Collection Handler, has a query to get all institutions in datastore, including the stubs.
**Solution:** Change query to find only active institutions.

Fix query handler to find only active institutions

---

frontend/post/post_details.html
frontend/styles/custom.css

**Feature/Bug description:** In small displays, the name of the institution and the author were superimposed.
**Solution:** Changed the directive to card-title and it is not overwritten.

Fix post layout in small screens

---

frontend/post/post_details.html

**Feature/Bug description:**  The buttons post in small displays are too close.
**Solution:** Hide text in small displays

Hide delete button text of post in small screens

---

ecis
parse_github_prs.py

**Feature/Bug description:** To create a new release it makes necessary to write a description, listing the modifications made to that version. That list comes from the list of merged pull requests from the last release to the moment of the new one. Thinking in optimize the time to generate a release and write that entire list separating into categories, a script was idealized to automate that process.
**Solution:** The script read the Github Pull Requests page searching for merged status and from a specific date (should be the last release date), parse the HTML and extract the relevant information, such as Pull Request title, author name, and number.
That feature's accessible through the command `github-prs` under the main script, example:
./ecis github-prs 2018-03-04
It receives as an …

Script to parse the github PRs page and format to generate release

---

frontend/institution/configInstDirective.js

**Feature/Bug description:** In the creation or edition of an institution the property "country" is not captured by the observer.
**Solution:** Initialize observer before loading the address of the institution.

Fix patch of institution

---

frontend/institution/members.html

**Feature/Bug description:** The border of admin photo, in section "membros" in institution page, is different from the pattern to photos of the CIS.
**Solution:** Adding border-radius in admin photo.

Fix border of admin photo

---

frontend/institution/base_institution_page.html
frontend/institution/institutionController.js

**Feature/Bug description:** The margin between the cover and the elements under it was changing every time an option was on the left-side menu was selected.
**Solution:** The cover height was decreased and it was changed how the institution image and name are organized in the template.
**Desktop view**
**Desktop view on Firefox**
**Mobile view**

fix bug on institution page design

---

frontend/post/postDetailsDirective.js
frontend/post/post_details.html
frontend/styles/custom.css
frontend/utils/utils.js

**Feature/Bug description:** When has a long word in the title of a post the visualization looks strange.
**Solution:** Added a function in Utils to verify if any string is bigger to screen width proportion and calling the correct CSS class to the context.

Fix word break of post title

---

frontend/institution/configInstDirective.js

**Feature/Bug description:** When the institution is edited in the deploy version the console show error and not notify the client if the operation is finalized.
**Solution:** Adding verification if the property 'newInstitution' exists in configInstDirective.js

Fix update of institution

---

frontend/auth/configProfileController.js

**Feature/Bug description:** When a user changes any institution profile and exits the page, is show the confirm dialog.
**Solution:** Cloned user object using cloneDeep, so when changed profile in the user not changed in the new User object.

Fix confirm dialog when changes profile institution

---

frontend/auth/configProfileController.js

When the user remove an institution his current_institution wasn't changing what could create a bug.
**Solution:**
I've called removeInstitution and removeProfile in the removeConection method. Thus, the current_institution is changed once the removeInstitution method call changeInstitution().

Fix remove institution from the user

---

frontend/event/event_details.html

**Feature/Bug description:** When the event image is PNG, the background color of the image was green.
**Solution:** Set color to white.

Fix background image of an event when using PNG format

---

frontend/post/post_details.html
frontend/survey/surveyDetailsDirective.js
frontend/test/specs/surveyDetailsDirectiveSpec.js

**Feature/Bug description:** When two or more users vote in options of a survey, the percentage displayed does not match with the real percentage counting with votes of the other(s) user(s).
**Solution:** Calling reload of the post immediately after the vote action.

Fix inconsistency in percentage of the survey

---

frontend/institution/management_members.html

The calculateHeight method could cause a very strange bug. The screen was shaking when the admin accept the last request.
**Solution:**
I've removed the calculateHeight call and the ng-scrollbar replacing them by a custom-scrollbar class with a auto overflow and a max-height property

Fix management members cards height

---

frontend/institution/managementMembersController.js
frontend/invites/inviteInstitutionController.js
frontend/invites/invite_institution.html
frontend/test/specs/UtilsSpec.js
frontend/utils/utils.js
support/auth/utils.js

The calculateHeight function could make the screen shake in some situations.
**Solution:**
I've removed the function from everywhere it was used and replaced that with some css.

Removing calculateHeight from the system

---

frontend/event/eventController.js

When an error occurs in the event edition the user is sent to home but the dialog doesn't get closed.
**Solution:**
I've called $mdDialog.hide(event) in the error callback function.

Fix edit event error

---

backend/models/user.py
backend/test/institution_handler_test.py
backend/test/institution_member_handler_test.py
backend/test/remove_institution_handler_test.py
backend/worker.py
frontend/auth/configProfileController.js
frontend/test/specs/userSpec.js
frontend/user/user.js

The frontend wasn't updating the user.institutions_admin when deleting an institution. So, when the admin removed an institution he couldn't remove his account yet, because the inst was still there. Besides, the system wasn't send 'DELETED_INSTITUTION' notification because the worker had a little bug. Lastly, the patch object in the configProfileController, I don't know why, was getting the institution's remove operation.
**Solution:**
I've removed the inst from institutions_admin in the frontend, fixed the worker and make a patch without any observer.

Fix remove account after delete an institution

---

frontend/institution/managementMembersController.js
frontend/test/specs/selectEmailsControllerSpec.js

**Feature/Bug description:** When members are invited by csv file and at least one member already been invited, the others are not invited.
**Solution:** Filtering the final list of emails to a list that don't match with the emails of 'sent_invitations' list.

Fix the invite by csv of user already invited

---

frontend/institution/institution_card.html

**Feature/Bug description:** The institution cards were with different height depending on the size of the institution description.
**Solution:** it was set a specific height to institution description.
**Cards with different height**
**Cards with fixed height**
**On large screen**
**On extra large screen**
**On mobile**

Fix bug on institution cards height

---

frontend/styles/custom.css

**Feature/Bug description:** When the background image is white, the image border disappear.
**Solution:** It was added a shadow to the institution image at the floating cover
**Without shadow**
**With shadow**

Fix institution image border at floating cover

---

frontend/styles/custom.css

**Feature/Bug description:** When the background image is white, the image border disappear.
**Solution:**  It was added a shadow to the institution image
**Before**
**After**

Fix institution image border at following institutions

---

backend/handlers/invite_collection_handler.py
backend/test/invite_collection_handler_test.py
frontend/institution/managementMembersController.js
frontend/test/specs/managementMembersControllerSpec.js

**Feature/Bug description:** When the user sends an invitation and then clicks to resend it, it is not possible because the invitation does not yet have the key.
**Solution:** When the invitations are made the post has returned an array that contains key and email objects

Fix resend invite

---

frontend/auth/config_profile.html

The view wasn't refreshing when the user deleted an institution in his profile's configuration.
**Solution:**
I've changed the ng-repeat to iterate for user.institutions instead of newUser.institutions once only the user was modified when the operation was done.

Fix remove institution in configProfile

---

frontend/event/event_dialog.html

When the user selected the end_time before the start_time, the last one couldn't be defined later.
**Solution:**
I've disabled the end_time when the start_time is not defined.

Fix event's end_time when the start_time is not defined

---

backend/handlers/institution_request_handler.py
backend/test/institution_request_handler_test.py

The permissions were being added to the wrong user. They should be added to the sender but were being added to the super admin.
**Solution:**
I've called sender.add_permissions instead of user.add_permissions.

Fix accept request to create institution

---

frontend/institution/management_members.html

**Feature/Bug description:**  The template for manage admin was hidded using 'ng-if=false'.
**TODO/FIXME:** Remove the ng-if-false after solve the bug

Hide manage admins tab

---

frontend/main/mainController.js
frontend/test/specs/mainControllerSpec.js

When an user tried to change the institution as soon as the admin accepted his request many errors appeared in the console coming from the changeInstitution function because the user in mainCtrl wasn't updated. 
**Solution:**
I've refreshed the user before call user.changeInstitution().

Fix change institution in mainCtrl

---

backend/models/invite_user_adm.py
backend/test/model_test/invite_user_adm_test.py
frontend/institution/managementMembersController.js
frontend/institution/management_members.html
frontend/invites/processInviteUserAdmController.js
frontend/test/specs/processInviteUserAdmControllerSpec.js
frontend/test/specs/transferAdminControllerSpec.js

**Feature/Bug description:** The admin transfer page was allowing the admin to send an invitation to himself.
**Solution:** Block, both on the server and on the client, sending the admin transfer invitation to itself.

Fix send invit user adm

---

frontend/index.html
frontend/institution/address.js
frontend/institution/configInstDirective.js
frontend/test/specs/configInstDirectiveSpec.js

**Feature/Bug description:** When the inactive user requests the creation of the institution, it can create without responding all the attributes of the address, because the object "address" has only the attribute "country"
**Solution:** Added array that contains all the attributes that should be answered when the country is Brazil.

Fix create institution

---

frontend/notification/notificationDirective.js
frontend/test/specs/userSpec.js
frontend/user/user.js

Handle with current_institution in the backend became a problem to us in this situation. The user who the request came from wasn't a current_institution's member anymore, what make the server raise an exception and making the notification's action work with problem.
**Solution:**
I've changed the current_institution before make the request to the server to reload the user.

Fix remove member notification action

---

frontend/institution/management_members.html

The titles were out of pattern.
**Solution:**
I've changed the titles to lower case pattern.

Standardize card titles in management page

---

frontend/invites/new_invite_page.html

**Feature/Bug description:** On screens heights less than 900px the new invite form was shaking every time a field was select. This happens because of the card has its height increased when a new field is selected, so it gets bigger than the page and the scrollbar appears for an instant and than disappear.
**Solution:** 
The md-content overflow property was set to hidden.
**Bug**
**Solved**

Fix bug on new invite form shaking

---

frontend/institution/configInstDirective.js
frontend/test/specs/configInstDirectiveSpec.js

**Feature/Bug description:** When the user reloads the creat_inst_form page in case of an invite, the behavior of form becomes to request create an institution.
**Solution:** Adding a case to verify if the user is not active and no has institution invites, the behavior of form should be to request to create an institution, in this case. Otherwise, redirect to signin page to recognize the invite again and get the institutionKey of the stub institution.

Fix the reload on create_inst_form page in case of invite to create institution

---

frontend/post/share_post_dialog.html

**Feature/Bug description:** The image exceeds the layout in modal of share event.
**Solution:** Adding a broken line to adjust the preview display of event.

Fix the overflow of event image in modal of share event

---

frontend/main/main.html

**Feature/Bug description:** When creating an event with a very large image, entering the event page and scrolling the page, the event sharing button was overlapping the report button.
**Solution:** I changed the z-index of the report button so it always stays in front of the page.

Fix position of report button

---

frontend/institution/institutionController.js

**Feature/Bug description:** When you open the institution edit page, an error occurred because in setScrollListener you use the content attribute, however, the content object does not exist.
**Solution:** Added default object the content.

Fix Institution Controller when use the content object and these not exist.

---

backend/models/institution.py
frontend/institution/institutionController.js

**Feature/Bug description:** When transferring the administration of an institution the email of new admin didn't change.
**Solution:** Pass the email when set the admin.

Fix email of new admin when transferring the administration of an institution

---

frontend/invites/new_invite_page.html

**Feature/Bug description:** The modal of the invite is not centered on the screen.
**Solution:** Adding tags to align with the center of the screen.

Fix the position of invite modal

---

frontend/event/eventDetailsDirective.js

**Feature/Bug description:** When the event page is opened the console displays the following error: cannot read property 'institution_key' of null.
**Solution:** Adding verification if the event is defined before the return of functions 'isInstitutionAdmin' and 'canChange'.

Fix null event on event page

---

frontend/home/homeController.js
support/auth/utils.js

**Feature/Bug description:** When you change the cover color of an institution and enter the user edit information page and try to edit an institution's profile, the editing dialog does not open.
**Solution:** I changed how to clone the user when the color change dialog of the institution cover is opened because the cloning method previously used could not clone lists, and this caused bugs in the edition of user profiles because of this method transformant lists in objects which are not lists.

Fix change institution profile color

---

frontend/event/eventDetailsDirective.js

**Feature/Bug description:** When the event page is opened the console displays the following error: cannot read property 'institution_key' of null.
**Solution:** Adding verification if the event is defined.

Fix null event in event page

---

frontend/event/eventDetailsDirective.js
frontend/event/event_page.html
frontend/test/specs/eventDetailsControllerSpec.js

The user was being redirected to the event's page where there was an inconsistency because the event was still there.
**Solution:**
I've set the event's state to deleted in the success function and changed the html to work according to the event's state.

Fix delete event

---

backend/handlers/event_handler.py
backend/test/event_handler_test.py
frontend/utils/messageService.js

When the event was deleted the user still could access it by its url.
**Solution:**
I've checked the event's state before answer the request.

Fix deleted event accessible by URL

---

frontend/invites/newInviteController.js

**Feature/Bug description:** When the user has more than one invite, the tutorial of cis appears above the next invite.
**Solution:** Adding verification if the user has no invites before calling the tutorial dialog.

Fix tutorial appearing in invite page

---

frontend/institution/institutionController.js
frontend/utils/messageService.js

It was missing an error function that should send a message to the user.
**Solution:**
I've passed a second function to .then that handles with possible error and called showToast inside of it.

Fix missing error function in removeInst

---

frontend/institution/create_inst_form.html

The bar was appearing even in the fourth step.
**Solution:**
I've moved the ng-if statement to the parent div.

Fix create-institution-form's steps bar's show condition

---

backend/handlers/institution_request_handler.py
frontend/invites/inviteInstitutionController.js
frontend/invites/invite_institution.html
frontend/test/specs/inviteInstitutionControllerSpec.js

It was missing the json_response decorator in the delete method and It should open the dialog when the md-list-item is clicked.
**Solution:**
I've called openPendingRequestsDialog when the md-list-item is clicked, removed the accept and reject button and their functions and tests.

Fix requested invitations in invite institution's page

---

frontend/user/profile.html

**Feature/Bug description:** The profile dialog height was varying depending on the number of user profiles; and the its width was varying depending on the institution name on one of the user profiles.
**Solution:** It was fixed the dialog max-height and width
**Chrome**
**Firefox**
**Mobile**

Fix profile dialog height and width

---

frontend/event/event_details.html

**Feature/Bug description:** When the begging and end date of the event was in the same month, the month name was not centralized
**Solution:** The element padding was replaced by the directive layout-alignment
**Event on event page**
**Event on event datails page**

Centralize event month name

---

frontend/event/eventController.js
frontend/institution/configInstDirective.js
frontend/invites/newInviteController.js
frontend/post/postDirective.js

**Feature/Bug description:** The way to create the object watchers to later create the modification patch is old, still using the jsonpatch library directly.
**Solution:** I have changed the way I generate watchers, instead of directly using the jsonpatch library, now uses the observerRecorderService service, which was created to better manage these observers.

Use ObserverRecorderService for generate jsonpatch observer

---

backend/handlers/post_collection_handler.py

**Feature/Bug description:** When the event author shares your event, you receive the notification.
**Solution:** Added verification that not send the notification to event author.

Fix notification when the author share yourself event 

---

frontend/post/postDetailsDirective.js
frontend/utils/utils.js

**Feature/Bug description:** If has a bigger URL in a post and this URL exceeds the limit of chars to display in the timeline the post shows the HTML tags and don't generate a hyperlink.
**Solution:** Creating an algorithm to find the HTML tags to show the hyperlink and verify if the end of tags is above of limit of the text, isolate the position of the first occurrence which exceeds the limit of text and replaces the limit of text to support the complete hyperlink.

Fix long url bigger than limit of text in post

---

frontend/home/home.html
frontend/styles/custom.css

**Feature/Bug description:** The right navbar "Próximos eventos" contains icons not aligned in Mozilla Firefox.
**Solution:** Adding layout-align and changing the CSS classes to work fine in Mozilla Firefox and Chrome too.

Fix the align of next events in mozilla firefox

---

frontend/home/homeController.js
frontend/institution/management_institution_page.html
frontend/notification/notificationDirective.js
frontend/test/specs/colorPickerControllerSpec.js
frontend/user/left_nav.html
frontend/user/user.js

**Feature/Bug description:** By clicking on the notification that the user has been deleted from an institution the color of the user's cover changes, and if it is clicked several times, it changes with each click given in the notification.
**Solution:** I checked if the notification had already been clicked, if yes, no longer reload the server user and also modified the way to get the color of the user's cover, the color was being saved directly in the user's current institution, and now own profile.

Fix change color when click delete member notification

---

backend/models/institution.py
backend/models/user.py
backend/test/user_institutions_handler_test.py
frontend/test/specs/userSpec.js
frontend/user/user.js

**Feature/Bug description:**  When remove link between member and institution the user unfollow institution.
**Solution:** Didn't unfollow.

Don't unfollow institution when remove link between member and institution.

---

backend/handlers/institution_handler.py
backend/models/invite_institution_children.py
backend/models/invite_institution_parent.py
frontend/notification/notificationDirective.js
frontend/notification/notificationService.js
frontend/notification/notifications_page.html

**Feature/Bug description:** When an invitation to create a daughter institution was sent and the invited user accepts the invitation, the notification that that user accepted the invitation is wrong.
**Solution:** I created a new notification type 'ACCEPT_INVITE_HIERARCHY' to show the message that the institution was created and, on the backend, set the send_reponse_notification of the invite institution children model so that it sends the correct notification.

Fix notification of accept invite intitution

---

frontend/home/homeController.js
frontend/post/postDetailsDirective.js
frontend/post/postDirective.js
frontend/test/specs/postDetailsControllerSpec.js
frontend/test/specs/postDirectiveSpec.js
frontend/test/specs/userSpec.js
frontend/user/user.js

This function was only checking if the user was the author or the admin, but the user should be able to delete the post if he has the permission for.
**Solution:**
I've made a different approach, checking the user permissions instead of check if he is the adm.

Changing the way that the showButtonDelete of post works

---

frontend/institution/management_institution_page.html

There was no button to go home from institution's management page
**Solution:**
Add another md-menu-item with the button

Add home button in institution's management  page

---

frontend/institution/management_institution_page.html

The institution name wasn't clickable in its management's page.
**Solution:**
I've added a <a> tag with the properly properties.

Improving inst's name in management page

---

backend/handlers/event_collection_handler.py
backend/handlers/event_handler.py
backend/test/event_collection_handler_test.py
backend/test/event_handler_test.py
frontend/event/eventController.js
frontend/event/eventDetailsDirective.js
frontend/test/specs/eventDetailsControllerSpec.js
frontend/test/specs/eventDialogCtrlSpec.js

The event's actions checking wasn't using permissions.
**Solution:**
I've used permissions to check some actions in events.

Check event's actions with permissions

---

frontend/institution/managementMembersController.js
frontend/institution/management_members.html
frontend/requests/requestProcessingController.js
frontend/requests/request_processing.html
frontend/test/specs/managementMembersControllerSpec.js

**Feature/Bug description:**  When you receive a request to be a member of an institution and enter the membership management page to accept, the form of acceptance is different from when the user clicks on the notification.
**Solution:** I've changed how to accept requests to be a member of the member management page so that it complies with the notification.

Show accept request dialog when click in request on manage member page

---

backend/handlers/institution_handler.py
frontend/app.js
frontend/institution/base_institution_page.html
frontend/institution/institutionController.js
frontend/institution/institutional_links.html
frontend/test/specs/institutionControllerSpec.js
frontend/test/specs/institutionLinksControllerSpec.js

**Feature/Bug description:** Enabling option in the left menu of institution page to go to the institutional links page. And creating this page.
**Solution:** Adding a short controller to show the information of institutional links and making a view to this.

Creating the page to show institutional links of an institution

---

frontend/invites/inviteInstHierarchieController.js
frontend/invites/invite_institution_hierarchie.html
frontend/test/inviteInstHierarchieControllerSpec.js

**Feature/Bug description:** When removeLink method is called it returns an error in Firefox, that event was undefined.
**Solution:** Pass event to the function by HTML.

Fix remove link between institution in firefox

---

frontend/notification/notifications_page.html

**Feature/Bug description:** The notifications page are broken card on Mozilla Firefox and don't show the full description in all browsers.
**Solution:** Changing the location of 'flex' in HTML and fixing the card to contain all notifications and adjusting the styles to display the full description of notifications.
The card now shows all notifications without broken in Mozilla Firefox.
Displaying full description in small screens.
Displaying full description in medium screens too.

Fix notification page

---

frontend/institution/managementMembersController.js
frontend/test/specs/managementMembersControllerSpec.js

**Feature/Bug description:** The user at this moment can send the invite when emails fields are empty.
**Solution:** Added verification in the method isValidAllEmails.

Fix invite members passing empty emails

---

backend/handlers/post_collection_handler.py
backend/test/post_collection_handler_test.py
backend/worker.py

**Feature/Bug description:** When sharing a post the notification that is sent is wrong because the institution that is sent in the notification is not the institution in which the original post was created.
**Solution:** In the send_message_Notification method used in postNotificationsHandler I pass the key of the post that was shared when it exists, if there is no key to the original post.

Fix shared post notification

---

frontend/invites/inviteInstHierarchieController.js
frontend/invites/invite_institution_hierarchie.html
frontend/test/inviteInstHierarchieControllerSpec.js

**Feature/Bug description:** When removes the link between institutions if the super-institution admin is admin of substitution too, the user can see the button to delete substitution. 
**Solution:** Show button when the user has permission and has the link between institutions.

Fix delete specific institution button for children.

---

backend/handlers/post_collection_handler.py
backend/test/post_collection_handler_test.py

**Feature/Bug description:** Event author shouldn't receive notification when herself share the event.
**Solution:** Fix verification

Fix share event notification

---

backend/handlers/like_handler.py
backend/test/like_post_handler_test.py

**Feature/Bug description:** When a user creates a post and then deletes it, if another user who is viewing the post does not refresh the page, it still succeeds in like the post.
**Solution:** I added a check in the like_handler that checks if the post is deleted, if yes, does not let give like.

Fix like post when deleted post

---

backend/handlers/post_handler.py

**Feature/Bug description:** When a user deletes a post, the notification sent does not have the current institution.
**Solution:** I sent the user's current institution along with the notification that the post was deleted.

Fix notification of delete post

---

backend/handlers/institution_children_request_handler.py
backend/handlers/institution_parent_request_handler.py

**Feature/Bug description:** When to accept or reject the link between institutions, the current institution of notification is wrong.
**Solution:** Changed the current_institution when sending the notification.
antes

Fix link notification between institutions

---

backend/handlers/institution_handler.py
backend/models/institution.py
backend/test/institution_handler_test.py
backend/test/remove_institution_handler_test.py
backend/worker.py

The institution's removal process wasn't being done in a queue. Sometimes the code was going down in the hierarchy right inside of the handler, making this kind of request very slow. Besides, the get_all_parent_admins method was wrong.
**Solution:**
I've refactored the remove_institution method what allowed me to move the hierarchy removal to the queue.
I've fixed the get_all_parent_admins method.

Moving the institution's removal to the queue.

---

backend/models/request.py
backend/test/model_test/request_institution_test.py
frontend/invites/suggestInstitutionController.js

When an institution reject a link and the other keeps that link, the first one can't try to make the link again. The system says they are already linked.
**Solution:**
I've checked the link from both sides instead of just one.

Fix link's checking between institutions

---

backend/handlers/reply_comment_handler.py
backend/models/post.py
backend/test/like_reply_handler_test.py

**Feature/Bug description:** When many users reply the comment in the same moment, returns concurrence error.
**Solution:** Added ndb.transactional in the method that adds the reply.

Fix concurrence problem in reply comment.

---

frontend/post/postDirective.js

**Feature/Bug description:** When a user creates a post and opens the modal edit post and tries to edit it if the post already has action, this edition does not work and no message appears to the user informing that the operation did not work.
**Solution:** I added an error message when the user can no longer edit the post and the post editing fails.

Fix show message if edit post is fail

---

backend/handlers/institution_handler.py
backend/utils.py
backend/worker.py
frontend/notification/notificationDirective.js
frontend/test/specs/userSpec.js
frontend/user/user.js

There was a problem with setup_current_institution because it was verifying if the user was a member. So, when a DELETED_INSTITUTION notification was raised and the user clicked on it, the notification's action should change the current institution before make the request to refresh the institution because of the setup_current_institution's verification, once the user was no longer member of the deleted institution.
**Solution:**
I've removed the verification, removed the method that should change the current institution and notified the users properly.

Fix institution removal notification process

---

backend/models/institution.py
backend/worker.py

The method was calling itself to the children_institutions and wasn't verifying if the link was really confirmed.
**Solution:** 
Verify the link before the recursion's call.

Fix add_permission_to_children method

---

backend/handlers/event_handler.py
backend/handlers/invite_collection_handler.py
backend/handlers/post_handler.py
backend/handlers/resend_invite_handler.py

**Feature/Bug description:** In some handlers the verification if the user has permission to do anything are with 'assert(not user.has_permission...)'. Using check_permission changes the responsibility to verify it has permission and throws the exception to the user model.
**Solution:** Changing the uses of has_permission with assert to check_permission only to enter into a pattern with the rest of code.

Refactoring the uses of assert with 'has_permission' directly to 'check_permission'

---

backend/handlers/institution_hierarchy_handler.py
backend/test/remove_admin_permissions_hierarchy_test.py
backend/worker.py

The method wasn't going up in the hierarchy removing the permissions.
**Solution:**
I've got the parent_admins and iterate over them removing the permissions when it should be removed.

Fix remove admin permissions handler

---

.gitignore
backend/handlers/institution_children_request_collection_handler.py
backend/handlers/institution_parent_request_collection_handler.py
backend/models/institution.py
backend/test/institution_children_request_collection_handler_test.py
backend/test/institution_parent_request_collection_handler_test.py
backend/test/mocks.py
backend/test/model_test/institution_test.py
frontend/invites/inviteInstHierarchieController.js
frontend/invites/invite_institution_hierarchie.html
frontend/invites/suggestInstitutionController.js
frontend/utils/messageService.js

**Feature/Bug description:** It was possible to create a hierarchical loop. For example, a hierarchically higher institution could invite one of its subordinated institutions to be its parent.
**Solution:** It was created a verification, at the handlers responsible for the creation of parent and child request, to identify and forbid the creation possible hierarchical loop requests.

Forbid hierarchical loop

---

frontend/notification/notifications_page.html
frontend/styles/custom.css

Differ read notifications from unread notifications.
**Solution:**
Add a color to the background if the notification is not read yet.

Improve notification's page view 

---

frontend/invites/newInviteController.js
frontend/invites/new_invite_page.html
frontend/notification/notificationDirective.js

**Feature/Bug description:** When an invitation to create an institution is sent and the user clicks the notification that arrives but does not accept or reject the invitation, it is prevented from clicking again to take the action.
**Solution:** I let the user click on the notification even though it has already been read and redirected it to the invitations page, and I've created a verification to see if the invitation has already been processed or not, if it does, it will display a message that it has already been processed.

Fix invite notifification click when is already read

---

frontend/main/mainController.js
frontend/user/left_nav.html

**Feature/Bug description:** When a user sent request to create an institution the notification is displayed to admin in two options of left menu on the homepage.
**Solution:** Fix the counting of invitations to a specific variable for links between institutions.
Showing only in invites or only in institutional links (except if has the two types of request)

Fix the notification in wrong option of left menu on home page

---

backend/handlers/institution_hierarchy_handler.py
backend/test/institution_hierarchy_handler_test.py
frontend/notification/notificationDirective.js
frontend/notification/notificationService.js

**Feature/Bug description:** The name of the link removal notification between institutions is bad, and the action when clicking on the notification is wrong, as there is a state.go that is pointing to the post page.
**Solution:** Change the notification name from INSTITUTION to REMOVE_INSTITUTION_LINK and remove the state.go

Refact remove institution link notification

---

backend/handlers/institution_children_request_collection_handler.py
backend/models/institution.py
backend/models/request.py
backend/test/model_test/institution_test.py
backend/test/model_test/request_institution_test.py
frontend/institution/institution.js
frontend/invites/inviteInstHierarchieController.js
frontend/invites/suggestInstitutionController.js
frontend/test/specs/institutionSpec.js
frontend/utils/messageService.js

**Feature/Bug description:** Previously, when a already rejected child request and tries to send the same invite again, the request is duplicated in the list. Besides that, the requested institution was added again as a children institution.
**Solution:** On client, I added a verification to the method addChildInst, to check if that institution is already a child, if so, it is not added to the list. On server, I created a method to add a child, at Institution model, to prevent the same institution be added twice to the children institutions.

Fix request child institution

---

backend/handlers/institution_children_request_handler.py
backend/handlers/institution_parent_request_handler.py
backend/models/request_institution_children.py
backend/models/request_institution_parent.py
backend/send_email_hierarchy/request_link_email_sender.py
backend/templates/reject_institutional_link.html
backend/util/strings_pt_br.py

**Feature/Bug description:** There are not email template to reject institution links on the platform.
**Solution:** Created HTML template based on design and adding new send_response_email to institution_parent and institution_children requests.
**Hotmail**
**Gmail**

Creating email template to reject institution links

---

frontend/institution/base_institution_page.html

**Feature/Bug description:** The photo background of institutions which are PNG file is the same as the cover. In some cases, this can be confused because do not has a distinction between cover color and photo color.
**Solution:** Adding pattern of the white background for pictures.

Fix background of institution photo

---

frontend/institution/members.html

The ng-click was duplicated. One to the external div and another to the div that wraps the admin name. So, when the click was right in the name, two ng-clicks were called making the profile show twice. 
**Solution:**
I've removed the internal ng-click.

Fix admin profile visualization

---

frontend/institution/institution.js
frontend/invites/invite_institution_hierarchie.html

When the two or more children institution's invite were created they're not appearing in the view because the function that checks if they should be added to the institution.children_institutions or not was checking if there was an invite with the same key as the current invite and the invites didn't have any key, once they hasn't gone to the backend, so, the function wasn't allowing the addition because undefined === undefined was returning true, what made it realize that there was an invite with the same key. 
**Solution:**
I've checked if the invites have the key before checking if it was equals to the current invite's key.

Fix addChildInst function

---

backend/handlers/institution_members_handler.py
backend/send_email_hierarchy/remove_member_email_sender.py
backend/templates/rejected_request_user_email.html
backend/templates/remove_member_email.html
backend/templates/request_user_email.html
frontend/institution/removeMemberDialog.html

**Feature/Bug description:** When administration removes the member, it can place the justification text with undefined size and the old member will receive the email that was with the old design.
**Solution:** Changed layout of email, and defined length to justification in the frontend.
**Hotmail:**
**Gmail:**

Remove member email

---

frontend/requests/requestProcessingController.js
frontend/requests/request_processing.html
frontend/test/specs/requestProcessingControllerSpec.js

When a institution that has parent received a REQUEST_CHILDREN and the admin accept this the permissions of the previous parent admin weren't removed. 
**Solution:**
I've forked the flow in two steps: In the first one the user is warned that the previous link is gonna be removed. If he accepts it, the handler that removes the link is called and the permissions is gone too. In the second one the user answers about the new link.

Fix change institution parent

---

backend/handlers/search_handler.py
backend/models/institution.py
backend/models/user.py
backend/search_module/__init__.py
backend/search_module/search_document.py
backend/search_module/search_institution.py
backend/search_module/search_user.py
backend/test/invite_handler_test.py
backend/test/resend_invite_handler_test.py

**Feature/Bug description:** The search modules imports made in the backend are extensive and difficult to read.
Example:
```python
from search_module.search_institution import SearchInstitution
```
**Solution:** I set up the __init__.py file so that it recognizes all packet models by simplifying imports and making reading easier.
Example:
```python
from search_module import SearchInstitution
```
**Refactored search modules:**
* SearchDocument
* SearchInstitution
* SearchUser

Refact search modules imports

---

backend/handlers/institution_hierarchy_handler.py
backend/handlers/institution_members_handler.py
backend/handlers/user_institutions_handler.py
backend/models/invite.py
backend/models/invite_institution.py
backend/models/invite_user.py
backend/models/request_institution.py
backend/models/request_institution_children.py
backend/models/request_institution_parent.py
backend/models/request_user.py
backend/send_email_hierarchy/__init__.py
backend/send_email_hierarchy/accepted_institution_email_sender.py
backend/send_email_hierarchy/email_sender.py
backend/send_email_hierarchy/invite_institution_email_sender.py
backend/send_email_hierarchy/invite_user_email_sender.py
backend/send_email_hierarchy/leave_institution_email_sender.py
backend/send_email_hierarchy/remove_institution_email_sender.py
backend/send_email_hierarchy/remove_member_email_sender.py
backend/send_email_hierarchy/request_link_email_sender.py
backend/send_email_hierarchy/request_user_email_sender.py
backend/worker.py

**Feature/Bug description:** The send email hierarchy modules imports made in the backend are extensive and difficult to read.
Example:
```python
from send_email_hierarchy.accepted_institution_email_sender import AcceptedInstitutionEmailSender
```
**Solution:** I set up the __init__.py file so that it recognizes all packet models by simplifying imports and making reading easier.
Example:
```python
from send_email_hierarchy import AcceptedInstitutionEmailSender
```
**Refactored email modules:**
* AcceptedInstitutionEmailSender
* EmailSender
* InviteInstitutionEmailSender
* InviteUserEmailsSender
* LeaveInstitutionEmailSender
* RemoveInstitutionEmailSender
* RemoveMemberEmailSender
* RequestLinkEmailSender
* RequestUserEmailSender

Refact send email hierarchy modules import

---

frontend/survey/panel-voters.html
frontend/survey/surveyDetailsDirective.js
frontend/test/specs/surveyDetailsDirectiveSpec.js

The voters' names were overtaking the limit they should have making the view weird. 
**Solution:**
I've added a md-3-line class to md-list-item and limited the max characters quantity showed by name.

Fix survey voters' names

---

frontend/institution/managementMembersController.js
frontend/institution/management_members.html
frontend/test/specs/managementMembersControllerSpec.js

When the name was too large the view's behavior was weird. The height between the first name's line and the second one was larger than it should.
**Solution:**
I've set the line-height property.

Fix adm name in management page

---

frontend/post/postDirective.js
frontend/survey/surveyDirective.js
frontend/test/specs/submitFormListenerServiceSpec.js
frontend/utils/submitFormListenerService.js

**Feature/Bug description:** When creating a survey type post and trying to move to another page, the dialog indicating that unsaved changes appear, even after the post has already been created.
**Solution:** I created a function in the submitFormListener service that allows a given object to stop being observed, and I used it in the surveyController to stop observing the post created when it is posted.

Fix create survey post

---

backend/models/invite.py
backend/send_email_hierarchy/email_sender.py
backend/send_email_hierarchy/remove_institution_email_sender.py
queue.yaml

The emails were being sent from the notifications queue, what doesn't make sense.
**Solution:**
I've added another queue in queue.yml and changed the method that add the emails' tasks, making it enqueue in emails' queue.

Split notifications queue

---

backend/handlers/invite_collection_handler.py
backend/test/invite_collection_handler_test.py
frontend/invites/inviteService.js
frontend/test/specs/inviteServiceSpec.js

**Feature/Bug description:** The way the hierarchy and user invitations were being sent was inconsistent because in the user invitation the data is in the invite body attribute and the hierarchy is in the attribute data.
**Solution:** I've put the invitation invitations data on the invite_body as well as the user's data.

Refact send invite hierarchy

---

backend/handlers/institution_handler.py
backend/handlers/like_handler.py
backend/test/institution_handler_test.py
frontend/institution/institutionService.js

The method shouldn't be a post once it wasn't creating any new entity, it was only updating a institution's stub to change its state to active and update the data.
**Solution:**
The method became a put, what makes sense because it updates the entity.

Refact institution handler's post method

---

backend/templates/rejected_institution_request_email.html
backend/templates/request_institution_email.html

**Feature/Bug description:** In HTML, the image used to represent the institution was the default image of the user.
**Solution:** Changed image to  the default image of the institution.

Fix html of request_inst email 

---

backend/handlers/post_handler.py
backend/test/post_handler_test.py

There was an unnecessary try except block. Besides, the key received as param was named without the pattern.
**Solution:**
Remove try except block and rename url_string.

Improving post_handler's patch method

---

frontend/requests/request_processing.html

**Feature/Bug description:** The visualization of dialog to confirm reject of link request are broke.
**Solution:** Adding layout directives solve the problem.

Fix the confirm reject dialog of request link between institutions

---

backend/handlers/event_handler.py

The received param was out of pattern.
**Solution:**
I've renamed the param to keep it in pattern.

Improving event_handler's get method

---

frontend/main/main.html
frontend/user/left_nav.html

**Feature/Bug description:** In small screens the user can not access the menu options.
**Solution:** Making visible in small screens.
**TODO/FIXME:** In very small screens the search option in right side of screen still broken.

Toggle left menu in small screens

---

frontend/post/share_post_dialog.html
frontend/styles/custom.css

**Feature/Bug description:** The header of view to share event are broken.
**Solution:** Define the heigth to show header completely.

Fix the header of shared event with image

---

frontend/institution/management_institution_page.html

**Feature/Bug description:** The left menu for small screens don't show your content in the institution managment page.
**Solution:** Removing the "hide" tag resolve the problem.

Fix the left menu in institution managment page

---

frontend/invites/new_invite_page.html

**Feature/Bug description:** The accept invitations page was broken in mozilla.
**Solution:** Remove the max-height from the div above the md-card and add margin.

Remove max-height of div

---

frontend/event/event_dialog.html

The was able to insert videos and links without any description in event creation.
**Solution:**
I've changed the descriptions' requirements. Thus, for any video or link inserted, its description is required.

Fix video and links' descriptions requirements in event creation

---

frontend/event/event_dialog.html

**Feature/Bug description:** The dialog to create event is not scrolling to show buttons in small screens. Also the fields of videos and links are very small.
**Solution:** Adjusting HTML to work fine and show complete modal in Mozilla Firefox.

Fix dialog of create of event

---

frontend/institution/managementMembersController.js
frontend/test/specs/managementMembersControllerSpec.js

**Feature/Bug description:** When send a user invitation, an error occurs on the console stating that cannot read property invites of undefined.
**Solution:** Adjust the response of the InviteService.sendInviteUser method so that it no longer uses response.data.invites but response.invites.

Fix send invite user frontend

---

frontend/post/post_details.html

**Feature/Bug description:** When voting on a poll that was shared, the vote does not appear to the user and on the console, an error message appears stating that the reloadPost method is not a function.
**Solution:** Pass the reloadPost function from the postDetailsController to the survey-directive.

Fix vote in shared survey post

---

frontend/app.js
frontend/event/event.html
frontend/event/eventController.js
frontend/event/eventDetailsDirective.js
frontend/event/eventPageController.js
frontend/event/event_page.html
frontend/home/homeController.js
frontend/institution/institution_events.html
frontend/post/postDetailsDirective.js
frontend/post/post_details.html
frontend/post/sharePostController.js
frontend/post/share_post_dialog.html
frontend/test/specs/eventPageControllerSpec.js
frontend/test/specs/sharePostControllerSpec.js

It was missing the timeline's posts in eventDetailsController and in EventPageController. Thus, when a event was shared, it wasn't added to the array.
**Solution:**
I've passed through the controllers that call event-details or go to EventPage passing the timeline's posts when changing the state or marking the directive.

Fix share event in event's page and in event's details

---

frontend/post/share_post_dialog.html

**Feature/Bug description:** The layout of the post sharing dialog is strange because there is a large space between the post title and its contents.
**Solution:** Using css and angular directives I removed excess white space between the title of the post and its content.

Fix share post dialog

---

backend/handlers/vote_handler.py
backend/test/vote_handler_test.py
frontend/post/postDetailsDirective.js
frontend/post/post_details.html
frontend/survey/surveyDetailsDirective.js
frontend/test/specs/surveyDetailsDirectiveSpec.js

**Feature/Bug description:** If there is the survey and search survey, and any user votes for the original search, the search share options disappear. As the type_survey variable of the search is changed to false, the function that ranks if the post is the search does not recognize the post as such.
**Solution:** Put return in the request when voting the survey, and update the options of the survey.

Fix vote survey

---

backend/handlers/post_collection_handler.py
backend/test/post_collection_handler_test.py
backend/worker.py

The worker's AddPostInstitution handler was useless once its operations were very simple.
**Solution:**
I've removed the handler and now the post is added in PostCollectionHandler.

Removing AddPostInstitution handler

---

frontend/institution/managementMembersController.js

The showToast was been called twice, once by managementMembersController and another by HttpService. This occurs because inviteService calls HttpService and managementMembersController calls InviteService.
**Solution:**
Remove showToast from managementMembersController.sendUserInvite()

Remove duplicated showToast in sendUserInvite

---

backend/models/institution.py
backend/test/institution_children_request_handler_test.py
backend/test/institution_parent_request_handler_test.py
backend/test/model_test/institution_test.py
backend/worker.py

**Feature/Bug description:** When an institution A sends a request to institution B to be daughter and B rejects, A passes an unconfirmed link to B. If A sends a request for B to be a parent, and B confirms an infinite loop error is generated in the worker.
**Solution:** Modify the verify_connection method on the institution template so that it only verifies whether one institution is the parent or child of other of the other and not both checks at the same time.

Fix loop when create link between institutions

---

frontend/index.html
frontend/notification/notificationMessageCreatorService.js
frontend/notification/notificationService.js

**Feature/Bug description:** Due to a large number of notifications in the system, the service notificationsService has become very large because all the notification messages are created in it.
**Solution:** Create a new service (NotificationMessageCreatorService) that is responsible for creating notification messages, removing this responsibility from the notificationService.

Move create notifications messages to other service

---

frontend/event/event_dialog.html

**Feature/Bug description:** When trying to create an event and put the end date exactly the same as the start date, the user is unable to finish creating the event and can not change the dates.
**Solution:** In the field of dates where there is a check that checks if the event is over, I've added a new check that checks whether the event is being created or edited. If it is being created, the date can be changed, otherwise it can not.

Fix create event

---

frontend/institution/base_institution_page.html

**Feature/Bug description:** The background of the cover of an institution is light green and this does a strange visualization.
**Solution:** Adding a white background to improve visualization of PNG images.

Adding white background in institution cover photo

---

frontend/notification/notificationDirective.js

**Feature/Bug description:** The notifications without states to go does nothing when the user clicks.
**Solution:** Adding a condition to go to notifications page when the notification has no state.

Redirecting passive notifications to notifications page

---

frontend/survey/surveyDirective.js
frontend/test/specs/surveyDirectiveSpec.js

**Feature/Bug description:** When creating a survey, the author of the survey is not allowed to remove it until it leaves and enters the system again.
**Solution:** I added the permission to remove the poll on the user once the survey is created.

Fix add permission to remove survey

---

frontend/utils/messageService.js

**Feature/Bug description:** When a user tries to post a post to an institution in which they do not have permission, an untranslated message appears.
**Solution:** Translate the message and add it in the messageService.

Add error message in message service

---

backend/handlers/user_handler.py
backend/test/user_handler_test.py

**Feature/Bug description:** If you have more than one institution deleting your account, some institutions are not removed because of how it is iterating over user institutions.
For example, the user has the following array [InstA, InstB]. For in its first step remove InstA, the second step would remove InstB, however, InstB is at index 0 of the array.
**Solution:** Iterate by user's institutions at the end.

Fix delete user account

---

frontend/invites/invite_institution_hierarchie.html

There was a useless and disabled md-radio-button.
**Solution:**
Remove the button.

Remove none option from hierarchy invite's view

---

backend/search_module/search_institution.py
backend/utils.py

**Feature/Bug description:** When performing a search whose searched query has one or more '\', an error is generated on the server due to the fact that '\' is an escape character and is not being handled on the server.
**Solution:** Treat the '\' character in the server as part of the search sentence and not as an escape character, thus allowing the use of '\' in the search.

Fix search with escapes characters

---

backend/handlers/post_comment_handler.py
backend/test/post_comment_handler_test.py

There was a wrong if statement in post_comment_handler what was blocking the sending notification when the comment was sent by the post's author. This verification is done in the queue.
**Solution:**
Remove the if statement.

Fix notify posts' subscribers when there is a new comment

---

backend/handlers/event_collection_handler.py
backend/handlers/institution_followers_handler.py
backend/handlers/institution_handler.py
backend/handlers/institution_hierarchy_handler.py
backend/handlers/invite_institution_collection_handler.py
backend/handlers/invite_user_handler.py
backend/handlers/like_handler.py
backend/handlers/post_collection_handler.py
backend/handlers/post_comment_handler.py
backend/handlers/reply_comment_handler.py
backend/handlers/resend_invite_handler.py
backend/handlers/vote_handler.py
backend/models/post.py
backend/test/event_collection_handler_test.py
backend/test/institution_collection_handler_test.py
backend/test/institution_followers_handler_test.py
backend/test/invite_institution_collection_handler_test.py
backend/test/invite_user_handler_test.py
backend/test/mocks.py
backend/test/post_comment_handler_test.py
backend/test/user_timeline_handler_test.py
backend/test/vote_handler_test.py
frontend/utils/messageService.js

It was allowed to comment in a post whose institution was inactive.
**Solution:**
I've added a verification in post_comment_handler to block this flow.

Fix comment a post whose institution is not active

---

frontend/invites/invite_institution_hierarchie.html

It was missing the layout property at analyze button's div
**Solution:**
I've set the layout property.

Fix pending hierarchy invitation's analyze button

---

backend/handlers/institution_handler.py
frontend/institution/configInstDirective.js

1. The configInstDirective makes the request using $http to get the countries. The response is different from HttpService.
2. The institution_handler's get method was checking if the institution wasn't active, but some requests that are handled there  works with pending institutions.
**Solution:**
The getCountries method is now getting the correct data by doing response.data.
I've checked if the institution is inactive instead.

Fix getCountries and getInstitution

---

frontend/user/profile.html

**Feature/Bug description:** When viewing the user's institutional profile, the branch line field does not exist.
**Solution:** I added the branch line field in the user's institutional profile view.

Add branch line in institution profile

---

backend/handlers/user_handler.py
backend/test/user_handlers_tests/user_handler_test.py
frontend/notification/notificationDirective.js
frontend/notification/notificationMessageCreatorService.js

Send notification to adms when the user remove the account
**Solution:**
Call send_message_notification to each institution in user_handler's delete method.

Send notification to adms when the user remove the account

---

backend/handlers/invite_institution_handler.py
backend/test/invite_handlers_tests/invite_institution_handler_test.py
frontend/invites/inviteService.js

It wasn't possible to cancel a hierarchy's invite because the only invite that was handled was InviteInstitution.
**Solution:**
I've removed the verfication from the handler.

Fix cancel hierarchy invite

---

frontend/requests/analyse_hierarchy_request_dialog.html

The html was showing child.institutional_email where it should show child.parent_institution.institutional_email
**Solution:**
I've changed the field to show the right email.

Fix institutional_email in change parent dialog

---

frontend/requests/analyseHierarchyRequestController.js
frontend/test/specs/request/analyseHierarchyRequestControllerSpec.js

Let's say we have 3 institutions: A, B and C. B is C's parent. A wants to be C's parent and send it an invite. When C accepts the invite the link between C and B is not removed because the removeLink method is passing the wrong parameter to the backend. Instead of pass B to remove the link with C it was passing A.
**Solution:**
I've just fixed the parameters.

Fix change parent

---

frontend/institution/institutionLinksController.js
frontend/test/specs/institution/institutionLinksControllerSpec.js

The childStatus function was verifying only if the child institution has parent instead of check if the parent is the institution whose page is loaded.
**Solution:**
I've added the missing verification.

Fix link's status in institution's page

---

frontend/utils/messageService.js

The error message related to lack of permission to remove post wasn't translated in the frontend.
**Solution:**
I've inserted the message and its translation to the msg object.

Translating post error message

---

frontend/post/post_details.html

It was missing some classes to be equal to the regular post's title.
**Solution:**
I've inserted these classes.

Fix shared post's title

---

frontend/auth/authService.js
frontend/notification/notificationDirective.js
frontend/requests/requestProcessingController.js
frontend/survey/surveyDirective.js
frontend/test/specs/notification/notificationControllerSpec.js
frontend/user/user.js
frontend/user/userService.js

**Feature/Bug description:**  Refactoring the reload function used when is necessary to update user and save in cache. Before, this method created the new user. All notifications that need to be updated by the user must be described in the userService for the observer to be created, the ACCEPT_LINK notification being created observer in the AuthService.
**Solution:**  This method updates the properties of the user, so in notifications that need to refresh user call this method. Change notification to userService.

Refact function reload of auth service

---

frontend/institution/institution.js
frontend/institution/managementMembersController.js
frontend/invites/invite.js
frontend/notification/notificationService.js
frontend/requests/requestDialogService.js
frontend/test/specs/institution/institutionSpec.js
frontend/test/specs/institution/managementMembersControllerSpec.js
frontend/test/specs/invites/inviteSpec.js
frontend/test/specs/invites/newInviteControllerSpec.js
frontend/test/specs/invites/processInviteUserAdmControllerSpec.js
frontend/test/specs/request/requestDialogServiceSpec.js
frontend/utils/messageService.js
frontend/utils/message_dialog.html

**Feature/Bug description:** When the user clicks on a request notification that is related to an institution no more active, the notification dialog is shown with empty fields.
Exemple: User request
**Solution:** On RequestDialogService, in the selectDialog function, I added a verification to check if the request is valid, based on the request's institutions state. If on of the institutions is invalid, a dialog is showed to inform this to the user.
Invalid request dialog

Fix invalid request notification

---

backend/custom_exceptions/__init__.py
backend/custom_exceptions/queueException.py
backend/handlers/institution_children_request_handler.py
backend/handlers/institution_parent_request_handler.py
backend/models/request_institution_children.py
backend/test/model_test/request_institution_children_test.py
backend/test/util_modules_tests/notification_test.py
backend/test/util_modules_tests/notifications_queue_manager_test.py
backend/util/__init__.py
backend/util/notification.py
backend/util/notifications_queue_manager.py
backend/worker.py
frontend/notification/notificationDirective.js
frontend/notification/notificationMessageCreatorService.js
frontend/test/specs/notification/notificationControllerSpec.js
frontend/user/userService.js
queue.yaml

**Feature/Bug description:** In certain system actions, such as administration transfer and request to create a link with other institutions, the permissions of the users involved need to be reloaded. Many problems are happening while reloading due to the fact that as soon as notification that a given request has been accepted, the user is reloaded and sometimes there is no time for the queue to add and remove permissions to finish, ie the user is reloaded but does not yet have the permissions. This is because the queue for adding permissions works asynchronously, just like the queue of notifications, so there is currently no way to control the synchronization between the various existing services.
**Solution:** Create a different queue type from the ones that already exist on the system …

Send notification to refresh user when accept request

---

backend/handlers/invite_user_adm_handler.py
backend/models/invite_user_adm.py
backend/test/util_modules_tests/notification_test.py
backend/test/util_modules_tests/notifications_queue_manager_test.py
backend/util/notification.py
backend/util/notifications_queue_manager.py
backend/worker.py
frontend/notification/notificationMessageCreatorService.js
frontend/test/specs/notification/notificationControllerSpec.js
frontend/user/userService.js

**Feature/Bug description:** When an administrator sends an administration transfer invitation to another member of the institution and he accepts, a notification must be sent to the current administrator and another to the new administrator as soon as the administration transfer queue finishes so that the permissions can be reloaded.
**Solution:** Use notifications queue manager to create a notification that will be resolved only when the administration transfer queue is finished.

Send notification of accept transfer admin invite

---

frontend/invites/newInviteController.js
frontend/test/specs/invites/newInviteControllerSpec.js

**Feature/Bug description:** When the user accesses a new invitation page via notification, the invitation is not on the user's invitations, so as the method is implemented it cannot be redirected home.
**Solution:**  When the user chooses to respond later to the invitation by clicking the button, he is redirected home.

Fix answer later thougth notification.

---

frontend/post/postDetailsDirective.js
frontend/test/specs/post/postDetailsControllerSpec.js

**Feature/Bug description:** Fix edit post button when the institution is inactive.
**Solution:** Added verification that confirms is institution is active.

Fix show button edit

---

backend/worker.py

**Feature/Bug description:** In EmailMembersHandler, the send_mail method was being called with the property 'to' receiving a list of emails instead of a single email. 
**Solution:** It was set to send email to the first one on the list

Fix send email to institution members

---

backend/handlers/institution_children_handler.py
backend/handlers/institution_parent_handler.py
backend/models/institution.py
backend/test/model_test/institution_test.py

**Feature/Bug description:** The remove_link method of the Institution model is no longer needed because there are other methods that already do what it does.
**Solution:** Use the remove_child and set_parent methods to remove child and parent links.

Remove unnecessary method remove_link in institution model

---

backend/test/worker_handlers_tests/worker_aux_methods_test.py

There was a worker_aux_methods' test breaking locally. Filter_permissions_to_remove. The compared objects used to have unsorted lists.
**Solution:**
I've sorted the lists in the objects what made the comparison return true.

Fix worker test

---

frontend/invites/invite.js
frontend/requests/requestDialogService.js

It wasn't possible to open dialog when the notification's type was REQUEST_INSTITUTION. It was missing this type in the case inside the function that selects the dialog and the function areInstitutionsValid in invite.js was checking if the institutions were active instead of checking if the institutions weren't inactive.
**Solution:**
I've added this case in the switch case and fixed the function.

Fix can't open institution request dialog

---

frontend/requests/requestDialogService.js

**Feature/Bug description:** When trying to view the dialog processing a request_institution, it is not displayed because the request is not being passed to the controller.
**Solution:** Place the request on the locals variable in the selectDialogToShow function of the RequestDialogService so that it passes the request to the controller.

Fix show dialog to accept request institution

---

backend/worker.py

**Feature/Bug description:** When both the administrative transfer queue and the remove administrative permissions queue attempt to update the same user, the notification is sent to the user but a concurrency error occurs, and when attempting to do the operation again, the notification has already been resolved and not is in the queue, causing another error because there is no longer any way to send the notification.
**Solution:** Move the NotificationsQueueManager call out of the transaction, so if there is competition error and retry the notification queue is not affected.

Fix concurrence in the transfer admin queue and remove admin permissions queue

---

backend/handlers/invite_user_collection_handler.py
backend/test/invite_handlers_tests/invite_user_collection_handler_test.py
backend/test/worker_handlers_tests/send_invite_handler_test.py
backend/worker.py

**Feature/Bug description:** When attempting to create an invitation of type invite_user_adm, there is an error in the send-invites queue causing multiple notifications to be sent unnecessarily, this is because this queue expects that the id of a notification that is not sent, will be sent to it.
**Solution:** Make it optional to send the notification id to the send-invites queue.

Fix send invite user adm

---

frontend/event/event.html

**Feature/Bug description:** The width of event card in timeline of events are according by the size of institution name.
**Solution:** Applying the correct flexbox in design to show the cards of event correctly.

Fixing the layout of events timeline

---

frontend/post/postDirective.js
frontend/test/specs/post/postDirectiveSpec.js

**Feature/Bug description:** When click to edit a post and then click on edit, an error appears in the console with the second message: cannot read property 'title' of undefined.
**Solution:** Modify the $ mdDialog.hide() call to $ mdDialog.cancel(), so that the edit is canceled.

Fix cancel edit post

---

frontend/test/specs/event/eventDetailsControllerSpec.js

**Feature/Bug description:** When the event start date falls on the same day as the week of the end date, it is not displayed.
**Solution:** Change the way the date is checked.

Fix event data visualization

---

frontend/auth/signupDirective.js

**Feature/Bug description:** When you click request invite and fill in the password fields incorrectly, an error in the console appears, warning that the MessageService is not set.
**Solution:** Injecting the MessageService into the SignupController controller

Fix send request invite

---

frontend/institution/management_institution.css
frontend/institution/management_members.html

**Feature/Bug description:** The avatars in sub-menus of the manage members page are of different size.
**Solution:** Adding the same CSS class in the list of members to show the avatars standardized.

Fix avatar of manage members page

---

frontend/main/main.html

The app-version tag looks weird in mobiles' screens.
**Solution:**
Show it only to screens greater than 600 px.

Remove app-version from mobiles' screen

---

.gitignore
Jenkinsfile
ecis
frontend/test/package.json

**Feature/Bug description:** The bower package manager was decoupled and replaced with yarn
**Solution:** Update how to run the frontend tests so that you use yarn.

Change package manager bower to yarn

---

ecis

**Feature/Bug description:** Always when restarting the computer, it was necessary to reset the application so that it worked correctly because the database was erased.
**Solution:** Initialize the cloud datastore emulator together with the application so that the data is persisted and not deleted when the computer is restarted, providing a more similar experience with the real datastore.

Initializa cloud datastore emulator in ecis script

---

ecis

**Feature/Bug description:** When starting the system, the emulator of the datastore was being inhabited by default, which prevented that in machines where the emulator does not correctly work, the system does not start.
**Solution:** Leave the emulator application optional.

Create option to run with datastore emulator

---

frontend/notification/notifications_list.css

The icon wasn't centralized
**Solution:**
Fix the icon's classes.

Fix notification's icon

---

frontend/home/post_dialog.html
frontend/post/save_post.html
frontend/styles/custom.css

It was missing some flexs and the dialog-transparent-without-shadow class was applying some properties to all screens but it should only to small screen.
**Solution:**
Add the missing flexs and a media queria to add the properties only to the small screens.

Fix edit post dialog

---

frontend/test/specs/event/eventDialogCtrlSpec.js

Bug maybe caused by test lifecycle.
Probably `startHour` was defined when it shouldn't.
**Solution:** 
Make sure statHour is defined only when it should be.

Fix event test

---

ecis

**Feature/Bug description:** Run ecis script on mac
**Solution:** Modify usage of sed command, so it works both on linux and on mac (bsd) systems.
---
`sed` has a different implemention on unix based systems (linux) and BSD systems (mac os). While on linux it simply edits the file in-place if we don't pass a backup extension (optional), on BSD it expects it as a *mandatory* argument.
(`sed -i .bak ...` for instance)
In order to have a portable solution (and also one where we dont end up with several backup files cluterring the repository), we write sed output to a temp file, and then replace our original file with said temp file.
Linux sed:
```
-i[SUFFIX], --in-place[=SUFFIX]
edit files in place (makes backup if extension supplied). The default operation mode is to break symbolic and hard …
```

Add compatible ecis script

---

frontend/sideMenu/factories/homeItems.factory.js

**Feature/Bug description:** On the home page, when the user changes the current institution and clicks on one of the management institution options, the corresponding management page is loaded with the key of the previous institution. That was occurring because the HomeItemsFactory was using a constant to save the current institution key, so when the user changes its current institution this value is not updated. Hence, the functions that redirect to the institution management page were using the previous institution key.
**Solution:** It was created a function to return the current institution key;

Fix bug on management institution options

---

frontend/main/mainController.js
frontend/test/specs/event/eventDialogCtrlSpec.js
frontend/test/specs/main/mainControllerSpec.js

fixes #1401 
The page was being reloaded when a new link was established
**Solution:**
Remove some unnecessary reloads, like $state.reload(), that was at mainCtrl.refreshUser.

Fix page reload when a new link is established

---

frontend/home/home.html
frontend/main/main.css
frontend/styles/custom.css

**Feature/Bug description:** Right side panel looked squeezed on high res desktops:
Round buttons would be also squeezed on first load, increasing in size after being hovered on:
Feedback button got on top of clickable elements:
**Solution:** 
* Increase right side panel width and decrease content width
* Remove margin on institutions round buttons
* Move feedback button

Fix right side panel on high res screens

---

frontend/styles/custom.css

**Feature/Bug description:** On firefox, the scrollbar is not defined as in other browsers, therefore, the custom ecis scrollbar does not render the way it should be.
**Solution:** Add firefox scrollbar definition.

Fix scrollbar on firefox to have ecis colors and thin width

---

frontend/imageUpload/crop_image.css
frontend/imageUpload/crop_image.html
frontend/index.html
frontend/styles/custom.css

**Feature/Bug description:** Change image crop dialog to match design spec
**Solution:** 
* Use css grid to structure the dialog in crop_image.html
* Remove cropArea from custom.css
* Add a new crop_image.css

Change image crop dialog to match design spec

---

frontend/sideMenu/factories/homeItems.factory.js

**Feature/Bug description:** Missing support redirection in mobile.
**Solution:** Add 'Reportar problemas' item to homeItems factory.
- Design:
- Before:
- After:

Add 'Reportar problemas' sidenav item

---

ecis

**Feature/Bug description:** Current `sed` command on ecis script is compatible with macOS
**Solution:** Change command to work on both linux and macOS

Update ecis script to use mac compatible sed usage

---

frontend/home/home.html

Fixes #1434 
Add button on mobile timeline page has wrong green color.
**Solution:** 
change the color to 'light-green-600'
**TODO/FIXME:** 
Some others green colors are not the same.

changed add button collor on timeline

---

frontend/auth/authService.js
frontend/home/homeController.js
frontend/test/specs/home/homeControllerSpec.js

The Push notification permission was being asked after the user login and blocked the home page to load until the user answer the dialog permission.
But the client chose to allow home page to load. What means that, The push notification permission will be asked on home page after first login.
**Solution:** 
Removed the function that asks the  permission from AuthService to HomeCtrl.

Modified when push notification permission is asked
