- app/controllers.js
- app/home.html
Criação de posts na timeline. Apenas lógica de view.
> Create post (only view)

- main.py
- utils.py
Conversão das keys retornadas pela api em url's que podem ser acessadas diretamente, retornando o json da entidade relacionada com a key.
> Add api key resolve as url

- admin.py
- app/auth/authService.js
- app/home/home.html
- app/home/homeController.js
- app/main/main.html
Left toolbar in the main page to select institution.
> Add toolbar for selection of institution

- utils.py
O usuário pode logar apenas com a conta do google, com isso o sistema irá criar um usuário com nome sendo o nickname, e por default sendo membro e seguindo splab.
> Logging without user created by admin.py

- handlers/post_handler.py
> fixed posthandler merge

- .travis.yml
- util/json_patch_test.py
Configuração do Travis CI para utilizar o SDK do app engine.
> Add travis integration with Travis CI

- admin.py
- app/app.js
- app/home/home.html
- app/home/homeController.js
- app/index.html
- app/institution/institutionController.js
- app/institution/institutionService.js
- app/institution/institution_page.html
- app/main/mainController.js
- handlers/institution_follower_handler.py
- handlers/institution_followers_handler.py
- handlers/institution_members_handler.py
- handlers/institution_timeline_handler.py
- main.py
> Inst page details

- admin.py
> created function to add comments to posts

- app/institution/institutionService.js
- handlers/institution_followers_handler.py
- main.py
method delete in InstitutionFollowersHandler to remove one follower #85
> Method delete in Institution Followers Handler

- app/home/homeController.js
- app/institution/institutionController.js
- app/institution/institution_page.html
unfollow button in INstitution page #87
> Button unfollow in institution page

- app/institution/institutionController.js
unfollow button in INstitution page #87
> update followers in institution page

- app/auth/user.js
- app/home/homeController.js
- app/institution/institutionController.js
- models/institution.py
- models/user.py
> User can't unfollow his intitutions

- app/app.js
- app/comment/commentService.js
- app/home/home.html
- app/home/homeController.js
- app/index.html
> Comments client side

- app/home/home.html
- app/home/homeController.js
- app/index.html
- app/institution/institution_page.html
- app/post/postDetailsDirective.js
- app/post/postDirective.js
- app/post/post_details.html
> Post details directive

- test/post_collection_handler_test.py
- test/post_handler_test.py
- test/test_base_handler.py
> Test of post collection handler

- test/follower_institution_test.py
- test/followers_institution_test.py
> Test followers handler

- app/post/postDetailsDirective.js
- app/post/postService.js
- app/post/post_details.html
- handlers/like_post_handler.py
- handlers/post_handler.py
- main.py
- models/post.py
- models/user.py
- test/like_post_handler_test.py
- test/post_handler_test.py
> finishing the like and tests

- app/post/post_details.html
> Bug go to institution resolved

- app/home/home.html
- app/home/homeController.js
- app/post/postDetailsDirective.js
- app/post/post_details.html
- handlers/post_comment_handler.py
- models/post.py
- utils.py
> Delete comment client-side

- models/post.py
- test/like_post_handler_test.py
> changed the make method from Like object

- app/post/postDetailsDirective.js
- app/post/post_details.html
- models/post.py
> Show number comments post

- app/post/post_details.html
> Change post position buttons + remove unused menu buttom

- app/post/postDetailsDirective.js
> Fix empty comment bug

- app/custom.css
- app/post/post_details.html
> Hyperlink to institution

- app/post/new_post.html
- app/post/post_details.html
> Fix the maximum size of the post and removing the button of time

- admin.py
- app/institution/institution_page.html
- utils.py
> Fixing: adding the user's name on the picture

- app/post/postDetailsDirective.js
- app/post/post_details.html
> Fixing the comment's number bug

- app/post/postDetailsDirective.js
- app/post/post_details.html
- handlers/like_post_handler.py
- test/like_post_handler_test.py
> Bug Numbers of Like

- admin.py
- app/comment/commentService.js
- app/post/postDetailsDirective.js
- app/post/post_details.html
- models/post.py
- test/post_comment_handler_test.py
> Display institution name on comments

- admin.py
- app/custom.css
- app/post/postDetailsDirective.js
- app/post/post_details.html
- handlers/institution_timeline_handler.py
- handlers/post_handler.py
- handlers/user_timeline_handler.py
- models/post.py
- test/institution_timeline_handler_test.py
- test/user_timeline_handler_test.py
- utils.py
> Refactored the process to delete post

- app/app.js
- app/error/user_inactive.html
- app/main/mainController.js
- app/test/specs/mainControllerSpec.js
View for users without institutions and invites #190
> Created path to inactive user page

- handlers/institution_timeline_handler.py
- handlers/user_timeline_handler.py
- test/institution_timeline_handler_test.py
- test/user_timeline_handler_test.py
> Timeline ordered by last modified

- models/institution.py
- models/invite.py
- test/invite_collection_handler_test.py
Invite parent institution after institution signup #209
> Create stub for Parent Institution

- index.yaml
Fix index.yaml to be consistent with ordering posts by last modified date
> Fix index.yaml 

- app/auth/authService.js
- app/auth/configProfileController.js
- app/auth/login.html
- app/auth/loginController.js
- app/index.html
- app/main/main.html
- app/main/mainController.js
- app/test/specs/configProfileControllerSpec.js
- app/test/specs/loginControllerSpec.js
- app/test/specs/mainControllerSpec.js
- app/test/specs/messageServiceSpec.js
- app/utils/messageService.js
- handlers/base_handler.py
- utils.py
Redesign login page
Create user account with email and password via Firebase authentication
Signin with email and password
MessageService to handle displayed messages to the user
> Firebase user signup and signin with email and password

- app/test/specs/loginControllerSpec.js
Remove focus on loginControllerSpec
> Fix login controller test

- .jshintrc
- app/auth/user.js
- app/main/main.html
- app/main/mainController.js
- app/test/specs/mainControllerSpec.js
- app/test/specs/userSpec.js
When moving between routes the current institution was changing to default.
> Fix current institution when changing routes

- app/invites/invite_institution.html
- app/invites/invite_institution_hierarchie.html
The invitations were coming out of the card in invite_institution.html and invite_institution_hierarchie.html. Now, after adding a <md-item> before the <md-card>, the invitations fits correctly in the card.
> Fix invites content floating over the card element

- ecis-firebase-identity.json
- setup_google_credential.sh
Json file generated was malformed, causing server error.
> Fix malformed json generated by the setup google identity script

- app/invites/inviteInstitutionController.js
- app/invites/invite_institution.html
Before this change the invite page showed only sent invitations, after changes the page show the sent and accepted invites
> showing accepted invites in invite_page

- utils.py
New google api certificates was add to the list. I changed the way that exception is handled on the verification token.
> Fix new google api certificates

- app/notification/notificationDirective.js
- app/notification/notifications.html
When a comment notification is clicked, the user is redirected to the post's page.
> Go to the post page when click a comment notification

- app/app.js
- app/error/error.html
- app/error/errorController.js
- app/home/homeController.js
- app/notification/notificationDirective.js
- app/notification/notifications.html
- app/post/postPageController.js
- handlers/base_handler.py
- utils.py
New notifications layout, displaying different icon to each type, also, timestamp appears under the notification text.
This PR change the errors layout page (same as user inactive layout) and handles status 500 changing the client state to error page.
> New notifications layout and Client handling errors properly

- app/home/home.html
- app/home/homeController.js
- app/home/post_dialog.html
- app/post/postDirective.js
- app/post/timeline.html
- app/test/specs/postDirectiveSpec.js
When a new post is created the timeline wasn't refreshed to get that new post. The solution was to pass to the create-post directive, the list of post, from HomeController.
> Fix new post addition to timeline

- app/notification/notificationService.js
- app/notification/notifications.html
Notifications wasn't ordered reverse. The solution was change to use push() method on the list and use the orderBy function of angular ng-repeat directive.
> Fix reverse order of notifications directive

- models/invite.py
Send notifications of invite, only when the client part of invite be done.
> Block send notifications of invite.

- app/auth/authService.js
- app/notification/notificationService.js
Fix notification watch when user perform a consecutive logout and login.
> Create authService event listener to thrigger functions when logout is called

- app/home/home.html
- app/institution/institution_page.html
The layout of institution page was unresponsive when the page height was less then 600px
> Fix strange behavior of left site cards on institution page

- admin.py
- app/institution/institutionService.js
- app/main/main.html
- app/test/specs/institutionServiceSpec.js
- app/test/specs/inviteInsHierarchieSpec.js
- app/test/specs/inviteInstitutionControllerSpec.js
- app/test/specs/mainControllerSpec.js
- app/test/specs/requestInvitationControllerSpec.js
- handlers/institution_handler.py
- handlers/search_handler.py
- models/institution.py
- search_module.py
- test/search_handler_test.py
This feature allows to search for an institution by its acronym.
> Search institution by its acronym

- app/auth/configProfileController.js
- app/auth/config_profile.html
- app/test/specs/configProfileControllerSpec.js
- app/test/specs/homeControllerSpec.js
I added the image cropping function on the user settings page.
> Crop image in config profile controller

- app/institution/institutionController.js
- app/institution/removeInstDialog.html
- app/test/specs/userSpec.js
- app/user/user.js
- handlers/user_handler.py
- models/institution.py
The institution is removed from user's cache.
> Fix remove institution

- app/post/post.js
- app/post/postDetailsDirective.js
- app/post/post_details.html
- app/test/specs/postDetailsControllerSpec.js
- handlers/post_collection_handler.py
- handlers/user_timeline_handler.py
- models/institution.py
- models/post.py
- test/institution_timeline_handler_test.py
- test/post_handler_test.py
- test/user_timeline_handler_test.py
If the post has no comments or likes it is deleted permanently from the database.
> Delete post with no activity

- util/json_patch.py
- util/json_patch_test.py
* I added verification if entity passed if dict in method create_entity
* I added verification if entity passed if dict in method go_through_path
* I added verification if entity passed if dict in method operations add, remove, replace
> Refactoring json patch

- app/app.js
- app/auth/configProfileController.js
- app/auth/config_profile.html
- app/invites/newInviteController.js
- app/invites/new_invite_page.html
- app/test/specs/configProfileControllerSpec.js
- app/test/specs/editProfileControllerSpec.js
- app/user/edit_profile.html
- app/user/profileService.js
- app/user/userService.js
- util/json_patch.py
I've added a button in config_profile_html for each institution that allows the user edit the profile relative to that institution.
This button opens a dialog that is controlled by EditProfileController, a function that belongs to ConfigProfileController.
There was no need to work in backend, once what I needed there was the user_handler's patch method.
> Edit user profile

- app/notification/notificationDirective.js
- app/notification/notificationService.js
- handlers/like_handler.py
* I added function of send notifications in like_handler
* I added new types of notifications in notification directive and notification service
> Add function of send notification of like post and comments

- handlers/event_handler.py
- models/event.py
- test/event_handler_test.py
* I added method __setattr__ in event model for set attributes
* I removed method treats_date of event_handler
> Refactoring model event

- admin.py
- handlers/institution_request_collection_handler.py
- handlers/institution_request_handler.py
- main.py
- models/factory_invites.py
- models/institution.py
- models/request.py
- models/request_institution.py
- models/request_institution_children.py
- models/request_institution_parent.py
- test/institution_request_collection_handler_test.py
- test/institution_request_handler_test.py
- utils.py
* I added __RequestInstitution__ model.
* I added __RequestInstitutionCollectionHandler__.
* I added __RequestInstitutionHandler__.
> Request institution

- app/institution/institution.js
- app/institution/institutionController.js
- app/invites/newInviteController.js
- app/invites/new_invite_page.html
- app/requests/requestInvitationController.js
- app/requests/requestProcessingController.js
- app/requests/request_invitation_dialog.html
- app/requests/request_processing.html
- models/institution.py
- test/model_test/request_institution_test.py
- test/model_test/request_user_test.py
**Cause**: It occurs because the function getFullAddress is not being used in some controllers.
**Effect**: On this controllers, the address was being shown in json format.
**Solution**: Moved the function getFullAddress to the institution model and called it where is needed.
> BUG institution address presentation

- app/app.js
- app/auth/login.html
- app/auth/loginController.js
**Bug**:  After logging with google a inactive user was able to navigate through the system pages, not redirecting to inactive user page.
**Solution**:  Add a response interceptor to catch the user state and redirect to the right page, inactive user page or request page when having a pending request.
> Fix intercept exceptions routes after login

- app/institution/institutionService.js
- app/invites/newInviteController.js
- app/invites/new_invite_page.html
- handlers/institution_handler.py
- models/user.py
- test/institution_handler_test.py
When the user recieves one invite to be admin for institution, if the user has not name, he send your name to be updated and create your profile.
> Bug createprofile when create new institutions

- app/post/post.js
- app/post/postDetailsDirective.js
- app/post/post_details.html
- app/post/share_post_dialog.html
- app/test/specs/postDetailsControllerSpec.js
- app/test/specs/postSpec.js
- app/test/specs/sharePostControllerSpec.js
**Cause**: There was not a frame to embed the video on the shared post neither on the share post dialog.
**Solution**: It was added this frame to the templates and the related code in controllers were refactored.
> Bug on showing video on shared post and on share post dialog

- app/invites/newInviteController.js
- app/invites/new_invite_page.html
- app/post/post_details.html
**Bug**: Image is shown in a small size on shared post
**Solution**: removed the img tag from a div with class image-view and added a style to max width and auto height
> Bug showing image on shared post

- app/invites/existing_institutions.html
- app/invites/invite_institution_hierarchie.html
- app/invites/suggestInstitutionController.js
- app/notification/notificationDirective.js
- app/post/save_post.html
- app/requests/requestProcessingController.js
New verification added in send requests to institution parent or children and adjusted buttons on view
> Improving modal inst requests

- app/invites/inviteInstHierarchieController.js
- handlers/request_handler.py
- models/request_institution_children.py
- models/request_institution_parent.py
- models/request_user.py
- test/request_handler_test.py
I've fixed the notification receiver.
It's missing the refactoring of CheckIsAdmin method.
> Fix bug send connection notification

- app/invites/existing_institutions.html
- app/invites/suggestInstitutionController.js
Changing message in modal and button to open institution page
> changing modal message and button

- app/invites/newInviteController.js
- app/test/specs/newInviteControllerSpec.js
- handlers/institution_handler.py
Before this change, edit profile not work when the institution is new. Now user can edit profile in this case.
> fixing bug in edit profile when the institution is new

- app/invites/invite_institution_hierarchie.html
- app/main/mainController.js
- app/requests/requestInvitationService.js
- handlers/invite_collection_handler.py
Fix wrong endpoint to get pending institution requests.
> Fix get institution pending requests

- app/requests/requestInvitationController.js
- app/requests/request_invitation_dialog.html
<p><b>Feature/Bug description:</b> 
The layout of request user invitation dialog wasn't following the material design patterns.</p>
Redesign the entire flow of the view and components.
</p>
> Refact layout of request user invitation dialog

- admin.py
<p><b>Feature/Bug description:</b> Admin wasn't be able to login in with email/password provider</p>
<p><b>Solution:</b> Added an alternative email to the list of admin emails</p>
> Added an alternative email to the list of admin emails

- app/home/home.html
- app/institution/institutionController.js
- app/institution/institution_page.html
- app/post/postDetailsDirective.js
- app/post/timeline.html
- app/post/timelineDirective.js
- app/test/specs/sharePostControllerSpec.js
Bug description: When share post in page institution, the shared post is added in timeline of institution even if institution's page not be institution author of post.
Solution: Verify if user is in page institution
> Fix share post in institution page

- app/event/event.html
- app/event/eventController.js
- app/home/home.html
- app/post/postDetailsDirective.js
- app/post/post_details.html
- app/post/share_post_dialog.html
- app/test/specs/eventControllerSpec.js
- app/test/specs/sharePostControllerSpec.js
- handlers/event_collection_handler.py
- models/event.py
- test/event_collection_handler_test.py
- test/event_handler_test.py
- test/post_collection_handler_test.py
**Bug description:** Share post when this is sharing of event
**Solution:** Pass event to controller ShareController and create a new post with the event.
> Share event post

- app/event/event.html
- app/home/home.html
- handlers/event_collection_handler.py
<p><b>Feature/Bug description:</b> After use Make in method get in event_collection_handler, author_name was changed by author and any places don't show name of author event</p>
<p><b>Solution:</b> Changed author_name by author in home.html and event.html</p>
> Fix wrong event property author_name instead of author

- app/requests/requestInvitationController.js
- app/requests/request_invitation_dialog.html
- app/styles/custom.css
- app/user/user_inactive.html
<p><b>Feature/Bug description:</b> Before create institution the user should confirm that can create.</p>
<p><b>Solution:</b> Added checkbox that user affirms that can create institution. </p>
> Confirm authorization user for create institution

- frontend/app.js
<p><b>Feature/Bug description:</b> Bug in state transition when the user is inactive nd has a new invitation</p>
<p><b>Solution:</b> Add route new_invite in ignored_routes list on function run of app.js</p>
> Fix state transition for inactive user

- backend/models/institution.py
- frontend/institution/configInstDirective.js
<p><b>Feature/Bug description:</b> When you create a new institution, your image is broken.</p>
<p><b>Solution:</b> Repair image path.</p>
> Fix image url in configInstDirective

- landing/cisdetails.html
- landing/coming_soon.html
- landing/ecisdetails.html
- landing/home.html
- landing/landing.js
- landing/main.html
- landing/privacy.html
- landing/support_institutions.html
- landing/terms.html
<p><b>Feature/Bug description:</b> Creation of static pages for landing page</p>
<p><b>Solution:</b>Creation of static pages : support institutions, terms of use, e-CIS details and  CIS details</p>
> Static pages

- backend/handlers/institution_handler.py
- backend/handlers/invite_handler.py
- backend/models/institution.py
- backend/models/invite.py
- frontend/invites/newInviteController.js
<p><b>Feature/Bug description:</b> When user is invited to be admin of an institution, if the user accept or reject the invite, the notification sent to sender of invite is displayed with Unknown name.</p>
<p><b>Solution:</b> In case of reject invite, the user state is inactive therefore the name displayed in the notification is the user email. In case of acceptance, the correct name is displayed.</p>
> fix bug user with unknown name in notification

- frontend/institution/management_institution_page.html
Ng-click was with the wrong method. 
</p>
I've changed the method to goToInstitution in ng-click.
</p>
> Fixing the ng-click in management_institution_page.html

- frontend/post/comment.html
<p><b>Feature/Bug description:</b> Font size of reply comment incorrect.</p>
<p><b>Solution:</b> I changed font size.</p>
<p><b>TODO/FIXME:</b> I changed the size using style, change that in the future.</p>
> Fix font size of reply input

- backend/handlers/institution_hierarchy_handler.py
- frontend/invites/inviteInstHierarchieController.js
- frontend/invites/invite_institution_hierarchie.html
The delete method was missing @json_response decorator.
The user was redirected to the home when the link was removed.
</p>
I've added the json_response decorator.
Now the link is removed from the controller.
</p>
> Fixing removeLink

- frontend/institution/occupation_area.json
Some occupation areas has been added
</p>
I've added the new occupation areas in occupation_area.json
</p>
> Adding some occupation areas

- backend/search_module.py
The query string was wrong
</p>
I've added another condition to the query string
</p>
> Editing query string in search_module

- backend/worker.py
The http's post method in worker.py was missing @json_response 
</p>
I've added the decorator @json_response. 
</p>
> Adding json_response

- frontend/institution/institution.js
The cnpj was in isValid method.
</p>
I've removed this.cnpj from isValid.
</p>
> Removing cnpj from isValid

- ecis
<p><b>Feature/Bug description:</b> The deployment of the system is entirely manual, being to difficult to organize all configuration before send the files.</p>
<p><b>Solution:</b> Automate the deployment with a bash script, that configure and execute the commands to deploy to the remote server.</p>
**Sintaxe**
- ./ecis deploy 
- Deploy to a promoted version
- ./ecis deploy version_name
- Deploy to a specific version
> Automatic deploy with bash script

- frontend/institution/management_members.html
Fixing the view of the member email in management members' page.
</p>
I've removed md-subheader class.
</p>
> Removing subheader from member.email

- frontend/invites/inviteInstHierarchieController.js
- frontend/invites/invite_institution_hierarchie.html
<p><b>Feature/Bug description:</b> On institution link management, the suggested institution name was not being shown right after the request has been sent</p>
<p><b>Solution:</b> It was created a function to get the suggested name from the institution invite when it exists, otherwise, it is returned the institution name</p>
> Bug on showing suggested institution name

- backend/handlers/institution_children_request_handler.py
- backend/handlers/institution_parent_request_handler.py
<p><b>Feature/Bug description:</b> It was happening a CORS error when an institution request was rejected. </p>
<p><b>Solution:</b> It was added the json_response decorator to delete method in both institution parent and institution children request handlers </p>
> BUG on reject institution request

- frontend/test/specs/profileControllerSpec.js
- frontend/user/profile.html
- frontend/user/profileService.js
<p><b>Feature/Bug description:</b> In profile dialog not has button to go to account settings.</p>
<p><b>Solution:</b> Added a button to go to account settings when the profile dialog is own of user.</p>
> adding button in profile to go to settings

- backend/handlers/post_collection_handler.py
- backend/models/post.py
- backend/models/survey_post.py
- backend/test/event_handler_test.py
- backend/test/model_test/survey_post_test.py
<p><b>Feature/Bug description:</b> Model of survey post in backend.</p>
<p><b>Solution:</b> The entity is heritage of model Post with addition some attributes like 'options' and 'deadline'.</p>
<p><b>TODO/FIXME:</b> Model of option
{'text' : 'text',
'number_votes' : 0,
'voters' : []}</p>
> Survey post model server

- backend/handlers/request_handler.py
- backend/models/request_user.py
- backend/test/request_handler_test.py
- frontend/institution/institutionController.js
- frontend/institution/institution_page.html
- frontend/notification/notificationDirective.js
- frontend/notification/notificationService.js
- frontend/requests/requestInvitationController.js
- frontend/requests/request_invitation_dialog.html
- frontend/requests/request_processing.html
- frontend/test/specs/institutionControllerSpec.js
An active user can now request to be a member of any institution, as long as he is not yet one.
</p>
I've opened request_invitation_dialog from institution controller, where the button that requests the link is, and I've used the same controller, requestInvitationController. For this, I've made some changes in the html and in the controller's logic, mainly in its initialization. When the request is accepted a notification is sent to the request's sender, warning him and allowing to refresh his institutions.
</p>
> Request to be a member

- backend/test/institution_followers_handler_test.py
Adding tests to InstitutionFollowersHandler
</p>
I've created a test's file and there I've wrapped some unittests
</p>
> Testing institutionFollowersHandler

- backend/test/model_test/event_test.py
The event model didn't have tests.
</p>
I've created a file of unit tests for event. 
</p>
> Testing event model

- backend/utils.py
There were some useless functions in utils.py
</p>
I've removed it.
</p>
> Removing useless functions from utils.py

- frontend/config.js
- frontend/institution/institutionService.js
- frontend/post/postService.js
- frontend/test/specs/homeControllerSpec.js
- frontend/test/specs/institutionControllerSpec.js
<p><b>Feature/Bug description:</b> Query params were being passed incorrectly separated by two &&</p>
<p><b>Solution:</b> Remove a &</p>
> Fix timeline url

- .gitignore
- frontend/config.js
<p><b>Feature/Bug description:</b> The main script was changing the backend url on the frontend, causing erros when running the system</p>
<p><b>Solution:</b> Modify to the correct url and configurate git to untrack changes on that file.</p>
> Fix wrong backend URL on frontend config

- backend/models/invite.py
- backend/models/invite_institution.py
- backend/models/invite_institution_children.py
- backend/models/invite_institution_parent.py
- backend/models/invite_user.py
- backend/test/model_test/invite_institution_test.py
- backend/test/model_test/invite_test.py
- backend/test/model_test/invite_user_test.py
Created tests for Invite, invite_intitution and invite_user models.
> Tests for invite model

- frontend/home/homeController.js
<p><b>Feature/Bug description:</b> Events were not showing up on the home page.</p>
<p><b>Solution:</b> Adjust how events are received from the backend.</p>
> Fix visualization of events in home page

- landing/home.html
- landing/support_institutions.html
<p><b>Feature/Bug description:</b>New texts about functionalities and support institutions to be update.</p>
<p><b>Solution:</b> The old text has been replaced</p>
> Update texts of landing page

- frontend/search/search.html
- frontend/search/searchController.js
- frontend/test/specs/searchControllerSpec.js
<p><b>Feature/Bug description:</b> When search page is opened, the function "getOccupationArea" cause an error because the name of json archive is now "actuation_area".</p>
<p><b>Solution:</b> Changing the name of archive occupation_area to actuation_area in function and changing the variable name "occupation" to "actuation" in controller and html to improve the coherence.</p>
> fixing bug in get occupation areas

- ecis
- landing/home.html
<p><b>Feature/Bug description:</b> The span tag was written as spanv, causing strange effect in the page.</p>
<p><b>Solution:</b> Correct the tag name to span.</p>
> Fix landing page tag

- backend/handlers/event_collection_handler.py
- backend/models/event.py
- backend/test/event_collection_handler_test.py
- backend/test/invite_collection_handler_test.py
- backend/test/model_test/event_test.py
<p><b>Feature/Bug description:</b> Fix test of event_collection_handler_test.py and invite_collection_handler.py</p>
I verified that the error messages were passed correctly.</p>
> Check error requests in backend handlers test

- backend/test/post_collection_handler_test.py
- backend/utils.py
<p><b>Feature/Bug description:</b> Tests that expected an exception to be thrown were not verifying that the exception thrown was expected.</p>
<p><b>Solution:</b> I added checks for the thrown exceptions to see if they match  expected.</p>
> Fix tests of post collection handler test

- frontend/post/post_details.html
<p><b>Feature/Bug description:</b> Creates a new layout for removed posts.</p>
<p><b>Solution:</b> Using layout guidelines from angular material I created the layout of removed posts.</p>
> Create a new layout of deleted post

- frontend/post/post_details.html
- frontend/styles/custom.css
Editing post's buttons layout.
</p>
I've changed the post_details html and added some css.
</p>
> New layout of post buttons

- frontend/event/eventController.js
- frontend/utils/messageService.js
<p><b>Feature/Bug description:</b> When creating a new event, if the start date equals the end date, the backend throws an exception and the frontend view breaks.</p>
<p><b>Solution:</b> Handle the error thrown from the backend in the event Dialog Controller.</p>
> Fix bug of create new event

- frontend/user/user.js
<p><b>Feature/Bug description:</b>Bug when new users are created, because they doesn't have institutions yet</p>
<p><b>Solution:</b> The correct verification is check the length of institutions array</p>
> Verify if user has institutions

- frontend/institution/edit_info.html
- frontend/institution/management_institution_page.html
- frontend/institution/management_members.html
<p><b>Feature/Bug description:</b>New layout for management institutions page, left side menu</p>
<p><b>Solution:</b> Implementation of left side menu on institutionn management page</p>
> Left sidebar on management institution page

- frontend/auth/authService.js
- frontend/post/save_post.html
<p><b>Feature/Bug description:</b> When the user browser section reached 1hour the system was login out and redirection to the sign in page. That problem happens because the auth module wasn't refreshing the token when the user used the system.</p>
<p><b>Solution:</b> Create a function that fires an async task that gets a refreshed token and set to the user stored in the browser cache.</p>
<p><b>TODO/FIXME:</b> It needs to be tested using the system.</p>
> User refresh token

- frontend/auth/authService.js
<p><b>Feature/Bug description:</b> Email verification with firebase. Once the user creates it's account an email is sent to him with a link to verify his account.</p>
<p><b>Solution:</b> Used the firebase native function to send the verification email.</p>
<p><b>TODO/FIXME:</b> This verification breaks the test fake login.</p>
> Verify user email with firebase

- frontend/auth/authService.js
- frontend/auth/login.html
- frontend/auth/loginController.js
- frontend/index.html
<p><b>Feature/Bug description:</b> This feature allows the user to create a new password through an email sent by the system.</p>
<p><b>Solution:</b> Used a function from Angular Fire framework that receives the user email and sends a message with a link to recover the password.</p>
> Reset user password

- frontend/post/post_details.html
<p><b>Feature/Bug description:</b> All posts can be edited by any users and the message of delete button appears in all posts.</p>
<p><b>Solution:</b> Changing permission to edit post to only the author and removing exhibition of message in delete button when the user not have permission to delete.</p>
> changing permission to edit posts and the display of delete button

- frontend/survey/save_survey.html
- frontend/survey/surveyDirective.js
<p><b>Feature/Bug description:</b> Bug when create survey post, type_survey wasn't filled.</p>
<p><b>Solution:</b> Added method getTypeSurvey when create Survey</p>
> Fix choice type_survey

- backend/handlers/invite_handler.py
- frontend/institution/managementMembersController.js
- frontend/institution/management_members.html
- frontend/invites/newInviteController.js
- frontend/invites/new_invite_page.html
- frontend/test/specs/managementMembersControllerSpec.js
<p><b>Feature/Bug description:</b> When the user accept a membership invitation the profile color doesn't change correctly.</p>
<p><b>Solution:</b> When the user accepts a membership invitation the user is retrieved through the invitation API that didn't have the institution profiles.</p>
> Fix profile color after accept membership invitation

- frontend/post/postDirective.js
<p><b>Feature/Bug description:</b> When a pdf is attached to the post creation form, nothing was happening.</p>
<p><b>Solution:</b> The problem was a wrong verification that blocked the addition of the file to the controller.</p>
> Fix post when try to attach PDF

- frontend/app.js
- frontend/auth/loginController.js
<p><b>Feature/Bug description:</b> When the user tries to access an URL that needs authentication the system redirects to the Sign In page and lost the original path.</p>
<p><b>Solution:</b> Using the $location feature from AngularJS it was possible to get the original path that the user tried to access. With that, it's possible to store the information during the login and proceed to the path after finish the authentication process.</p>
> Redirect to correct URL after login

- frontend/institution/management_members.html
- frontend/invites/inviteInstitutionController.js
- frontend/invites/invite_institution.html
- frontend/test/specs/inviteInstitutionControllerSpec.js
<p><b>Feature/Bug description:</b>New layout with cards to institutional invites </p>
<p><b>Solution:</b> 4 cards are crated</p>
<p><b>TODO/FIXME:</b> Insert the left menu of user on this page</p>
> New layout for institutional invites from super users

- frontend/user/user_inactive.html
<p><b>Feature/Bug description:</b> Create a new layout for user inactive page.</p>
<p><b>Solution:</b> Using the angular directives I created the new layout according to what was passed by the design.</p>
> New layout of user inactive page

- frontend/institution/institution_page.html
- frontend/institution/management_members.html
- frontend/styles/custom.css
<p><b>Feature/Bug description:</b>Md-list-item's css was overwritten in custom.css</p>
I've removed the overwritten and wrapping the code into md-list-item-low-height class.
</p>
> Removing the overwrite of md-list-item's css

- frontend/invites/inviteInstHierarchieController.js
- frontend/invites/invite_institution_hierarchie.html
<p><b>Feature/Bug description:</b> Create a new layout for invite intitution hierarchie page.</p>
<p><b>Solution:</b> Using the angular directives I created the new layout according to what was passed by the design.</p>
> New layout of invite institution hierarchie

- frontend/requests/request_invitation_dialog.html
<p><b>Feature/Bug description:</b> Fields of the user request form were not being checked before submitting the request.</p>
<p><b>Solution:</b> Add the ng-submit directive in the form so that it checks the fields before submitting the request.</p>
> Fix bug of send request user

- frontend/app.js
- frontend/auth/loginController.js
- frontend/index.html
- frontend/libs/angular-ui-router.js
<p><b>Feature/Bug description:</b> When the user tried to log in with an inactive user then logged out and logged in with an active user, the system was prompting the user inactive page.</p>
<p><b>Solution:</b> Refact the transitions listeners on app.js to provide a better modular implementation, separating the listeners of the inactive user, invitations, and authentication. In addition, removed transitions made by the angular bearer interceptor to prevent ui-router transitions superseded.</p>
> Fix wrong redirect after user inactive login

- frontend/auth/configProfileController.js
- frontend/auth/config_profile.html
<p><b>Feature/Bug description:</b> The config_profile page are out of sync with the new patterns of front-end.</p>
<p><b>Solution:</b> Changing layout, colors, buttons and toolbars to the new design patterns.</p>
> changing the config_profile page to new patterns of front-end

- frontend/institution/institution_page.html
<p><b>Feature/Bug description:</b> In institution members the profile of member is not displayed when the user click.</p>
<p><b>Solution:</b> Added action to show member profile when the user click in picture or name of member.</p>
> Showing member profile of institution

- frontend/home/home.html
- frontend/home/homeController.js
- frontend/post/timeline.html
- frontend/post/timelineDirective.js
- frontend/styles/custom.css
<p><b>Feature/Bug description:</b> Reload button the posts was rolling along with the page.</p>
<p><b>Solution:</b> I moved the timeline button to the home page.</p>
> Move refresh timeline button

- backend/handlers/user_handler.py
- frontend/home/home.html
<p><b>Feature description:</b> Now, the institutions are shown on a image grid </p>
> changed following institutions view from list to grid

- backend/admin.py
The permission was wrong.
</p>
I've fixed the permission.
</p>
> Fix survey permission in admin.py

- frontend/auth/configProfileController.js
- frontend/home/color_picker.html
- frontend/home/colors.json
- frontend/home/home.html
- frontend/home/homeController.js
- frontend/post/save_post.html
- frontend/test/specs/homeControllerSpec.js
- frontend/utils/utils.js
<p><b>Feature/Bug description:</b> Color picker to customize the institution colors</p>
<p><b>Solution:</b> Create a picker on home that changes the color of user current institution</p>
> Color picker to institution profile

- frontend/post/postPageController.js
- frontend/post/post_page.html
<p><b>Feature/Bug description:</b> When a post is deleted and has no comment the post view page is empty.</p>
<p><b>Solution:</b> Add a text to be displayed when the post is deleted and does not contain any comments.</p>
> Fix visualization of deleted post in post page

- backend/models/request.py
- backend/models/request_user.py
- frontend/requests/requestInvitationController.js
- frontend/requests/request_invitation_dialog.html
- frontend/test/specs/requestInvitationControllerSpec.js
<p><b>Feature/Bug description:</b> When the user request to be member of institution more than once the message "500 : Error! The sender is already invited" is displayed and the system stop.</p>
<p><b>Solution:</b> Added verification if the emails of user is contained in invitations with sent status for institution.</p>
> Fix user request

- frontend/invites/inviteInstitutionController.js
<p><b>Bug description:</b> The institution requests was not been shown because the response.data is undefined </p>
<p><b>Solution:</b> The response from getRequestsInst does not have data, so, it was removed and the requests are been get directly from the response. </p>
> bug on showing institution requests

- frontend/post/postDetailsDirective.js
<p><b>Feature/Bug description:</b> Showed button edit when is the survey, but the user shouldn't edit the post. </p>
> Fix edit survey

- backend/admin.py
- frontend/post/postDirective.js
- frontend/post/save_post.html
<p><b>Feature/Bug description:</b> When edit post and it has image or video, the user can add other media.</p>
<p><b>Solution:</b> Added verification if has image and set value of video when call method createEditedPost.</p>
> Fix bug add media when edit post and it has media.

- frontend/notification/notificationDirective.js
When the administrator accepted a user's request to be a member of an institution, user.institution_profiles did not update.
</p>
Now, when the user clicks on the notification, he is refreshed.
For this, I've called UserService.load() in notificationController.action().
</p>
> Refreshing the user by notification's action

- backend/handlers/event_handler.py
- frontend/event/event.html
- frontend/event/eventController.js
- frontend/test/specs/eventControllerSpec.js
<p><b>Feature/Bug description:</b> When event is deleted his not disappear on events timeline.</p>
<p><b>Solution:</b> Added a filter in array of events to remove deleted events when the delete function is called.</p>
> fixing delete event bug

- frontend/institution/edit_info.html
- frontend/institution/submit_form.html
<p><b>Feature/Bug description:</b> Wrong color in toolbar and button</p>
<p><b>Solution:</b>  Color changed to teal-500 of toolbar and button </p>
> Fix color edit information institution

- frontend/post/post.js
- frontend/post/postDetailsDirective.js
<p><b>Feature/Bug description:</b> When delete post the date and the user wasn't who deleted post.</p>
<p><b>Solution:</b> Refresh in frontend last_modified_date and last_modified_by in the moment that deleted.</p>
> Fix delete post

- frontend/post/save_post.html
<p><b>Feature/Bug description:</b> The modal size of create post page not according with the new design.</p>
<p><b>Solution:</b> Resizing page to be as specified by designer.</p>
> Resizing the create post page to the new design

- frontend/notification/notificationDirective.js
The user wasn't refreshed when he was deleted from an institution.
</p>
I've added an action in DELETE_MEMBER notification.
</p>
> Adding action in DELETE_MEMBER notification

- frontend/survey/surveyDetailsDirective.js
- frontend/survey/survey_details.html
- frontend/test/specs/surveyDetailsDirectiveSpec.js
<p><b>Feature/Bug description:</b> When the poll has no vote the vote button still appears and is enabled.</p>
<p><b>Solution:</b> Hide the button while the user does not select an option.</p>
> Hide button of vote in survey post

- frontend/home/home.html
<p><b>Feature/Bug description:</b> Broken responsive timeline width.</p>
<p><b>Solution:</b> Change the layout value from column to row, on the div that encapsulated the timeline.</p>
> Fix home timeline responsive width

- backend/handlers/user_handler.py
<p><b>Feature/Bug description:</b> The user can't delete link</p>
<p><b>Solution:</b> Added jsonresponse in method delete</p>
> Fix delete link between member and institution

- frontend/invites/inviteInstHierarchieController.js
<p><b>Feature/Bug description:</b> When admin invite new institution, the pending invite is not displayed.</p>
<p><b>Solution:</b> Opening toolbar of hierarchie when has new pending invite.</p>
> Showing pending invites when the admin send new invites

- frontend/app.js
- frontend/institution/institutionController.js
- frontend/institution/institution_page.html
- frontend/institution/managementMembersController.js
- frontend/institution/management_members.html
- frontend/invites/inviteInstHierarchieController.js
- frontend/invites/inviteInstitutionController.js
- frontend/invites/invite_institution.html
- frontend/invites/invite_institution_hierarchie.html
- frontend/test/specs/UtilsSpec.js
- frontend/test/specs/inviteInstitutionControllerSpec.js
- frontend/test/specs/managementMembersControllerSpec.js
- frontend/user/profile.html
- frontend/utils/utils.js
<p><b>Feature description:</b> Now the invite cards show at most four invites/requests per scroll</p>
> Improved invite cards

- frontend/invites/inviteInstHierarchieController.js
- frontend/post/save_post.html
<p><b>Feature/Bug description:</b> After save survey the post don't change to common post</p>
<p><b>Solution:</b> After save survey call method choice common</p>
> Fix save survey

- backend/handlers/event_handler.py
<p><b>Feature/Bug description:</b> The method delete in event_handler.py didn't has json_response</p>
<p><b>Solution:</b> Added json_response</p>
> Fix delete method in event_handler

- frontend/institution/managementMembersController.js
- frontend/institution/management_members.html
<p><b>Bug description:</b>  The sent invites card was being expanded even when the invite was not being sent because it was invalid</p>
<p><b>Solution:</b> It was set to change showInvites and showSendInvites values only when the invite is successfully sent</p>
> bug on sending user invite

- frontend/auth/configProfileController.js
- frontend/test/specs/configProfileControllerSpec.js
<p><b>Feature/Bug description:</b> Every time a user removes a connection to a facility, a logout is made.</p>
<p><b>Solution:</b> Check if the user has more than one institution, if so, only removes the link, otherwise logout.</p>
>  Fix User Link Removal

- frontend/institution/institutionController.js
- frontend/notification/notificationDirective.js
- frontend/test/specs/userSpec.js
- frontend/user/user.js
When an institution was deleted its profile wasn't update in frontend.
</p>
I've created a removeProfile in user.js and added an action in DELETE_INSTITUTION notification.
</p>
> Fix update institution_profiles when an institution is deleted.

- .travis.yml
- landing/support_institutions.html
<p><b>Feature/Bug description:</b> The layout of support institutions page is not responsive.</p>
<p><b>Solution:</b> Changing layout on the page support institutions.</p>
> Improving responsivity in support_institutions page in landing-page

- frontend/post/comment.html
- frontend/post/postDetailsDirective.js
<p><b>Feature description:</b> set to show all the comments replies when on post details page </p>
> show replies when on post details page

- landing/cisdetails.html
- landing/ecisdetails.html
- landing/privacy.html
- landing/support_institutions.html
- landing/terms.html
<p><b>Feature/Bug description:</b> Titles in subpages of landing page are in lowercase.</p>
<p><b>Solution:</b> Changing the lowercase titles to uppercase.</p>
> changing landing page titles to upper case

- frontend/post/postDetailsDirective.js
- frontend/post/post_details.html
<p><b>Feature/Bug description:</b>it has been set post icons to gray when the post is deleted and set to show different delete messages depending on who deleted it</p>
> change post icons color and post message when it is deleted

- backend/models/event.py
- frontend/home/home.html
In home the institution name appears in the events, instead of the author's name.
</p>
I've change event.author by event.institution_name in home.html.
</p>
> Changing the author's name by the inst's name in home's event view

- frontend/post/pdf_view.html
<p><b>Feature/Bug description:</b> When display is small the pdf view is wrong</p>
<p><b>Solution:</b> Added flex-xs in divs</p>
> When display is small the pdf view is wrong

- frontend/institution/management_members.html
- frontend/invites/invite_institution.html
- frontend/invites/invite_institution_hierarchie.html
<p><b>Feature/Bug description:</b> Label to invite was 'Enviar convite'.</p>
<p><b>Solution:</b> Change to 'Convidar membro' or 'Convidar instituição'.</p>
> Changed label to invite institution or member

- backend/test/invite_collection_handler_test.py
The TODO was useless.
</p>
I've removed it.
</p>
> Removing invite_collection_handler_test's TODO

- backend/search_module/search_institution.py
<p><b>Feature/Bug description:</b> There is no option to search by legal nature.</p>
<p><b>Solution:</b> Create search option by legal nature.</p>
> Create search institution by legal nature

- backend/models/institution.py
- frontend/institution/legal_nature.json
<p><b>Feature/Bug description:</b> The nature of the institutions was outdated.</p>
<p><b>Solution:</b> Add the new options and remove the ones that are no longer needed.</p>
> Modify options of legal nature

- backend/models/request_institution.py
The TODO didn't make sense.
</p>
I've removed it.
</p>
> Removing TODO from request institution's isValid.

- frontend/home/homeController.js
- frontend/test/specs/colorPickerControllerSpec.js
<p><b>Feature/Bug description:</b>The Color Picker Controller doesn't have the test.</p>
<p><b>Solution:</b> Created test.</p>
> Create test to controller ColorPickerController

- frontend/search/search.html
- frontend/search/searchController.js
- frontend/test/specs/searchControllerSpec.js
<p><b>Feature/Bug description:</b> Create search field by legal nature.</p>
<p><b>Solution:</b> Create a new card to search by legal nature.</p>
> Create search field by legal nature

- frontend/institution/submit_form.html
<p><b>Feature/Bug description:</b> User can confirm the institution edition without filling in the required email field.</p>
<p><b>Solution:</b> Use the ng-submit directive to force the user to fill in the required fields.</p>
> Fix required field in edit inst form

- backend/admin.py
- backend/handlers/institution_handler.py
- backend/handlers/institution_hierarchy_handler.py
- backend/handlers/institution_members_handler.py
- backend/handlers/institution_request_handler.py
- backend/models/user.py
- backend/permissions.py
- backend/test/institution_handler_test.py
- backend/test/institution_hierarchy_handler_test.py
- backend/test/institution_member_handler_test.py
<p><b>Feature/Bug description:</b>Remove the decorator is_admin of Institution Handler and check permissions</p>
<p><b>Solution:</b> Create permissions for admin to: <br>
**remove_member of institution <br>
**remove_inst <br>
**remove_link between two institutions <br>
**update_inst <br></p>
<p><b>TODO/FIXME:</b> Do the same to remove the decorator @is_admin of utils.py</p>
> Remove @is_admin of institution handler

- frontend/institution/configInstDirective.js
- frontend/institution/create_inst_form.html
- frontend/institution/institution.js
- frontend/institution/submit_form.html
- frontend/test/specs/configInstDirectiveSpec.js
Changing some institution's fields requirements.
</p>
Refactor the required fields.
</p>
> Making description required and acronym optional

- jenkinsfile
<p><b>Feature/Bug description:</b> Add a jenkins file to the source of the project.</p>
> Jenkins file

- backend/test/decorator_test.py
- backend/test/mocks.py
New mock file to help in backend tests
</p>
I've created a mock file that creates users and institutions providing them an unique hash.
</p>
> Mock file for backend tests

- backend/test/remove_institution_handler_test.py
Refactoring the test for the use of mocks
</p>
I've created the test's entities using the mocks.
</p>
> Refactoring remove institution handler test

- backend/handlers/institution_handler.py
- backend/handlers/institution_hierarchy_handler.py
- backend/handlers/institution_members_handler.py
- backend/handlers/post_collection_handler.py
- backend/models/user.py
- backend/test/institution_member_handler_test.py
- backend/test/model_test/user_test.py
- backend/utils.py
<p><b>Feature/Bug description:</b>Check permissions with denying the condition </p>
<p><b>Solution:</b> Refact method has permission of user</p>
<p><b>TODO/FIXME:</b> Chenge verifications of super users to new mode</p>
> Verify permissions and throw exception in method has_permission of user

- backend/test/followers_institution_handler_test.py
- backend/test/institution_timeline_handler_test.py
- backend/test/mocks.py
- backend/test/remove_institution_handler_test.py
The variables' names weren't generic and the tests weren't using mocks.
</p>
Replace the variables' names by generics names and use mocks.
</p>
> Fix institution's tests

- backend/admin.py
- backend/models/institution.py
- backend/search_module/search_document.py
- backend/search_module/search_institution.py
- backend/test/followers_institution_handler_test.py
- backend/test/institution_timeline_handler_test.py
- backend/test/mocks.py
- backend/test/model_test/request_institution_test.py
- backend/test/model_test/request_user_test.py
- backend/test/remove_institution_handler_test.py
- frontend/institution/configInstDirective.js
- frontend/institution/create_inst_form.html
- frontend/institution/institution.js
- frontend/institution/submit_form.html
<p><b>Feature description:</b> Now it is possible to search an institution by its address state</p>
> Search institution by state

- backend/handlers/invite_handler.py
- backend/models/user.py
<p><b>Feature/Bug description:</b> Now the is_valid method only checks the last profile added</p>
> Refact UserProfile is_valid method

- frontend/auth/login.html
- frontend/auth/loginController.js
<p><b>Feature/Bug description:</b> The text was be wrong. </p>
<p><b>Solution:</b> Changed text.</p>
> Changed text of login

- frontend/institution/configInstDirective.js
<p><b>Feature/Bug description:</b> The photo url of an institution recently created was undefined to the user who created it </p>
<p><b>Solution:</b>It was created a function to set the default photo url when it is undefined</p>
> bug on new institution photo

- backend/handlers/institution_handler.py
- backend/handlers/institution_members_handler.py
- backend/handlers/institution_request_collection_handler.py
- backend/handlers/institution_request_handler.py
- backend/handlers/invite_institution_handler.py
- backend/main.py
- backend/test/institution_handler_test.py
- backend/test/institution_request_handler_test.py
- backend/test/invite_institution_handler_test.py
- backend/utils.py
- frontend/invites/inviteInstitutionController.js
- frontend/main/mainController.js
- frontend/requests/requestInvitationService.js
- frontend/test/specs/inviteInstitutionControllerSpec.js
- frontend/test/specs/suggestInstitutionControllerSpec.js
- frontend/user/user.js
<p><b>Feature/Bug description:</b> Modify method of checking user permissions.</p>
<p><b>Solution:</b> Refactor the method of checking permissions so that it also checks the key of the user's current institution.</p>
> Modify check has permission on utils

- frontend/invites/new_invite_page.html
- frontend/styles/custom.css
New invite's view was broken.
</p>
I've fixed the html by adding another div element and some css' classes.
</p>
> Fix new invite page responsiveness

- frontend/search/search.html
- frontend/search/searchController.js
- frontend/test/specs/searchControllerSpec.js
<p><b>Feature/Bug description:</b> Create search by federal state.</p>
<p><b>Solution:</b> Create a new card to search by federal state.</p>
> Frontend of search institution by federal state

- frontend/institution/managementMembersController.js
- frontend/institution/management_members.html
- frontend/invites/inviteInstHierarchieController.js
- frontend/invites/invite_institution_hierarchie.html
<p><b>Feature/Bug description:</b> Change the color of the display area of ​pending links if there is any request.</p>
<p><b>Solution:</b> create a method that checks whether outstanding requests exist if so, change the color of the display area of ​​the pending links.</p>
> Change display field color for pending links if there is an request

- landing/main.html
<p><b>Feature/Bug description:</b> The toolbar background was scrolling with the page</p>
<p><b>Solution:</b> Add a css position fixed to the toolbar</p>
> Add position fixed css to the md-toolbar

- landing/main.html
<p><b>Feature/Bug description:</b> Toolbar scrolling with the page</p>
> Fix toolbar background

- landing/cisdetails.html
- landing/home.html
- landing/platformcisdetails.html
<p><b>Feature/Bug description:</b> Fix inconsistence in text</p>
<p><b>Solution:</b>Update text about the platform</p>
> Fix text about the platform

- landing/platformcisdetails.html
<p><b>Feature/Bug description:</b> Fix text</p>
<p><b>Solution:</b> Change names</p>
> Fix text about platform

- frontend/institution/institutionController.js
- frontend/institution/removeInstDialog.html
<p><b>Feature/Bug description:</b> Create a new layout for the institution removal dialog.</p>
<p><b>Solution:</b> Using the angularjs directives I have created a new layout for the institution removal dialog.</p>
> New layout of remove inst dialog

- frontend/institution/removeInstDialog.html
<p><b>Feature/Bug description:</b> Create links that leads to the institution page by clicking on the name or image.</p>
<p><b>Solution:</b> Using the ui-sref directive, I created the link that points to the institution page.</p>
> Add link of institution page visualization

- frontend/app.js
- frontend/event/event.html
- frontend/event/eventController.js
- frontend/event/event_details.html
- frontend/home/homeController.js
<p><b>Feature/Bug description:</b> The timeline of events are out of sync with new layout proposed by designer of e-cis.</p>
<p><b>Solution:</b> Changing timeline of events to seem like a timeline of posts, except by some differences like share button on left side of event card.</p>
> Improving event timeline

- frontend/institution/managementMembersController.js
- frontend/institution/management_members.html
- frontend/institution/removeMemberDialog.html
<p><b>Feature/Bug description:</b> Now when the dialog appears, it shows the user that is going to be removed</p>
> Redesign remove member dialog

- ecis
- frontend/auth/login.html
- frontend/auth/loginController.js
- frontend/config.js
<p><b>Feature/Bug description:</b> Changed the view to show buttons and fields vertically</p>
> Changed the login view

- frontend/event/event.html
- frontend/event/eventController.js
- frontend/event/event_details.html
- frontend/post/post_details.html
- frontend/test/specs/eventControllerSpec.js
<p><b>Feature/Bug description:</b> The details of events in timeline are not according with the new designed pages.</p>
<p><b>Solution:</b> Changing layout, responsivity and displaying infos according with the new design.</p>
> Changing event layout

- backend/worker.py
The worker wasn't working as expected when the entity type were post or institution because they weren't imported into the file.
PS: These imports can't be removed. Despite they seem to be useless into worker.py, the last one only works properly when it has that imports.
</p>
I've added the imports in worker.py.
</p>
> Fix worker imports

- frontend/user/profile.html
- frontend/user/profileService.js
<p><b>Feature/Bug description:</b> Old design to view profile user.</p>
<p><b>Solution:</b> Change design.</p>
<p><b>TODO/FIXME:</b> The button edit don't hide in the right time.</p>
> View Profile User

- backend/firebase.py
- backend/handlers/institution_handler.py
- backend/handlers/institution_hierarchy_handler.py
- backend/handlers/institution_members_handler.py
- backend/handlers/like_handler.py
- backend/handlers/post_collection_handler.py
- backend/handlers/post_comment_handler.py
- backend/handlers/reply_comment_handler.py
- backend/handlers/request_handler.py
- backend/models/institution.py
- backend/models/invite.py
- backend/service_messages.py
- backend/worker.py
- frontend/notification/notificationDirective.js
- frontend/notification/notificationService.js
- frontend/notification/notifications.html
<p><b>Feature/Bug description:</b> Created functions to generate message and entity for notifications and refactored the code related to notification</p>
> Add user and institutions data to notification

- frontend/auth/config_profile.html
- frontend/styles/custom.css
<p><b>Feature/Bug description:</b> Edit profile page are not according with new project design.</p>
<p><b>Solution:</b> Changed to new page of edit the profile.</p>
> New page of edit the profile

- frontend/auth/config_profile.html
- frontend/styles/custom.css
<p><b>Feature/Bug description:</b> The icon is behind maximum size of button.</p>
<p><b>Solution:</b> Adding css style to increase size of button to support icon inside.</p>
> Adding style to md-button in the user picture to show icon in center

- frontend/post/comment.html
- frontend/post/postDetailsDirective.js
- frontend/test/specs/commentControllerSpec.js
<p><b>Feature/Bug description:</b> Bug in reply comment, the condition in html that show the div was wrong.</p>
<p><b>Solution:</b> The condition was "showReply && !commentCtrl.canReply() && !commentCtrl.isInstInactive()" it changed to "commentCtrl.canReply()". The method canReply() in controller was modified to verify all conditions needed that user can reply.</p>
<p><b>TODO/FIXME:</b> </p>
> Fix bug to reply comment

- frontend/auth/configProfileController.js
- frontend/auth/config_profile.html
- frontend/user/edit_profile.html
<p><b>Feature/Bug description:</b> The edit institutional profile are out of sync with new design.</p>
<p><b>Solution:</b> Changing html to display layout according by new design.</p>
> New layout of edit institutional profile

- backend/templates/invite_user.html
The html was with a wrong width size. Besides, it was missing the name CIS in the beginning of the email.
</p>
I've fixed the width property and inserted "CIS".
</p>
> Fix invite_user.html

- frontend/app.js
- frontend/institution/base_institution_page.html
- frontend/institution/institutionController.js
- frontend/institution/managementMembersController.js
- frontend/institution/members.html
- frontend/test/specs/institutionControllerSpec.js
- frontend/test/specs/managementMembersControllerSpec.js
<p><b>Feature/Bug description:</b> Create a view member institution, that is visible to all user of the platform. The page contains first the admin of institution then all members of the institution, the user can search by name. </p>
<p><b>Solution:</b> Create using design for all size.</p>
> View members of institution

- frontend/app.js
- frontend/institution/base_institution_page.html
- frontend/institution/followers.html
- frontend/institution/institutionController.js
- frontend/institution/institutionService.js
- frontend/test/specs/followersInstControllerSpec.js
- frontend/test/specs/institutionControllerSpec.js
<p><b>Feature/Bug description:</b> View followers institution contains all followers and user can search by one.</p>
<p><b>Solution:</b> Created a view using design and responsiveness.</p>
> View followers institution

- frontend/institution/timeline_inst.html
The view was broken when an institution had an empty timeline.
</p>
I've added a width=100% into post-timeline directive.
</p>
> Adding width in post-timeline directive

- Jenkinsfile
<b>Feature/Bug description:</b> The slack notification are not friendly, showing the job URL and poor color patterns.
<p><b>Solution:</b> Customize the sendSlack notification of the Jenkins Pipeline, adding a Material Color pattern and a Build Number with link to the job URL.</p>
<p><b>TODO/FIXME:</b> Discover how to get the commit data to display a more elaborated message.</p>
> Custom slack notifications

- frontend/home/homeController.js
- frontend/utils/messageService.js
Events that had already been closed were being shown at home
</p>
I've fixed the method activeEvents.
</p>
> Fix showing inactive events in home

- backend/search_module/search_institution.py
- backend/test/followers_institution_handler_test.py
- backend/test/institution_timeline_handler_test.py
- backend/test/invite_collection_handler_test.py
- backend/test/mocks.py
- backend/test/model_test/request_user_test.py
- backend/test/remove_institution_handler_test.py
- backend/test/search_handler_test.py
<p><b>Feature/Bug description:</b> The search by description of institution are not implemented yet.</p>
<p><b>Solution:</b> Implementing search by description of institutions in server side of application.</p>
> Search institution by description

- backend/search_module/search_institution.py
- frontend/app.js
- frontend/main/mainController.js
- frontend/search/search.html
<p><b>Feature/Bug description:</b> The view was old layout, and the institution object found did not have all information necessary.</p>
<p><b>Solution:</b> Changing design according to suggestion, using CSS, HTML, and AngulaMaterial.
Changed the rote "search", now this is part of app.user, so the new view is a complement of the user left bar. Created email field in the document of the institution. </p>
Imagens do S5:
> Changed design view search

- frontend/institution/followers.html
- frontend/institution/members.html
<p><b>Feature/Bug description:</b> The toolbar had a border.</p>
<p><b>Solution:</b> Put toolbar outside "md-card-content" </p>
> Changed place of toolbar

- backend/admin.py
<p><b>Feature/Bug description:</b> Reset the datastore to be used on test version.
</p>
<p><b>Solution:</b> Create ResetMSHandler call by the route admin/reset/ms to create the  Institution MInistério da Saúde and your administrator.</p>
<p><b>TODO/FIXME:</b> Analyse if the email of official administrator wiil be testeeciis@gmail.com
</p>
> Reset datastore to create Ministério da Saúde and it's administrator

- frontend/institution/base_institution_page.html
- frontend/styles/custom.css
<p><b>Feature/Bug description:</b> Create a new layout for the cover of the institution according to what was passed by the design.</p>
<p><b>Solution:</b> Using the angular and css directives, I created a new layout for the cover of the institution.</p>
> New layout of institution cover

- frontend/auth/login.html
- frontend/user/user_inactive.html
<p><b>Feature/Bug description:</b> On version tests the invitation request flow is unavailable
</p>
<p><b>Solution:</b> Hide the button to request invite and hide the invitation request flow for inactive users</p>
<p><b>TODO/FIXME:</b> Undo this changes when invitation request flow will be available
</p>
> Hide request invite for new users

- backend/models/institution.py
- frontend/institution/create_inst_form.html
- frontend/institution/registration_data.html
- frontend/institution/submit_form.html
<p><b>Feature/Bug description:</b> The model institution didn't has the attribute branch_line.</p>
<p><b>Solution:</b> Added attribute in template and added field in create institution and edit institutional information.</p>
> Create attribute branch_line in institution

- landing/home.html
- landing/main.html
<p><b>Feature/Bug description:</b>The platform finishes the pre-registration phase. </p>
<p><b>Solution:</b> Change the button interesr to login button.</p>
> Change button interest to login

- frontend/home/homeController.js
- frontend/institution/base_institution_page.html
- frontend/institution/institutionController.js
- frontend/institution/management_institution_page.html
- frontend/main/mainController.js
- frontend/styles/custom.css
- frontend/user/left_nav.html
<p><b>Feature/Bug description:</b> The user left bar don't show what option is selected.</p>
<p><b>Solution:</b> Created stateView variable in homeController that contains the current state, so the Class CSS  in HTML change according stateView. </p>
> Display select option user left bar

- frontend/invites/inviteInstitutionController.js
- frontend/invites/invite_institution.html
- frontend/test/specs/inviteInstitutionControllerSpec.js
- frontend/utils/messageService.js
Resend the email and the notification to the user that received an invite to be an institution's admin.
</p>
I've created a function in InviteInstController that calls resendInviteHandler. There, the invite.sendInvite method is called.
</p>
> Resend institution invite

- backend/models/user.py
- backend/test/model_test/institution_profile_test.py
- frontend/invites/newInviteController.js
- frontend/invites/new_invite_page.html
- frontend/user/edit_profile.html
<p><b>Feature/Bug description:</b> Didn't exist the attribute branch_line in profile_user.</p>
<p><b>Solution:</b> Created the attribute in model.</p>
>> S5
> Create attribute branch_line in profile_user

- frontend/user/edit_profile.html
<p><b>Feature/Bug description:</b> The inputs of edit_profile didn't have the tag name.</p>
<p><b>Solution:</b> Added tag name.</p>
> Add tag name in edit_profile.html inputs 

- frontend/institution/base_institution_page.html
- frontend/institution/institutionController.js
- frontend/test/specs/institutionControllerSpec.js
<p><b>Feature/Bug description:</b>  When entering the institution page several errors appear on the console indicating that the current instittution is null when the showFollowButton method is called.</p>
<p><b>Solution:</b> Add one more check in the showFollowButton method, which makes sure the current intitution exists before checking its properties.</p>
> Fix show follow button in institution controller

- frontend/user/left_nav.html
<p><b>Feature/Bug description:</b> The button my settings wasn't used.</p>
<p><b>Solution:</b> Removed the button.</p>
> Removed button my settings of user left-nav

- frontend/post/postDetailsDirective.js
<p><b>Feature/Bug description:</b> When have several clicks in like/deslike comments and replys redirect the user to error page. </p>
<p><b>Solution:</b> Added error handling to show message.</p>
> Added error handling in like/deslike comment and reply

- frontend/institution/institutionController.js
- frontend/institution/removeInstDialog.html
when the user removed his unique institution he still had access to the platform
</p>
I've called Authservice.logout() when the user removed his unique institution
</p>
> Fix remove institution when It is the unique

- frontend/institution/base_institution_page.html
- frontend/institution/management_institution_page.html
- frontend/institution/registration_data.html
- frontend/institution/timeline_inst.html
<p><b>Feature/Bug description:</b>In  this pull request #674   @Luiz-FS 
change the name of the object from current_institution to institution, but he has not changed everywhere in the code 
</p>
<p><b>Solution:</b>Update the name of objetc fron current_institution to institution</p>
> Fix name of object in institution controller

- frontend/institution/configInstDirective.js
- frontend/institution/followers.html
- frontend/institution/institutionController.js
- frontend/institution/institution_events.html
- frontend/institution/managementMembersController.js
- frontend/institution/members.html
- frontend/institution/registration_data.html
- frontend/institution/submit_form.html
- frontend/post/postDetailsDirective.js
- frontend/post/post_details.html
<p><b>Feature/Bug description:</b>Some pages has not progress circular before load data</p>
<p><b>Solution:</b> Insert load progress circular on:
- Sub-pages of institution page: members, registration data, followers, events
- Load comments of post
- Manage institution: edit info</p>
> Load progress circular

- frontend/institution/configInstDirective.js
<p><b>Feature/Bug description:</b>Redirect user who create institution to home page instead of empty institution page</p>
<p><b>Solution:</b>Redirect user after create institution to home page</p>
> Redirect user to home page after create institution

- frontend/main/main.html
- frontend/main/mainController.js
- frontend/styles/custom.css
<p><b>Feature/Bug description:</b> Didn't existed reported button.</p>
<p><b>Solution:</b> Created report burtton using z-index and other tools of CSS.</p>
> Created report button

- frontend/home/home.html
- frontend/institution/members.html
- frontend/user/profile.html
- frontend/user/profileService.js
<p><b>Feature/Bug description:</b> When user email is big the layout broken. </p>
<p><b>Solution:</b> Removed percentage of margin and limit string</p>
> Fixed longer emails in my profile.

- frontend/home/home.html
- frontend/index.html
<p><b>Feature/Bug description:</b> Uodate title to new project name</p>
<p><b>Solution:</b> Update name, fix show icon, and insert style clickable on institution button</p>
> Change app title

- backend/models/institution.py
- frontend/institution/legal_nature.json
- frontend/test/specs/configInstDirectiveSpec.js
<p><b>Feature/Bug description:</b>New option in legal nature options</p>
<p><b>Solution:</b> Insert startup in legal nature options</p>
> New option startup in legal nature options

- backend/utils.py
<p><b>Feature/Bug description:</b>When the new user follow the health ministry institution only the user was update.</p>
<p><b>Solution:</b> Update de Health Ministry too, when the new user follow</p>
> Update followers of health ministry

- backend/search_module/search_document.py
- backend/search_module/search_institution.py
- backend/search_module/search_user.py
<p><b>Feature/Bug description:</b> NoneType error when searching for document during the process of update institution or user.</p>
<p><b>Solution:</b> The error wasn't resolved once the cause isn't determined yet. The workaround threat the NoneType returned from the get index, and log the problem when it occurs, preventing the process to continue.</p>
<p><b>TODO/FIXME:</b> Refact this flow to update document, avoiding NoneType when the index is searched.</p>
> Workaround to fix NoneType error when searching for document

- backend/handlers/institution_handler.py
- backend/handlers/institution_members_handler.py
- backend/send_email_hierarchy/email_sender.py
- backend/send_email_hierarchy/invite_institution_email_sender.py
- backend/send_email_hierarchy/invite_user_email_sender.py
- backend/send_email_hierarchy/remove_institution_email_sender.py
- backend/templates/invite_institution_email.html
- backend/templates/invite_user.html
- backend/worker.py
The emails' buttons weren't clickable in hotmail.
</p>
I've added the links right below the buttons.
</p>
> Adding the links below the buttons in emails html

- backend/admin.py
<p><b>Feature/Bug description:</b>Change email of Health Ministry admin </p>
<p><b>Solution:</b> Change email of Health Ministry admin to plataformavirtualcis@gmail.com on ResetMSHandler.</p>
> Change email of Health Ministry admin

- frontend/search/searchController.js
The search's filters hadn't been loaded.
</p>
I've created a function that transforms the json in an objects array.
</p>
> Fix search filters

- backend/worker.py
<p><b>Feature/Bug description:</p> Update name of sender email</p>
<p><b>Solution:</b> Change name to PLataforma Virtual CIS</p>
> Ppdate sender name of email

- backend/admin.py
- backend/handlers/institution_followers_handler.py
- backend/utils.py
- frontend/institution/institutionController.js
<p><b>Feature/Bug description:</b> The super institution now is DECIIS, so this institutuion must be create with MS, and the adm has permission to send invite for new institutions whe is logged with DECIIS, not more when is logged by MS. Other thing is that all user have to follow MS and DECIIS Institution</p>
- <p><b>Solution:</b>
- Create the new institution DECIIS
- Insert the official email of adm to deciis@saude.gov.br
- Force all user to follow DECIIS and MS institutions
</p>
<p><b>TODO/FIXME:</b> Think of a better way to do  make all users follow this institutions</p>
> Create Institution DECIIS

- frontend/auth/configProfileController.js
- frontend/user/edit_profile.html
<p><b>Feature/Bug description:</b> In edit user page when change the name or cpf withou click in button "Concluir edição" the change was saved.</p>
<p><b>Solution:</b> Created the copy of user that contain new information, when save edition the original user is changed..</p>
> Fix edit user

- backend/handlers/institution_handler.py
- backend/handlers/invite_handler.py
- backend/models/institution.py
- frontend/invites/newInviteController.js
- frontend/invites/new_invite_page.html
<p><b>Feature/Bug description:</b> Fix the accept invitation page because it was allowing the user to click the accept invitation button several times which caused a bug in the user profiles that were repeated.</p>
<p><b>Solution:</b> I prevented the invitation from being accepted several times on the server side and hid the button to accept the invitation in the frontend when it has already been clicked, instead, I added a circular progress.</p>
> Fix accept invite user

- frontend/post/save_post.html
The post's text wasn't with scroll.
</p>
I've added an overflow property to the textarea's style.
/p>
> Fix edit post view

- frontend/institution/configInstDirective.js
- frontend/institution/create_inst_form.html
- frontend/user/user.js
<p><b>Feature/Bug description:</b> Sometimes, the user property institution_profile is not initialized when a new profile is going to be added, hence it happens a typeError. Furthermore, at this moment, the user get stuck on that form and he can submit the data more than once.</p>
<p><b>Solution:</b> It was added a verification to method addProfile to check if the property is defined before add a new profile. And, on new institution form, when it is submitted, the submit button is substituted by a progress circular. </p>
> added verification to user method addProfile

- frontend/event/event.html
- frontend/institution/institution_events.html
<p><b>Feature/Bug description:</b> Add a message on the institution's events page to be displayed when have no events.</p>
<p><b>Solution:</b> I created a card on the event page that appears when there is no event to be displayed.</p>
> Show message in event page if not exists event

- frontend/institution/institutionController.js
- frontend/institution/removeInstDialog.html
- frontend/test/specs/removeInstControllerSpec.js
Remove institution dialog was showing the option to remove or not the hierarchy even if the institution didn't have children. 
</p>
I've added a condition in the html that only allows to show that option if the institution has children.
In the following examples SPLAB has children and CERTBIO doens't.
</p>
> Fix remove institution dialog

- frontend/post/comment.html
- frontend/post/post_details.html
<p><b>Feature/Bug description:</b> Modify the title of the liking button when a user likes or dislike a post.</p>
<p><b>Solution:</b> Using an ifter I changed the button title when an operation was done.</p>
> Modify title of like button in post

- backend/search_module/search_institution.py
- frontend/search/search.html
- frontend/search/searchController.js
- frontend/test/specs/searchControllerSpec.js
The search's filters in frontend weren't working as expected. 
</p>
I've implemented a logic, manipulating the data, that makes the filters work at the same time.
</p>
> Improving search

- frontend/institution/create_inst_form.html
- frontend/invites/new_invite_page.html
<p><b>Feature/Bug description:</b> The toolbar of steps not appears and green background not fill completely in small screens.</p>
<p><b>Solution:</b> Adding a md-content directive to fill green background in small screens and changing divs to show toolbar of steps correctly.</p>
> Fixing view of create institution

- frontend/notification/notificationDirective.js
- frontend/notification/notifications.html
- frontend/styles/custom.css
<p><b>Feature/Bug description:</b> The number of notifications aren't displayed to user.</p>
<p><b>Solution:</b> Adding a data-badge to show the number of notifications.</p>
> Adding a counter of notifications in main toolbar

- frontend/post/post_details.html
- frontend/styles/custom.css
<p><b>Feature/Bug description:</b>Wrong line breaks</p>
<p><b>Solution:</b> Create a css to fix and recognize line breaks
Before:
After: 
</p>
> Create css for text

- frontend/auth/configProfileController.js
<p><b>Feature/Bug description:</b> When user cancel the editing of profile, the infos changed keep in the user.</p>
<p><b>Solution:</b> Creating old reference to profile to not keep the changes in user.</p>
> Fix edit profile modificates user info without save

- frontend/event/eventDetailsDirective.js
- frontend/event/event_details.html
<p><b>Feature/Bug description:</b> The address in case of missing some infos show "--".</p>
<p><b>Solution:</b> Adding verification in gets of properties.</p>
> Fixing the display of event address

- frontend/event/event.html
- frontend/event/eventController.js
<p><b>Feature/Bug description:</b> In edition of event that has a picture, this picture is not shown.</p>
<p><b>Solution:</b> Adding the photo_url property of event to controller for display the picture of event.</p>
> Adding the missing picture in edit of event

- frontend/survey/surveyDetailsDirective.js
- frontend/survey/survey_details.html
<p><b>Feature/Bug description:</b> The percentage of votes in survey is displayed to author only when him votes.</p>
<p><b>Solution:</b> Adding to ng-if the verification to show percentage of votes when the user is author of survey.</p>
> Displaying the percentage of votes to author of survey any moment

- frontend/app.js
- frontend/home/homeController.js
- frontend/invites/newInviteController.js
- frontend/invites/welcome_dialog.html
- frontend/main/main.html
- frontend/styles/custom.css
- frontend/user/left_nav.html
<p><b>Feature/Bug description:</b> Display to the user, at the first login, a quick tour to welcome and demonstrate how report problems.</p>
<p><b>Solution:</b> Create a dialog to display the welcome message then a button that hides the dialog and shows another dialog near the report button.</p>
> Welcome tutorial

- frontend/event/event_dialog.html
- frontend/institution/configInstDirective.js
- frontend/institution/create_inst_form.html
- frontend/institution/institution.js
- frontend/institution/submit_form.html
- frontend/styles/custom.css
- frontend/test/specs/configInstDirectiveSpec.js
<p><b>Feature/Bug description:</b>The user can created without answer the fields of adress.</p>
<p><b>Solution:</b> Added verification.</p>
> Fixed create institution form.

- frontend/post/postDirective.js
- frontend/post/save_post.html
<p><b>Feature/Bug description:</b> Add error messages in the text fields in post creation so that they are displayed when the user no to fill in any required fields.</p>
<p><b>Solution:</b> I added the form tag in the creation of the post and added 'required' in the required fields so that the user can not create a post without filling in the required fields.</p>
> Add required in fields of create post form

- frontend/invites/acceptInviteController.js
- frontend/invites/accept_invite.html
<p><b>Feature/Bug description:</b> Fix bug by accepting the invitation for the link received by email. When the user already logged in system and try to accept the invitation from the link received by email, it is redirected to a timeline and not to the invitation page as it should be.</p>
<p><b>Solution:</b> I created a method of name 'signin' in the acceptInviteController, which checks if the user is already logged in, if yes, redirects to the invitation page, otherwise goes to the login page.</p>
> Fix bug of accept invite from email

- frontend/event/eventController.js
- frontend/event/event_details.html
- frontend/event/event_dialog.html
- frontend/styles/custom.css
- frontend/test/specs/eventDialogCtrlSpec.js
<p><b>Feature/Bug description:</b> The user was created event without answer complete address.</p>
<p><b>Solution:</b> Created method that verifies each step of creation event, and when Country is Brazil the user should put all address</p>
> Fix create event

- frontend/post/postDetailsDirective.js
- frontend/post/post_details.html
Add progress-circular to post page
</p>
Add md-progress-circular tag in post_details.html and control it by a method in postDetailsController.
</p>
> Add progress circular to post page

- backend/worker.py
<p><b>Feature/Bug description:</b> Change email sender on worker</p>
<p><b>Solution:</b> Change email sender to plataformavirtualcis@gmail.com</p>
> Change email sender

- frontend/styles/custom.css
<p><b>Feature/Bug description:</b> The notification badge work strange when has more than 99 notifications.</p>
<p><b>Solution:</b> Changing text size and dimensions of badge.</p>
> Improving notification badge

- frontend/invites/newInviteController.js
- frontend/invites/new_invite_page.html
Add progress-circular to new_invite_page
</p>
Add md-progress-circular tag in new_invite_page.html and control it by a loading flag in the new_invite_controller.
</p>
> Add progress-circular to new_invite_page

- backend/handlers/institution_members_handler.py
- backend/models/request_institution.py
- backend/models/request_institution_children.py
- backend/models/request_institution_parent.py
- backend/models/request_user.py
- backend/templates/invite_institution_email.html
- backend/templates/invite_user.html
- frontend/auth/login.html
- frontend/institution/configInstDirective.js
- frontend/user/user_inactive.html
<p><b>Feature/Bug description:</b> Change the name of the e-CIS platform to the CIS platform.</p>
<p><b>Solution:</b> In places where the name e-CIS was still being used, I switched to CIS platform.</p>
> Change name ecis to cis in verification email

- frontend/institution/managementMembersController.js
- frontend/institution/management_members.html
<p><b>Feature/Bug description:</b> If spent very time to send invite the user could click several times in send button.</p>
<p><b>Solution:</b> Show loading while the invite is sent.</p>
> Add loading when invite member

- frontend/main/mainController.js
<p><b>Feature/Bug description:</b> Report button redirect to home of suport page.</p>
<p><b>Solution:</b> Changed URL.</p>
> Change URL that report button redirect.  

- frontend/institution/base_institution_page.html
- frontend/institution/institutionController.js
<p><b>Feature/Bug description:</b> Institution page didn't has come back button.</p>
<p><b>Solution:</b> Created button that redirect to home.</p>
> Create home button

- frontend/post/post_details.html
- frontend/survey/save_survey.html
<p><b>Feature/Bug description:</b> Unnecessary divider appears in a survey type post when the user is not the author of the survey.</p>
<p><b>Solution:</b> Hide the divider when the user is not the author of the survey.</p>
> Hide divider if is survey post and add required in date of save survey

- frontend/auth/config_profile.html
- frontend/event/event.html
- frontend/event/event_dialog.html
- frontend/event/event_page.html
- frontend/home/home.html
- frontend/institution/base_institution_page.html
- frontend/institution/create_inst_form.html
- frontend/institution/followers.html
- frontend/institution/institution_events.html
- frontend/institution/management_institution_page.html
- frontend/institution/members.html
- frontend/institution/registration_data.html
- frontend/institution/timeline_inst.html
- frontend/invites/invite_institution.html
- frontend/post/save_post.html
- frontend/search/search.html
- frontend/styles/custom.css
- frontend/survey/panel-voters.html
- frontend/survey/save_survey.html
- frontend/user/edit_profile.html
- frontend/user/profile.html
- frontend/user/user_inactive.html
<p><b>Feature/Bug description:</b> In timeline and other screens that has scroll, the display option of scroll is None.</p>
<p><b>Solution:</b> Adding a personalized scrollbar in screens that has scroll.</p>
> Adding personalized scrollbar in screens of system.

- frontend/post/save_post.html
<p><b>Feature/Bug description:</b> On editing post dialog, when the post has an image and the button to remove it is clicked, the dialog is closed and the post is saved.</p>
<p><b>Solution:</b>It was changed the button tag from button to md-button</p>
> Fix bug on editing post

- frontend/event/event_details.html
- frontend/post/share_post_dialog.html
<p><b>Feature/Bug description:</b> The modal layout of event sharing does not agree with the new layout of the events.</p>
<p><b>Solution:</b> Using the 'event-details' directive I fixed the modal layout of event sharing to fit the new layout.</p>
> Change layout of share event dialog

- frontend/search/searchController.js
The method keywordHasChanges was returning true always, because initialInstitution no longer existed.
</p>
I've changed initialInstitutions to institutions and reinforced the keyWordHasChanged verification.
</p>
> Fix search

- frontend/institution/configInstDirective.js
- frontend/institution/create_inst_form.html
- frontend/institution/submit_form.html
<p><b>Feature/Bug description:</b> The user could put anything in fields "branch_line" and number of adress.</p>
<p><b>Solution:</b> Added regex in fields.</p>
> Show erro message when user put something different of number in branch_line and number house

- frontend/test/specs/managementMembersControllerSpec.js
- frontend/utils/utils.js
The system was been tested by only one test.
</p>
I've removed the focus from the test.
</p>
> Removing focus from the frontend's tests

- frontend/event/event.html
- frontend/post/postDetailsDirective.js
<p><b>Feature/Bug description:</b>On event view, it was happenig an error caused by an md-menu tag inside the md-card-actions. And. on  SharePostController, the method postToRul was trying to call the method replace from object text even when it was null.</p>
<p><b>Solution:</b> It was removed the unnecessary html tag md-menu, from share_post_dialog, and added verification to method postToUrl, from SharePostController.
</p>
> fix bug when sharing event

- frontend/institution/configInstDirective.js
- frontend/institution/create_inst_form.html
- frontend/institution/institution.js
- frontend/institution/submit_form.html
<p><b>Feature/Bug description:</b> The field number address was required in create institution form. Can submit invalid form</p>
<p><b>Solution:</b> Added verification that the user can create without put number address and can submit form only when is valid.</p>
> The user can create institution without put number address

- backend/admin.py
- frontend/institution/timeline_inst.html
<p><b>Feature/Bug description:</b> The desciption didn't respected the line break.</p>
<p><b>Solution:</b> Added CSS class.</p>
> Fix break line in description Institution

- frontend/institution/base_institution_page.html
- frontend/institution/followers.html
- frontend/institution/members.html
- frontend/institution/registration_data.html
- frontend/main/main.html
<p><b>Feature/Bug description:</b>On firefox the timeline scroll doesn't work</p>
<p><b>Solution:</b>Change div to md-content</p>
> Fix scroll on firefox

- frontend/post/postDetailsDirective.js
- frontend/post/post_details.html
- frontend/styles/custom.css
<p><b>Feature/Bug description:</b> Post of inactive institution should have different view.</p>
<p><b>Solution:</b> Created a custom Class.</p>
> Change post view of inactive institution

- frontend/notification/notificationDirective.js
- frontend/requests/request_processing.html
<p><b>Feature/Bug description:</b> Create a new layout for the modal of accepting user requests to be members of an institution.</p>
<p><b>Solution:</b> Using the angular directives I created the new layout for the modal of accepting requests from users to be a member of an institution according to the layout defined by the design.</p>
> Create new layout of accept request user modal

- frontend/event/eventController.js
<p><b>Feature/Bug description:</b>The current message say for to wait aprovation after create a event. Now this message say just success.</p>
> Changing message in showToast after create event

- frontend/event/event.html
- frontend/event/eventController.js
- frontend/event/event_dialog.html
- frontend/home/home.html
- frontend/index.html
- frontend/institution/followers.html
- frontend/institution/institution_events.html
- frontend/institution/management_members.html
- frontend/institution/members.html
- frontend/institution/registration_data.html
- frontend/institution/submit_form.html
- frontend/institution/timeline_inst.html
- frontend/invites/new_invite_page.html
- frontend/post/post_details.html
- frontend/post/timeline.html
- frontend/search/search.html
- frontend/utils/loadCircleDirective.js
- frontend/utils/load_circle.html
<p><b>Feature/Bug description:</b> Encapsulating md-progress-circular to own directive of system.</p>
> Load circle directive

- frontend/event/eventDetailsDirective.js
- frontend/event/event_details.html
Some event's fields were overcoming the card's margin.
</p>
I've solved the problems with some css' classes.
</p>
> Fixing event's long fields

- frontend/post/save_post.html
The textarea's height was very large.
</p>
Decrease the height.
</p>
> Fixing the post creation's card height

- frontend/event/eventController.js
It was missing a variable declaration "var" in eventDialogController, what has created a problem when the user tries to edit the event.
</p>
I've added the variable declaration.
</p>
> Fix updateEvent function

- frontend/notification/notificationService.js
Every time a notification arrives the showToast was showed. It was creating a kind of a spam.
</p>
I've removed the showToast from the notification service.
</p>
> Removing showToast from notification service

- frontend/institution/base_institution_page.html
The institution-page's scrollbar wasn't customized.
</p>
I've added the css' class that customizes the scrollbar.
</p>
> Adding custom-scrollbar class in institution-page

- backend/handlers/vote_handler.py
- backend/models/survey_post.py
<p><b>Feature/Bug description:</b>Refact to minimize concurrency problems</p>
<p><b>Solution:</b>isolate only the transactional action and update to try 10 times</p>
> Improve post of vote handler

- frontend/post/postDetailsDirective.js
- frontend/post/post_details.html
- frontend/test/specs/postDetailsControllerSpec.js
The button "Atualizar post" wasn't working as expected. It was only reloading the comments.
</p>
I've created a reloadPost function that reload all the post. 
</p>
> Fix update post button

- backend/test/invite_handler_test.py
- frontend/institution/institutionService.js
- frontend/requests/requestInvitationService.js
- frontend/utils/utils.js
<p><b>Feature/Bug description:</b> The current institution was being passed as request params on post method, on InstitutionService, and on put and delete methods, on RequestInvitationService. </p>
<p><b>Solution:</b> It was removed in both cases.</p>
> removed currentInstitution from request params

- frontend/event/event.html
- frontend/home/home.html
- frontend/institution/followers.html
- frontend/institution/institution_events.html
- frontend/institution/members.html
- frontend/institution/registration_data.html
- frontend/institution/submit_form.html
- frontend/institution/timeline_inst.html
<p><b>Feature/Bug description:</b> The circle progress didn't has the right size in some views.</p>
<p><b>Solution:</b> Pass variable that add 'layout-fill' in CSS class of circle progress</p>
> Fix div circle progress in some views.

- frontend/institution/members.html
<p><b>Feature/Bug description:</b> The members cards has a content out of card.</p>
<p><b>Solution:</b> Changed max-height value of content card.  </p>
> Fix member card in firefox

- frontend/event/eventController.js
<p><b>Feature/Bug description:</b> Return erro when user click in button 'cancel'.</p>
<p><b>Solution:</b> Removed function.</p>
> Fix error when cancel the creation of event

- frontend/auth/authService.js
- frontend/notification/notificationDirective.js
- frontend/notification/notificationService.js
The user was been update only If he clicks on the notification.
</p>
I've thrown an event from notificationService and the listener, AuthService, reload the user when it catches the event.
</p>
> Fix request user consistency

- frontend/institution/management_institution_page.html
- frontend/institution/management_members.html
<p><b>Feature/Bug description:</b> The manage members view has a scrollbar even had little information. </p>
<p><b>Solution:</b> Removed layout-fill.</p>
> Fix manage members view

- backend/handlers/institution_handler.py
- backend/models/user.py
- backend/test/invite_handler_test.py
- backend/test/model_test/institution_profile_test.py
- frontend/institution/configInstDirective.js
- frontend/user/user.js
<p><b>Feature/Bug description:</b> When the institution info are updated the info in user profile is not updated.</p>
<p><b>Solution:</b> Updating this infos in client side and get from server side by key of institution.</p>
> Fix bug in update of profile

- backend/handlers/vote_handler.py
- backend/models/survey_post.py
- backend/test/model_test/survey_post_test.py
<p><b>Feature/Bug description:</b>The survey was updated in datastore two times.</p>
<p><b>Solution:</b>Make survey be updated only one time when method post is called. Move the transactional notation to the method that updates the survey</p>
> Move transactional to the method that update the survey

- frontend/user/profile.html
<p><b>Feature/Bug description:</b> Centralize circular progress in user profile modal</p>
<p><b>Solution:</b> I inserted a div above md-progress and used the layout row along with layout-align to centralize md-progress.</p>
> Fix position of md progress in user profile modal html

- frontend/index.html
- frontend/post/postDirective.js
- frontend/post/save_post.html
- frontend/test/specs/preventStateChangeDirectiveSpec.js
- frontend/test/specs/submitFormListenerServiceSpec.js
- frontend/utils/preventStateChangeDirective.js
- frontend/utils/submitFormListenerDirective.js
- frontend/utils/submitFormListenerService.js
<p><b>Feature/Bug description:</b> Prevent the user from leaving the page if they are filling out a form.</p>
<p><b>Solution:</b> I created a directive that receives the model that will be modified, and it verifies if the template has been modified, if it has been modified it blocks the page change and asks the user if it really wants to leave the page without saving the changes made.</p>
> Create submit form listener directive

- frontend/app.js
- frontend/error/error.html
<p><b>Feature/Bug description:</b> New error page according by new design.</p>
<p><b>TODO/FIXME:</b> Add a optional button to go to home page and edit responsivity to small screens.</p>
> New error page

- frontend/institution/management_members.html
Make md-list-item show the profile in management-members.html
</p>
Add ng-click="manageMemberCtrl.showUserProfile(member.key, $event)"
</p>
> Making md-list-item show the profile in management-members

- frontend/institution/base_institution_page.html
- frontend/user/left_nav.html
<p><b>Feature/Bug description:</b> When the picture on user profile or institution profile is .png the background looks strange.</p>
<p><b>Solution:</b> Adding a white background to display the picture.</p>
> Adding white background in picture of user profile and institution profile

- frontend/institution/configInstDirective.js
- frontend/institution/create_inst_form.html
Adding load progress in institution's creation
</p>
I've created a flag in the controller that controls when to show the load-progress directive and added the directive in the html.
</p>
> Adding load progress in institution's creation

- frontend/post/postDetailsDirective.js
- frontend/post/post_details.html
<p><b>Feature/Bug description:</b> The margin of the delete delete button was wrong when the post is of the survey type.</p>
<p><b>Solution:</b> I hid an md-list and an unnecessary div and added margin to the post's action buttons.</p>
> Fix layout of action buttons of post details

- frontend/event/event_details.html
<p><b>Feature/Bug description:</b> Parts of page was out of card.</p>
<p><b>Solution:</b> Put layout-row in small displays and "flex" has only in display bigger than 600.</p>
> Fixed responsideness of event page

- frontend/post/comment.html
The comment's buttons view was broken.
</p>
I've added some css trying to fix the icons' position.
</p>
> Fix comment's buttons

- backend/handlers/like_handler.py
- backend/models/post.py
- backend/test/like_post_handler_test.py
- backend/test/post_handler_test.py
<p><b>Feature/Bug description:</b> Optimize method post to like post, comment or reply to minimize concurrency problems</p>
<p><b>Solution:</b> Isolate the transsaction only to part methods that update the datastore  and insert the flag retries=10 to try more than once on error cases </p>
> Refact method POST of  like handler

- backend/test/institution_collection_handler_test.py
- backend/test/mocks.py
<p><b>Feature/Bug description:</b> Don't has tests to institution_collecion_handler.</p>
<p><b>Solution:</b> Creating test to get request of institution_collection_handler.</p>
> Creating test to institution_collecion_handler

- frontend/survey/surveyDetailsDirective.js
- frontend/survey/survey_details.html
- frontend/test/specs/surveyDetailsDirectiveSpec.js
<p><b>Feature/Bug description:</b> The result of survey is only displayed in case of user is author or has voted in survey.</p>
<p><b>Solution:</b> Now the user can see the result of survey after deadline.</p>
> Display the result of a survey after deadline

- frontend/post/pdfViewDirective.js
- frontend/post/pdf_view.html
<p><b>Feature/Bug description:</b> Before save the post with pdf the click are enable to open pdf. When open the pdf an error happen in console.</p>
<p><b>Solution:</b> Removing the clickable class before save the post and adding verification in controller too.</p>
> Fix pdf opening bug

- backend/models/post.py
- frontend/post/postDetailsDirective.js
- frontend/utils/messageService.js
<p><b>Feature/Bug description:</b> When a user like a comment that was deleted the error message that show was wrong.</p>
<p><b>Solution:</b> Added verification in backend that return error if comment was deleted, the error is process in frontend.</p>
> Fix error message when like deleted comment

- backend/models/event.py
- frontend/event/eventController.js
- frontend/event/eventDetailsDirective.js
<p><b>Feature/Bug description:</b> Any modifications made to the event through the edit event dialog is modified to the page, even if the user cancels the edition. This error is only in frontend, the changes weren't saved in backend.</p>
<p><b>Solution:</b> Passed the copy of event to edit controller, and when user save the modifies is returned the new object.</p>
> Fix event changes in the edit dialog that directly modified the event page.

- frontend/error/error.html
- frontend/error/errorController.js
<p><b>Feature/Bug description:</b> The button "Reportar erro" does nothing.</p>
<p><b>Solution:</b> Added redirect to the support page of cis in this button.</p>
> Redirect button from error page to report page

- frontend/utils/messageService.js
<p><b>Feature/Bug description:</b> When user comment the post that was deleted show message in english.</p>
<p><b>Solution:</b> Translate message, added in MessageService. </p>
> Fix error message when user comments the post that was deleted.

- ecis
<p><b>Feature/Bug description:</b> When utilizing main script, it's making changes to the config files,
that is appearing in the git status, and that can't be committed.</p>
<p><b>Solution:</b> Execute the git command `git update-index --skip-worktree` to skip changes to the config files.
Also, improved the steps to deploy the application to development and production environments. Now it's possible to type the version to deploy, or just type Enter to use the latest version, as well as, select the application to deploy under the list of options or type a different one.</p>
> Main Script enhancement

- frontend/post/postDetailsDirective.js
The commentCtrl.saving variable, that is one of the "controllers" of disableButton function, wasn't being set where It should.
</p>
I've manipulated the variable before and after the requests. 
</p>
> Fix possible multiple clicks on like comment button

- frontend/institution/configInstDirective.js
- frontend/institution/submit_form.html
- frontend/utils/submitFormListenerService.js
<p><b>Feature/Bug description:</b> Previously, when the user alters some data in the institution form and clicks to go to another page, he is not warned that the alterations were not saved.</p>
<p><b>Solution:</b> Now, a dialog appear and asks if the user is sure that he wants to leave the form without saving the changes</p>
> Request user confirmation to leave the Institution editing page without saving changes.

- frontend/auth/configProfileController.js
- frontend/auth/config_profile.html
<p><b>Feature/Bug description:</b> When the user leaves the edit page while editing the profile, he loses the changes and he is not warned about it. </p>
<p><b>Solution:</b> Added directive that confirm this action.</p>
> Request user confirmation to leave the profile editing page without saving changes.

- frontend/institution/create_inst_form.html
**Feature/Bug description:** When the user answers the create institution form he can't put a photo.
**Solution:** Fix condition of ng-if.
> Fix show photo input in create institution form

- frontend/search/search.html
- frontend/search/searchController.js
**Feature/Bug description:** When searching for an institution and select any filter not exist the option for clear it.
**Solution:** Create the button in HTML and the function in SearchController.
> Create button that clear the search filters

- ecis
**Feature/Bug description:** When trying to deploy to the default version, the script doesn't configure the firebase on the backend, causing malfunction. That is occurring because the configuration was done inside the if statement that treats only deploy to specific versions.
**Solution:** Move the configuration command to outside the if statement to be done to both deploys. In addition, I've created a function to catch errors, preventing the script to continue the execution, or printing a log message (passed as a parameter). 
> Fix script to deploy on default version

- frontend/post/postDetailsDirective.js
- frontend/post/post_details.html
- frontend/styles/custom.css
- frontend/survey/surveyDetailsDirective.js
- frontend/survey/survey_details.html
**Feature/Bug description:** When reload the shared survey post the percentages aren't calculated again.
**Solution:** Create the function getPercentage that if the percentage that wasn't calculated call the function that calculates.
> Fix shared survey post when reload the post

- .gitignore
- backend/utils.py
- ecis
- frontend/app.js
- frontend/auth/authService.js
- frontend/home/home.html
- frontend/main/main.html
- frontend/main/mainController.js
- support/auth/authService.js
**Feature/Bug description:** The user of the production environment has an issue that the frontend doesn't know when the application receives a new version, keeping the users using olde versions, causing bugs and conflicts with a different backend version.
**Solution:** Create an alert that is displayed to the user when a new version is available. That feature was possible through a version synchronization between the frontend and the backend, via an HTTP header, called `app_version`, that is mounted on the server, supplied by a static file created by the script right before to deploy or run the app.
That header is set on Utils.py, under the function json_response, with the following line:
self.response.headers['APP_VERSION'] = APP_VERSION
The APP_VERSION variable comes from the file …
> Alert the user of new version available

- frontend/requests/request_invitation_dialog.html
The request invitation button's color was out of pattern.
**Solution:** 
I've removed md-warn class and set the color using md-colors.
> Fix request invitation button's color

- frontend/invites/accept_invite.html
Changing the accept invite button from "ENTRAR" to "POSSUO CONTA" to avoid misunderstanding.
**Solution:**
Just change the message inside the button.
> Fix the accept invite button

- frontend/post/postDetailsDirective.js
- frontend/post/post_details.html
- frontend/test/specs/postDetailsControllerSpec.js
**Feature/Bug description:**  The layout of shared survey post is the same when the survey was closed or not.
**Solution:** Changed layout according to closed survey's layout.
> Fix the layout of a closed shared survey

- backend/handlers/institution_collection_handler.py
- backend/models/institution.py
- frontend/institution/institutionCardDirective.js
- frontend/institution/institution_card.html
- frontend/requests/requestInvitationController.js
**Feature/Bug description:** On institution card, at registered institution page, it was not possible to the user to request an invitation to any of those institutions.
**Solution:** It was created a button to the user request an invitation when he is not a member.
> Request invitation button on institution card

- frontend/notification/notificationDirective.js
- frontend/notification/notificationService.js
- frontend/notification/notifications.html
- frontend/notification/notifications_page.html
- frontend/test/specs/NotificationControllerSpec.js
**Feature/Bug description:** In notification page show only notifications that weren't read by the user.
**Solution:** Get firebase component that has all notifications.
> Show all notifications in notification page

- backend/handlers/institution_collection_handler.py
- backend/handlers/institution_handler.py
- frontend/institution/institutionCardDirective.js
- frontend/institution/institution_card.html
Add the institutions' cover picture in the all institutions page.
**Solution:**
I've created a div with a fixed height and inserted the image in the style's background-image property.
> All institutions cover

- backend/handlers/post_comment_handler.py
- backend/models/post.py
- frontend/post/postDetailsDirective.js
- frontend/test/specs/commentControllerSpec.js
**Feature/Bug description:** When a user that was commented or reply comment in the post and then changed the photo or/and name the comment didn't update.
**Solution:**  When load comment, load attributes the author.
> Fix inconsistency of comment and reply comment 

- frontend/institution/base_institution_page.html
- frontend/institution/institutionController.js
**Feature/Bug description:** The uploading the image has a delay. While this, the user doesn't have any return while waiting for the new cover.
**Solution:** Add loading circle directive.
> Add loading circle while the institution cover is upload

- frontend/test/specs/homeControllerSpec.js
**Feature/Bug description:** The test loadMorePosts in Hone Controller test is broken on master repository, the error is : permission_denied at /notifications/undefined: Client doesn't have permission to access the desired data.
**Solution:** The main controller function, has a request for NotificationService, and this call is not mocked on test.
**TODO/FIXME:**
> Fix Home Controller Test

- frontend/auth/login.html
- frontend/auth/signup.html
- frontend/test/specs/userInactiveControllerSpec.js
- frontend/user/userInactiveController.js
- frontend/user/user_inactive.html
**Feature/Bug description:** The occult functionality to be a member of CIS now working fine.
**Solution:** Implementing the TO DO's in user_inactive page, removing verifications to occult the functionality and improving it to work fine.
Username appears in the request list. Not more 'Unknow'.
The system notifies by email the approbation.
> Request to be a member of CIS

- frontend/institution/institutionController.js
- frontend/test/specs/homeControllerSpec.js
**Feature/Bug description:** When loading the institution page the following console error is showed:
"Cannot read property 'cover_photo' of null".
**Solution:** Verifying if the institution is defined before reading the property 'cover_photo'.
> Fix console error in read of property 'cover_photo'

- frontend/institution/base_institution_page.html
- frontend/institution/followers.html
- frontend/institution/institutionController.js
- frontend/institution/members.html
- frontend/institution/registration_data.html
- frontend/institution/timeline_inst.html
- frontend/styles/custom.css
**Feature/Bug description:** When the page is scrolled down, the bigger cover is replaced by a smaller one.
**Chrome 01/02**
**Chrome 02/02**
**Firefox**
**Mobile**
> Change the institution cover when the page is scrolled

- frontend/institution/institution_card.html
- frontend/styles/custom.css
**Feature/Bug description:** At registered institutions page, it was added the shadow-box property to the institution card cover.
> Add shadow to institution card cover

- frontend/institution/base_institution_page.html
- frontend/test/specs/authServiceSpec.js
**Feature/Bug description:** At institution page, it was added the shadow-box property to the institution image and cover.
**Shadow around cover**
**Shadow around institution image**
> Add shadow effect to institution image and cover, at institution page

- frontend/institution/managementMembersController.js
- frontend/institution/management_members.html
- frontend/test/specs/managementMembersControllerSpec.js
- frontend/test/specs/selectEmailsControllerSpec.js
**Feature/Bug description:** The user can place several emails, even if the email is from a user who is already a member or requested or sent an invite to this email or it has been repeated.
**Solution:** Used the method removePendingAndMembersEmails that filter the right emails and verify if the emails can be sent.
> Fix send several emails

- frontend/institution/institutionCardDirective.js
- frontend/institution/institution_card.html
**Feature/Bug description:** The institution card header height was varying depending on the size of the institution name and/or its address.
**Solution:** The institution name and address were limited.
**Chrome**
**Firefox**
**Mobile**
> Fix institution card header

- backend/handlers/institution_request_handler.py
- frontend/institution/configInstDirective.js
- frontend/institution/create_inst_form.html
- frontend/invites/invite_institution.html
- frontend/main/mainController.js
- frontend/requests/requestInvitationService.js
- frontend/test/specs/mainControllerSpec.js
- frontend/user/left_nav.html
- frontend/user/userInactiveController.js
- frontend/user/user_inactive.html
**Feature/Bug description:** When the user requests to be a member of CIS and not found your institution he doesn't have the option to create the institution.
**Solution:** Enabling to user request create your own institution.
> Request to be a member and admin of new institution

- frontend/requests/requestInstitutionProcessingController.js
- frontend/requests/requestProcessingController.js
- frontend/requests/request_processing.html
**Feature/Bug description:** When the user clicks on invitation notification that was used show quickly the dialog and toast that invite has been resolved by the user.
**Solution:** Show the message in the dialog.
> Show message when click message 

- frontend/event/event_dialog.html
Hide the steps' text in small screens
**Solution:**
Manipulation of hide and show
> Hiding event steps' text

- backend/models/request_institution.py
- backend/models/request_user.py
The emails link when a request was accepted were broken.
**Solution:**
I've changed the links.
> Fix accept request email link

- frontend/institution/create_inst_form.html
**Feature/Bug description:** In the second step of institution creation didn't show the message of empty inputs.
**Solution:** Added ng-submit in HTML form.
> Show message of required input in create inst form

- frontend/institution/base_institution_page.html
- frontend/institution/institutionController.js
**Feature/Bug description:** The floating cover in institution page does not display correctly in medium screens.
**Solution:** Changing the HTML to display the floating cover correct in all screen sizes.
Working in Firefox, smartphones, and tablets.
> Fix floating cover in institution page

- frontend/requests/requestInstitutionProcessingController.js
- frontend/requests/request_institution_processing.html
The request institution dialog was showing even when the request was accepted or rejected.
**Solution:**
I've created a validation logic.
> Fix request institution dialog

- frontend/institution/base_institution_page.html
- frontend/institution/institutionController.js
- frontend/styles/custom.css
**Feature/Bug description:** The left navbar on the institution page is too far from the center of the screen.
**Solution:** Adding flex to show left navbar close from the center of the screen.
> Fix left nav on institution page

- frontend/institution/transfer_admin_dialog.html
**Feature/Bug description:** Can't select the user clicking on the text.
**Solution:** Added ng-click in the text area.
> When the user selects another user to transfer the administration, can't select clicking in the name

- backend/handlers/post_handler.py
- backend/service_messages.py
- backend/worker.py
- frontend/notification/notificationService.js
- frontend/post/post.js
- frontend/post/timelineDirective.js
Setting up an event listener that allows to update the post and remove it from the timeline when there is a deleted_post notification.
**Solution:**
I've created a event listener in timelineController that wraps the logic of delete the post from the timeline.
> Improving the deleted_post notification

- frontend/utils/messageService.js
Translate some messages that come from the backend.
**Solution:**
Add others keys and values in message's service msg object.
> Translate some messages

- frontend/requests/request_institution_processing.html
**Feature/Bug description:** Address fields appears "null" when the country is not Brasil.
**Solution:** Adding cases to show the correct address in all cases of empty fields when the country is not Brasil.
> Fix the display of address in request of institution modal

- backend/handlers/event_handler.py
- backend/models/event.py
- backend/test/event_handler_test.py
- backend/test/model_test/event_test.py
- frontend/event/event.js
- frontend/event/eventController.js
- frontend/event/event_dialog.html
- frontend/test/specs/eventDialogCtrlSpec.js
- frontend/utils/messageService.js
**Feature/Bug description:** Allow edit the event information, that are not the basic ones (e.g. title, address), after it has ended.
**Event basic informations blocked**
> Edit event after it has ended

- frontend/user/left_nav.html
The current_institution list wasn't with the custom-scrollbar.
**Solution:**
I've inserted custom-scrollbar class in the md-menu-content.
> Inserting custom-scrollbar in choose institution list

- frontend/utils/messageService.js
The message wasn't translated in the frontend
**Solution:** 
I've added the message in the messageService's object responsible for translation.
> Fix user is not allowed to send invite message

- frontend/event/eventDetailsDirective.js
- frontend/event/event_details.html
- frontend/test/specs/eventDetailsControllerSpec.js
if the event ended the same day the view would look strange
**Solution:**
I've created a function that verifies if the event end in the same day and made the view work according to this function.
> Fix event date inconsistency

- frontend/institution/create_inst_form.html
The steps' card was overtaking the fields' card in small screens.
**Solution:** 
I've added some missing flex.
> Fix create institution form

- backend/handlers/institution_collection_handler.py
- backend/models/invite.py
- backend/test/model_test/invite_institution_test.py
- backend/test/model_test/invite_test.py
- backend/test/model_test/invite_user_adm_test.py
- backend/test/model_test/invite_user_test.py
- frontend/institution/configInstDirective.js
- frontend/institution/create_inst_form.html
- frontend/institution/registration_data.html
- frontend/institution/removeInstDialog.html
- frontend/institution/submit_form.html
- frontend/invites/accept_invite.html
- frontend/invites/new_invite_page.html
- frontend/invites/process_invite_user_adm.html
The institutional_email field wasn't used in the system.
**Solution:**
I've handled with the substitution of institution.email by institution.institutional_email in some cases or the existence of the two fields in another cases.
> Fix institutional_email

- backend/handlers/invite_handler.py
- backend/handlers/invite_user_adm_handler.py
- backend/handlers/user_handler.py
- backend/utils.py
**Feature/Bug description:** The make_user method was duplicated in utils and user handler.
**Solution:** Remove the make_user from the user handler and leave only the utils.
> Refact make user on utils.py

- backend/models/institution.py
- backend/models/user.py
- backend/test/user_handler_test.py
**Feature/Bug description:** It was created tests for UserHandler.
> Create tests for user handler

- backend/models/user.py
- backend/test/model_test/user_test.py
**Feature/Bug description:** The tests of user model are out of date.
**Solution:** Updating tests using mocks and adding new tests cases.
> Improving tests to user model

- frontend/requests/requestProcessingController.js
- frontend/requests/request_processing.html
**Feature/Bug description:** It was taking a while before showing the message.
**Solution:** Used variable to show the message that invite was used.
> Show message that invite was used.

- backend/handlers/event_handler.py
- backend/test/event_handler_test.py
- frontend/event/eventDetailsDirective.js
- frontend/event/event_details.html
**Feature/Bug description:** In frontend didn't show the option delete event when the user is the admin, and in backend didn't verify using permissions.
**Solution:** Added validations.
> Fix delete event

- frontend/institution/base_institution_page.html
- frontend/institution/institutionController.js
- frontend/styles/custom.css
On medium width screen, at members view, the floating cover was not being shown properly when scrolling the page down. And the left menu was overlapping the posts.
**Bug floating cover**
**Bug left menu**
**Solution:** It was changed the way the floating cover becomes visible. And it was created a function to calculate the appropriate left menu width depending on the screen width.
**Medium width screen**
**Large width screen**
**Extra large width screen**
**Mobile**
> Fix bug on floating cover and on left menu, at medium size screens

- backend/handlers/request_handler.py
- backend/models/request_institution.py
- backend/test/institution_request_collection_handler_test.py
- backend/utils.py
**Feature/Bug description:**  When the user requests to create institution the system looking for "Complexo Indústrial da Saúde" but this institution it isn't the super-institution. 
**Solution:** Change the super-institution to Departamento do Complexo Industrial e Inovação em Saúde and the super user to the deciis administrator.
**TODO/FIXME:** Refact the function to get the DECIIS Institution, making a get for the institution with that field trusted is equal to true. And certificate that DECIIS is the unique institution trusted in the system.
> Fix get super institution

- frontend/auth/configProfileController.js
**Feature/Bug description:** An error is thrown when the user like posts or change color of institutions and edit profile
**Solution:** Adding a filter in the patch to permit only specific fields.
> Fix edit user profile

- frontend/notification/notificationDirective.js
The notification was sending the user to different states even if it was read already.
**Solution:**
I've verified if the notification has already been read in goTo method.
> Fix redirect the user to another state with the notification

- frontend/app.js
- frontend/institution/institutionController.js
- frontend/test/specs/institutionControllerSpec.js
The posts array was undefined in the eventCtrl.
**Solution:**
I've added the params property to the state's object.
> Fix share event in institution's page

- frontend/requests/requestInstitutionProcessingController.js
- frontend/requests/request_institution_processing.html
**Feature/Bug description:** The modal of institution request to be part of CIS are out of date with the current design.
**Solution:** Redesigning to be according to the new design.
> Redesign the modal of request institution

- backend/admin.py
**Feature/Bug description:** Change the reset admin to create an environment similar to the production environment. Refactoring required because of the special treatment for the DECIIS institution that in the development environment was represented by the institution CIS.
**Solution:** Change the admin reset to create the institutions below:
- Ministério da Saúde
Admin: admin - platataformavirtualcis...
Followers: mayza, maiana, luiz, raoni, ruan, tiago, admin, other_admin
Members:  admin - platataformavirtualcis...
- Departamento do Complexo Industrial e Inovação em Saúde (TRUSTED = TRUE)
Admin: admin - platataformavirtualcis...
Followers: mayza, maiana, luiz, raoni, ruan, tiago, admin, other_admin
Members:  admin - platataformavirtualcis...
- Complexo Industrial da Saude
Admin: …
> Refact admin reset

- backend/handlers/institution_handler.py
- backend/worker.py
- frontend/home/homeController.js
- frontend/notification/notificationDirective.js
- frontend/test/specs/userSpec.js
- frontend/user/user.js
The function wasn't handling with the hierarchy
**Solution:**
I've adapted the notification's entity to wrap the remove_hierarchy information and used that to change to the right institution when the its value is true. 
> Fix goToDifferentInstitution function

- frontend/invites/new_invite_page.html
The label and the title were to close.
**Solution:** 
I've added a margin-top to the user's information.
> Fix accept member invite card

- frontend/event/eventController.js
- frontend/event/eventDetailsDirective.js
- frontend/event/event_details.html
- frontend/event/event_dialog.html
- frontend/styles/custom.css
**Feature/Bug description:** The field 'Número' in modal to create an event is required and the option to can edit the event are disabled.
**Solution:** Making the field 'Número' optative and fixing the flag to enable the option to edit event.
> Fix the number of address in create of event

- frontend/post/postDetailsDirective.js
**Feature/Bug description:** Increase the size of the post to resolve one production problem.
**Solution:** It is a temporary solution as we do not solve the real problem.
**TODO/FIXME:** Not break links in the timeline view
> Increase the limit of post characters

- backend/handlers/institution_handler.py
- frontend/invites/inviteInstHierarchieController.js
The parentLinkStatus was checking the link's status with a wrong approach.
**Solution:**
I've checked the status looking at the parent's side instead of the child's one.
> Fixing the parentLinkStatus method

- backend/handlers/like_handler.py
- backend/handlers/post_comment_handler.py
- backend/models/post.py
- backend/test/like_comment_handler_test.py
- backend/test/like_reply_handler_test.py
- backend/test/reply_comment_handler_test.py
- frontend/post/postDetailsDirective.js
**Feature/Bug description:** When multiple users commented on the same post at the same time competition error occurs.
**Solution:**  Added ndb.transaction in internal scope to try to resolve this.
**TODO/FIXME:**Create deslike_comment method and replace ndb.transactional to internal scopes.
> Add ndb.transactional in add comment method of post

- frontend/invites/inviteInstHierarchieController.js
- frontend/test/inviteInstHierarchieControllerSpec.js
There was no test to inviteInstitutionHierarchieController
**Solution:**
Make the tests.
> Test invite institution hierarchie controller

- frontend/invites/existing_institutions.html
**Feature/Bug description:** The model was with the old layout
**Solution:** Change layout according to the pattern of the project, but isn't new layout.
> Change layout of invite ehierarchie existing institution model

- backend/handlers/event_handler.py
- backend/test/event_handler_test.py
In the previous version the admin could edit the event.
**Solution:**
I've checked it with permissions.
> Fix event handler's patch method

- backend/handlers/request_handler.py
- backend/models/invite.py
- backend/models/request_user.py
- backend/test/request_handler_test.py
- frontend/notification/notificationDirective.js
- frontend/notification/notificationService.js
- frontend/notification/notifications_page.html
**Feature/Bug description:** When admin rejects the request to be a member of the institution, the user didn't receive any return. 
**Solution:** Send notification.
> Send notification when you reject the request to become a member of an institution.

- frontend/test/specs/institutionSpec.js
**Feature/Bug description:** There is has no tests to institution model in front-end.
**Solution:** Adding tests to institution model in front-end.
> Test institution model

- frontend/invites/suggestInstitutionController.js
I've miss spelled some variables in a previous pull request.
**Solution:** 
Fix the variables' names.
> Fix variables' name in suggestExistingInstCtrl

- backend/models/institution.py
- backend/models/user.py
- backend/test/institution_children_collection_request_handler_test.py
- backend/test/institution_handler_test.py
- backend/test/institution_parent_collection_request_handler_test.py
- backend/test/invite_user_adm_handler_test.py
- backend/test/model_test/invite_user_adm_test.py
- backend/test/model_test/user_test.py
- backend/test/user_handler_test.py
**Feature/Bug description:** The two functions don't verify if the user is a member of an institution involved in the context which they are called.
**Solution:** Adding verification before making changes if the user is a member of the institution.
> Refactoring the set_admin function in institution.py and add_institution_admin in user.py

- backend/handlers/institution_request_handler.py
- backend/models/institution.py
- backend/models/user.py
**Feature/Bug description:** In some lines of code the members are added in an institution using "append" not the function "add_member".
**Solution:** Changing this lines to use the function "add_member" to make the code more correct.
> Refactoring ways to add members in institution

- frontend/institution/registration_data.html
The directive has been misspelled
**Solution:**
I've fixed the directive's call
> Fix load-circle in registration-data page

- frontend/invites/inviteInstHierarchieController.js
- frontend/invites/invite_institution_hierarchie.html
The button wasn't disabled while the submission.
**Solution:**
I've passed ng-disabled  to the button and controlled it by a flag. 
> Fix send invite button in invite institution hierarchy

- backend/handlers/like_handler.py
The ndb.transaction was decorating all the delete method.
**Solution:**
I've moved the decorator to a more internal scope.
> Fix dislike concurrency

- frontend/invites/inviteInstitutionController.js
- frontend/requests/requestProcessingController.js
- frontend/requests/request_institution_processing.html
- frontend/styles/custom.css
- frontend/test/specs/requestProcessingControllerSpec.js
**Feature/Bug description:** The card to resolve institution's request is not according to the design of the system.
**Solution:** Adding more information and changing colors and layout.
> Improving card to resolve create institution's requests

- backend/test/worker_aux_methods_test.py
- backend/worker.py
This method wasn't checking if the link was confirmed.
**Solution:**
Check if the link is confirmed before call the method again to the parent_institution.
> Fix get_all_parent_admins

- backend/models/institution.py
- backend/test/model_test/institution_test.py
This method, that is very important to the hierarchy, wasn't being tested.
**Solution:**
I've created tests to the method.
> Test verify_connection

- backend/models/institution.py
- backend/test/mocks.py
- backend/test/model_test/institution_test.py
**Feature/Bug description:** The institution model in backend has no tests for all methods.
**Solution:** Adding more tests for methods not tested yet.
> Adding tests to institution.py

- backend/admin.py
- backend/handlers/institution_request_handler.py
- backend/models/request_institution.py
- backend/send_email_hierarchy/accepted_institution_email_sender.py
- backend/templates/accepted_institution.html
It wasn't sending any specific html to notify the user that his institution has been accepted
**Solution:**
I've created the html and connected it with the application.
> Accepted institution email

- backend/handlers/institution_members_handler.py
- backend/handlers/user_institutions_handler.py
- backend/models/invite.py
- backend/models/invite_institution.py
- backend/models/invite_user.py
- backend/util/strings_pt_br.py
- backend/worker.py
**Feature/Bug description:** Extracted subject string in Portuguese to a module that will be responsible for the translation
**TODO/FIXME:** Depending on how this module will grow in the future, it will be necessary to rename it, because the current name is too generic.
> Extract subject strings

- frontend/institution/managementMembersController.js
- frontend/institution/management_members.html
**Feature/Bug description:** In page to manage members the modal to resolve requests is not opening.
**Solution:** Updating parameters to the generic modal of requests.
> Fix the modal to resolve members request

- backend/models/request_institution_children.py
- backend/models/request_institution_parent.py
- backend/send_email_hierarchy/request_link_email_sender.py
- backend/templates/request_link_email.html
- backend/test/mocks.py
- backend/util/strings_pt_br.py
It wasn't sending a html when the institution received a new link request.
**Solution:**
I've created the email and connected it to the application.
> Create request new institution link email

- backend/templates/accepted_institution.html
- backend/templates/invite_institution_email.html
- backend/templates/invite_user.html
The buttons weren't clickable in hotmail because <a> was inside the button.
**Solution:**
I've fixed the html moving the position of some tags like <a> and <button>.
> Fix emails' html buttons

- backend/test/model_test/invite_institution_children_test.py
There was no test to this model.
**Solution:**
I've created the tests.
> Test invite_institution_children model

- frontend/institution/institutionController.js
It was missing a function, called limitString, in institutionController.
This function was called in the html.
**Solution:**
I've created the function.
> Fix missing data in institution's page

- backend/models/request_institution.py
The body was totally wrong.
**Solution:**
I've fixed the message and the link in the body.
> Fix request_institution's send_email method

- backend/models/invite_user_adm.py
- backend/send_email_hierarchy/__init__.py
- backend/send_email_hierarchy/transfer_admin_email_sender.py
- backend/templates/transfer_admin_email.html
- backend/util/strings_pt_br.py
Send email when a transfer admin invite is sent.
**Solution:** 
I've created the html and connected it with the application.
> Create transfer admin email

- backend/handlers/user_request_collection_handler.py
The documentation wasn't according to what the method really does.
**Solution:**
I've changed the documentation trying to give a better idea about the method's purpose.
> Improving user_request_collection_handler's get documentation

- backend/handlers/institution_parent_request_collection_handler.py
There were some problems like variables out of pattern, bad documentation and missing of transaction. 
**Solution:**
I've renamed some variables and inserted a transaction scope in the post method.
> Improving institution_parent_request_collection_handler

- backend/handlers/subscribe_post_handler.py
- backend/models/post.py
Some params were out of pattern and the documentation wasn't good enough.
**Solution:*
I've renamed some params and changed the documentation.
Besides, i've moved the put operation to the post's methods.
> Improving subscribers handler

- backend/handlers/post_handler.py
**Feature/Bug description:** The parameters in methods of post_handler are out of date with the new pattern.
> Improving the parameters to indicate urlsafe

- backend/handlers/institution_children_request_collection_handler.py
**Feature/Bug description:** The parent_key is getting from body. But it is unnecessary because the parent_key is equal to institution_key, and the parameter provide the institution_key.
> Improving post of institution_children_request_collection_handler

- frontend/requests/requestProcessingController.js
- frontend/requests/request_processing.html
**Feature/Bug description:** In the case of emails or names being large, they are off the card.
**Solution:** Defined different labels according to display size.
> Fix user request dialog

- frontend/event/eventDetailsDirective.js
- frontend/test/package-lock.json
**Feature/Bug description:** The TODO in editEvent of eventDetailsController not more necessary.
> Removing unncessary TODO

- backend/test/mocks.py
- backend/test/post_handler_test.py
**Feature/Bug description:** The post_handler has no test to get method and the initModels are out of date.
**Solution:** Adding models with mocks, improving create_post of mocks and adding test to get method.
> Test get of post handler

- backend/handlers/__init__.py
- backend/handlers/invite_collection_handler.py
- backend/handlers/invite_institution_collection_handler.py
- backend/main.py
- backend/test/invite_institution_collection_handler_test.py
- frontend/invites/inviteService.js
- frontend/test/specs/inviteInstitutionControllerSpec.js
- frontend/test/specs/inviteServiceSpec.js
- frontend/test/specs/suggestInstitutionControllerSpec.js
The handler's name was out of our pattern and the invite_collection_handler's get method should be there.
**Solution:**
I've renamed the file and the handler and moved the get to there.
> Improving invite_institution_handler

- backend/handlers/institution_request_handler.py
- backend/test/institution_request_handler_test.py
**Feature/Bug description:** In InstitutionRequestHandler exist the method check_permission that personalize error message according to the method.
**Solution:** Removed this method.
> Removed method unnecessary method

- backend/handlers/institution_handler.py
- frontend/invites/inviteInstHierarchieController.js
- frontend/invites/invite_institution_hierarchie.html
- frontend/test/inviteInstHierarchieControllerSpec.js
> Fix institution hierarchie page

- backend/service_messages.py
- backend/test/service_messages_test.py
- backend/worker.py
This method was used in nowhere
**Solution:**
I've removed it and its test.
> Removing send_message_email

- frontend/invites/new_invite_page.html
- frontend/styles/custom.css
The layout-align property was set wrong. Besides, it wasn't responsive for small screens.
**Solution:**
I've inserted the flexible property, corrected the layout-align value and add some css to fix the max-width of the card.
> Fixing new_invite_page.html

- backend/handlers/user_institutions_handler.py
- backend/models/user.py
- frontend/notification/notificationDirective.js
- frontend/notification/notificationService.js
**Feature/Bug description:** When the user left the institution, the administrator of the institution didn
't receive any notification.
**Solution:** Create notification.
> Create notification when user left the institution

- backend/handlers/vote_handler.py
- backend/models/survey_post.py
- backend/test/model_test/survey_post_test.py
- backend/test/vote_handler_test.py
- frontend/survey/surveyDetailsDirective.js
- frontend/utils/messageService.js
There was no verification that checked if the user had already voted in a survey.
**Solution:**
I've created a voters array, in survey's model, that stores all the users who has voted in the survey.
Thus, the handler checks if the user who is trying to vote hasn't voted yet in that survey. If so, an exception is raised blocking him to continue.
> Fix survey's multiple votes

- frontend/event/event_dialog.html
**Feature/Bug description:** The return button is not centralized and the dialog appears on the top side of the screen.
**Solution:** Centralizing the button and make dialog appears centralized too.
**Printscreen of Google Chrome**
**Printscreen of Mozilla Firefox**
> Fix the return button in the dialog of creation of event 

- frontend/event/eventService.js
- frontend/test/specs/eventServiceSpec.js
**Feature/Bug description:** There no has tests to EventService.js
**Solution:** Creating tests to EventService.js functions.
> Test EventService

- frontend/test/specs/userServiceSpec.js
**Feature/Bug description:** There no has tests to userService.js
**Solution:** Creating tests to userService.js functions.
> Creating tests to userService.js

- frontend/auth/authService.js
- frontend/test/specs/notificationServiceSpec.js
**Feature/Bug description:** Didn't exist test notificationService.
**Solution:** Create test.
> Create test of notificationService

- frontend/requests/requestProcessingController.js
- frontend/requests/request_processing.html
**Feature/Bug description:** The Accept Request dialog message was incorrect.
**Solution:** I have added a function that checks whether the request is of type user, if yes add "A platform user" in the message, otherwise adds "An institution".
> Fix message of accept request dialog

- frontend/styles/custom.css
- frontend/survey/save_survey.html
- frontend/survey/surveyDirective.js
**Feature/Bug description:** The creation of survey in small screens are broken.
**Solution:** Improving buttons to display the modal of the creation of survey correctly on small screens.
Adjusting to show correctly on normal screens too.
> Fix the creation of survey in small screens

- backend/handlers/post_handler.py
- backend/models/post.py
- backend/test/post_handler_test.py
- frontend/post/postDirective.js
- frontend/post/post_details.html
- frontend/utils/messageService.js
**Feature/Bug description:** The user can edit post that institution was deleted or the post was deleted.
**Solution:** Create method that verify if user can edit post.
> Fix edit post.

- frontend/notification/notificationDirective.js
- frontend/test/specs/NotificationControllerSpec.js
**Feature/Bug description:** The function goTo() in notificationDirective.js has no test and recently your behavior are changed.
**Solution:** Adding test to coverage and guarantee test when there changes in the behavior of this function.
> Adding test to the new behavior of goTo function in notificationDirective.js

- frontend/institution/create_inst_form.html
- frontend/user/user_inactive.html
**Feature/Bug description:** The message when the idle user requests an invitation is missing an accent, and the magnifying glass icon next to the Search Institution field when the user is inactive has no action.
**Solution:** Add the correct message accents and give action to the search button.
> Fix message of send user request and create button to search institutions

- backend/handlers/institution_handler.py
It was checking if obj == "inactive" but it should check if obj.state == "inactive"
**Solution:**
I've fixed the verification.
> Fix institution_handler's get method

- frontend/test/specs/event/eventSpec.js
**Feature/Bug description:** The event model has no test.
**Solution:** Create event model test.
> Create event model test

- frontend/test/specs/post/postPageControllerSpec.js
Creation of tests for PostPageController.
**Solution:**
Create the tests.
> Create tests for PostPageController

- frontend/invites/acceptInviteController.js
- frontend/test/specs/invites/acceptInviteControllerSpec.js
There were no tests to acceptInviteController.
**Solution:**
Create the tests.
> Testing acceptInviteController

- frontend/invites/newInviteController.js
- frontend/test/specs/invites/newInviteControllerSpec.js
When the user accept the invite a message informing that the institution is inactive is raised but he stays stuck in there.
**Solution:**
I've redirected him in the error function.
> Fix accept invite from an inactive institution

- frontend/institution/allInstitutionsController.js
- frontend/test/karma.conf.js
- frontend/test/specs/institution/allInstitutionsControllerSpec.js
**Feature/Bug description:** The controller allInstitutionsController has no tests.
**Solution:** create tests.
> Create all institutions controller test

- backend/models/user.py
- frontend/institution/configInstDirective.js
- frontend/user/user.js
Set profile's default color to avoid unexpected behavior when changing it automatically.
**Solution:**
I've removed the color's random selection process and set the default color to teal.
In the image above, I've changed the color of the SPLAB and Certbio
> Set profile's default color

- frontend/invites/process_invite_user_adm.html
- frontend/requests/analyseHierarchyRequestController.js
- frontend/requests/analyse_hierarchy_request_dialog.html
- frontend/requests/requestDialogService.js
- frontend/requests/requestInvitationController.js
- frontend/requests/requestProcessingController.js
- frontend/test/specs/request/analyseHierarchyRequestControllerSpec.js
- frontend/test/specs/request/requestProcessingControllerSpec.js
**Feature/Bug description:** In parent requests has no feedback to wait for the processing of admin permissions of hierarchy.
**Solution:** Refactoring duplicated code and tests and adding new behavior to show the message in analyseHierarchyRequestController.
> Adding message to wait the processing of permissions

- backend/worker.py
- frontend/notification/notificationDirective.js
- frontend/notification/notificationMessageCreatorService.js
- frontend/test/specs/notification/notificationControllerSpec.js
- frontend/user/userService.js
**Feature/Bug description:** Updating user in client side when the remove permissions are finished.
**Solution:** 
> Updating user in remove permissions

- frontend/test/specs/institution/institutionCardControllerSpec.js
There were no tests to this controller.
**Solution:**
Create the tests.
> Test institution card controller

- frontend/test/specs/invites/removeChildControllerSpec.js
There were no tests for this controller.
**Solution:**
Creation of the tests.
> Test removeChildController

- frontend/invites/invite.js
- frontend/test/specs/invites/inviteSpec.js
**Feature/Bug description:** Add tests for invite model, on client.
> Add new tests to Invite model

- frontend/test/specs/user/userSpec.js
There were some functions without tests.
**Solution:**
Create the missing tests
> Finishing user tests

- frontend/institution/managementMembersController.js
- frontend/institution/selectEmailsController.js
- frontend/test/specs/institution/selectEmailsControllerSpec.js
**Feature/Bug description:** A reference to ManagementMembersController was being used on SelectEmailsController to call some functions.
**Solution:** Instead of passing the reference of ManagementMembersController to the selectEmailsDialog, I set to pass the reference of the functions that are going to be used. 
> Refact SelectEmailsController

- frontend/utils/utils.js
**Feature/Bug description:** Some functions from utils were with no docstring
**Solution:** It was added docstring to all functions
> Add missing docstrings to util's functions

- backend/models/user.py
- backend/test/worker_handlers_tests/worker_aux_methods_test.py
- backend/worker.py
**Feature/Bug description:** The single test of the suit of worker aux tests  was not being executed because its name did not begin with 'test_'
**Solution:** I renamed that test and added new ones for all the other aux functions. 
> Fix worker aux functions test

- frontend/test/specs/pdf/pdfControllerSpec.js
**Feature/Bug description:** Has no tests to pdfViewDirective.js
**Solution:** Creating tests to functions of pdfViewDirective.js
> Test pdf view directive

- support/auth/userService.js
**Feature/Bug description:** The support service was not working because of the HttpService that does not exist in this service.
**Solution:** Change the HttpService to $http.
> Change HttpService to $http  in UserService

- frontend/invites/new_invite_page.html
> Fix answer later button

- frontend/imageUpload/imageService.js
- frontend/pdfUpload/pdfService.js
- frontend/test/specs/imageUpload/imageServiceSpec.js
**Feature/Bug description:** Due to firebase upgrade, uploading of images and PDFs was not working.
**Solution:** Update the way pictures and pdf are sent to the firebase.
> Fix upload images and pdf

- .gitignore
- app.yaml
- backend/backend.yaml
- backend/worker.yaml
- ecis
- frontend/config.js
- frontend/frontend.yaml
- frontend/main/mainController.js
- frontend/sw.js
- landing/config.js
- landing/index.html
- landing/main.html
- landing/mainController.js
- support/config.js
- support/support.yaml
**Feature/Bug description:** The script to run application server is out of date
**Solution:** Update script
> Fix script to run application server

- frontend/index.html
- landing/index.html
- support/index.html
Update link of angular fire lib.
**Solution:** 
> updating angularfire lib link

- frontend/event/event_details.html
- frontend/index.html
- landing/index.html
- support/index.html
**Feature/Bug description:** The flexbox was wrong added in a desktop screens.
**Solution:** Adding a flexbox in the necessary divs.
> Fixing the flexbox of event page

- frontend/user/config-profile.css
- frontend/user/config_profile.html
**Feature/Bug description:**  The "layout-row" and "layout-column" classes were overwriting the design material class of other files, causing layout problems
**Solution:** The unused class was removed and renamed the class that was being used.
> Fixed Class CSS

- ecis
- frontend/sw.js
Old version caches wasn't being removed from memory.
**Solution:** 
Made cache_sufix change with the app_version, so that the browser is able to detect file change in the sw.js. And added a "clearCache" function, that deletes old caches versions.
> Removed old version caches

- frontend/index.html
Updating firebase package import at index html.
> Update firebase package

- frontend/user/config-profile.css
- frontend/user/config_profile.html
**Feature/Bug description:** In config_user view the institution_name and acronym was in the same line.
**Solution:** Added layout column
> Fix layout of config_user view

- frontend/institution/base_institution_page.html
**Feature/Bug description:** The button to change the cover photo of the institution does not appear on small screens.
**Solution:** Remove the hide-xs directive from the change institutional cover button.
> Fix change cover photo button in small screen

- frontend/event/event_dialog.html
- frontend/styles/custom.css
**Feature/Bug description:** The status bar of the Create Event dialog was broken on medium screens.
**Solution:** Adjust the size of the bar according to the size of the screen.
> Fix status bar of create event dialog

- frontend/home/post_dialog.html
- frontend/index.html
- frontend/post/create_post.css
- frontend/post/pdf_view.html
- frontend/post/postDirective.js
- frontend/post/save_post.html
- frontend/styles/custom.css
- frontend/survey/save_survey.html
- frontend/survey/survey.css
**Feature/Bug description:** The creation of post is not responsive. PDF files with long title overflow the container and the thumbnails of pictures are in the left side.
**Solution:** Making responsive. Fix the PDF file with long titles and centralizing the thumbnails of pictures. Also, improving the survey creation in small screens.
> Responsive creation of post

- frontend/index.html
- frontend/user/edit_profile.css
- frontend/user/edit_profile.html
**Feature/Bug description:** The dialog was broken.
**Solution:** Redesign the page and added button to close dialog.
> Redesign dialog profile

- frontend/manifest.json
**Feature/Bug description:** The background color was the same that the icon color.
**Solution:** Changed color to teal-900 and removed the image with size 64px.
> Fix background color of splash screen

- backend/test/model_test/event_test.py
Event create test was using fixed date, which was today (20/10/2018).
Change the fixed date to a dinamic one.
> Fixed event test

- Jenkinsfile
**Feature/Bug description:** The current image of Jenkins is very outdated.
**Solution:** Create a new image as all the updated plugins.
> Create a new Jenkins image

- Jenkinsfile
- ecis
**Feature/Bug description:** The frontend tests were not running through the ecis script as the backend.
**Solution:** Refactor the script and Jenkinsfile so that the frontend tests are executed by the ecis script.
> Refact jenkins frontend tests

- frontend/frontend.yaml
- frontend/sw.js
**Feature/Bug description:** When entering the application and opening the element inspector, an error appears in the console informing that workbox could not connect with the indexdb.
**Solution:** Update worbox version.
> Fix workbox communication error

- frontend/auth/authService.js
- frontend/auth/loginController.js
**Feature/Bug description:** When trying to enter the system, if the user misses the password, the page is reloaded.
**Solution:** Send exception if the password is wrong.
> Fix reload page when user place incorrect password

- support/index.html
Angular Fire link was incorrect.
Modify link.
> Hotfix angular fire link

- frontend/post/create_post.css
- frontend/post/postDirective.js
- frontend/post/save_post_mobile.html
- frontend/survey/save_survey_mobile.html
- frontend/survey/survey.css
- frontend/survey/surveyDirective.js
**Feature/Bug description:** Redesigning the creation of a survey to mobile devices.
**Solution:** 
> Survey mobile

- frontend/index.html
CSS File was deleted but its reference was not removed from index.html
**Solution:** 
Remove link tag to css file.
> Fix not found css

- frontend/post/pdf_view.css
- frontend/post/save_post_mobile.html
**Feature/Bug description:** The survey button is not disabled when has a media in a common post.
**Solution:** Adding disabled parameter in the button of a survey post.
> Fix post disabled buttons

- frontend/app.js
- frontend/comment/comment.component.js
- frontend/comment/comment.css
- frontend/comment/comment.html
- frontend/post/postDetailsDirective.js
- frontend/post/post_details.html
**Feature/Bug description:** Adapt the layout of the post comments to the new version created by the design.
**Solution:** Using ccs3 with grid I created the new layout.
> Change layout of post comment

- frontend/app.js
- frontend/notification/notificationController.js
- frontend/notification/notificationService.js
- frontend/test/specs/notification/notificationControllerSpec.js
- frontend/test/specs/notification/notificationServiceSpec.js
- frontend/test/specs/utils/utilsSpec.js
- frontend/utils/utils.js
**Feature/Bug description:** The unread notifications array was in Notification Controller, so when in page notification the user marks the notification like 'read' the unread notifications of the button isn't updated.
**Solution:** Move the array to the service, so it should be the same on the notification page and the notification button.
> Move unread notifications to service

- frontend/auth/authService.js
- frontend/notification/pushNotificationService.js
- frontend/test/specs/notification/pushNotificationServiceSpec.js
Application cycle was not waiting the user response to the request permission at first time. 
Modified logic to wait for it.
> Modified logic to request push notification permission

- frontend/notification/pushNotificationService.js
When login with desktop, this method does not return a promise.
Return promise.
> fix bug when login in desktop

- frontend/app.js
- frontend/index.html
- frontend/notification/notificationController.js
- frontend/notification/notificationList.component.js
- frontend/notification/notification_list_mobile.css
- frontend/notification/notifications_list_mobile.html
- frontend/notification/notifications_page.html
- frontend/test/karma.conf.js
- frontend/test/specs/utils/utilsSpec.js
- frontend/utils/utils.js
The notification's page on mobiles wasn't the way the designer expected.
**Solution:**
Construct the page using layout-grid.
> Redesign notification mobile page

- frontend/notification/notifications_list_mobile.html
**Feature/Bug description:** In mobile devices, notifications have no action
**Solution:** add ng-click in notifications_list_mobile
> Fix notification action

- frontend/event/event.css
- frontend/event/event_details_small_page.html
**Feature/Bug description:** The edit events button was above the bottom action bar.
**Solution:** Fix the position of it so it does not overlap the bar.
> Fix edit button in event page

- frontend/styles/custom.css
- frontend/survey/survey.css
- frontend/survey/survey_details.html
> Revert "Fix view of survey"

- frontend/app.js
- frontend/index.html
- frontend/post/deletedPost.component.js
- frontend/post/deleted_post.html
- frontend/post/post_details.css
- frontend/post/post_details.html
**Feature/Bug description:** The post deleted screen on mobile devices was broken.
**Solution:** Fix view using grid layout.
> Fix removed post layout in small pages

- frontend/auth/login.css
- frontend/auth/login.html
> Fix login icons

- frontend/notification/notification_list_mobile.css
- frontend/notification/notifications_list_mobile.html
There should be two different background colors to the notifications, but there was only one.
**Solution:**
Create css' classes that handle with that.
> Fix mobile notification background color

- frontend/post/create_post.css
- frontend/post/postDirective.js
- frontend/post/save_post.html
It was missing the loading bar in post's image.
**Solution:**
Insert <md-progress-linear> and control it using a flag.
> Fix missing loading bar in post creation

- backend/admin.py
> added pedro and bruno users

- frontend/app.js
- frontend/home/post_dialog.html
- frontend/post/create_post.css
- frontend/post/save_post_mobile.html
- frontend/styles/custom.css
**Feature/Bug description:** The dialog of creating a new post on a mobile device was breaking when the keyboard appears.
**Solution:** Fix layout using CSS grid.
> Fix create post dialog

- frontend/notification/notification_button.css
- frontend/notification/notifications_button.html
**Feature/Bug description:** The number notifications was out of span.
**Solution:**  Decrease font size
> Change font size of button

- frontend/test/karma.conf.js
- frontend/test/specs/user/searchInstitutionControllerSpec.js
- frontend/test/specs/user/userInactiveControllerSpec.js
- frontend/test/specs/user/userRequestFormControllerSpec.js
- frontend/user/searchInstitution/searchInstitution.component.js
- frontend/user/userInactive/user_inactive.html
- frontend/user/userRequestForm/userRequestForm.controller.js
**Feature/Bug description:** It was created tests for:
- UserInactiveController
- SearchInstitution component controller
- UserRequestFormController
> Tests user inactive

- frontend/auth/authService.js
- frontend/sw.js
- frontend/test/specs/auth/authServiceSpec.js
**Feature/Bug description:** The system was not working offline.
**Solution:** Correct the method of loading a new token to the user, so that if there is an error in the request, return the old token.
> Fix refresh user token

- backend/handlers/event_collection_handler.py
NDB error because of query order
try to put an order for each query
> first try fix event query

- frontend/app.js
- frontend/auth/login.css
- frontend/auth/login.html
- frontend/index.html
- frontend/styles/custom.css
**Feature/Bug description:** The login page in the mobile device browsers was broken.
**Solution:** Replace the angular directives by grid layout, and adjust the size of the components.
> Fix login view

- frontend/institution/management_institution.css
- frontend/institution/removeInstController.js
- frontend/institution/removeInstDialog.html
- frontend/test/specs/institution/removeInstControllerSpec.js
Fixes #1341
The dialog's content was bigger them itself.
**Solution:**
Add a media query to decrease the content's size.
> Fix remove inst dialog

- frontend/event/event.css
- frontend/event/event_details.html
**Feature/Bug description:** The height of video youtube in event page is disproportionate
**Solution:** Define height to 500px;
Fix Issue: #1351
> Fix height of video youtube in event page

- frontend/app.js
- frontend/event/create_event.html
- frontend/event/event.css
- frontend/event/eventController.js
- frontend/event/eventDetailsDirective.js
- frontend/event/eventDialogController.js
- frontend/event/event_dialog.html
- frontend/index.html
- frontend/main/main.html
- frontend/main/mainController.js
- frontend/test/specs/event/eventControllerSpec.js
- frontend/test/specs/event/eventDetailsControllerSpec.js
- frontend/test/specs/event/eventDialogCtrlSpec.js
- frontend/utils/screenSizesConstants.js
**Feature/Bug description:** New view to the creation of events on mobile screen.
**Solution:** 
> Redesigning the create of event on mobile screen

- frontend/notification/pushNotificationService.js
**Feature/Bug description:** fix #1370
> Fix blank page on safari

- backend/admin.py
**Feature/Bug description:** Create a handler to add new features.
**Solution:** Create handler ResetFeatures on admim.py
> Create ResetFeatureHandler in admin.py

- webchat/components/contacts/contacts.css
- webchat/components/contacts/list/contacts-list.component.js
- webchat/components/contacts/list/contacts-list.html
- webchat/components/contacts/sidenav/contacts-sidenav.component.js
- webchat/components/contacts/sidenav/contacts-sidenav.html
- webchat/components/contacts/toolbar/contacts-toolbar.component.js
- webchat/components/contacts/toolbar/contacts-toolbar.html
- webchat/components/expansive-search-bar/expansive-search-bar.component.js
- webchat/components/expansive-search-bar/expansive-search-bar.css
- webchat/components/expansive-search-bar/expansive-search-bar.html
- webchat/components/header/ecis-header.component.js
- webchat/components/header/ecis-header.html
- webchat/components/user-description/user-description.component.js
- webchat/components/user-description/user-description.html
- webchat/home/home.html
- webchat/home/homeController.js
- webchat/index.html
- webchat/services/NavbarManagementService.js
- webchat/services/WebchatService.js
- webchat/styles/custom.css
- webchat/utils/utils.js
- webchat/webchat/webchat.html
- webchat/webchat/webchatController.js
**Feature/Bug description:** Add sidenav component that manages contacts display.
**Solution:** Create one major contacts sidenav components that contains two main smaller ones:
- Toolbar: Simple toolbar with search box component.
- List: Displays a list of users.
**TODO/FIXME:**:
> Webchat contacts list

- backend/admin.py
- backend/handlers/feature_toggle_handler.py
- backend/models/feature.py
- backend/test/feature_toggle_handler_tests/feature_toggle_handler_test.py
- backend/test/model_test/feature_test.py
- ecis
- feature-toggles/app.js
- feature-toggles/auth/authService.js
- feature-toggles/auth/loginController.js
- feature-toggles/index.html
- feature-toggles/manage/manage-toggles.css
- feature-toggles/manage/manage-toggles.html
- feature-toggles/manage/manageToggles.js
- feature-toggles/manage/manageTogglesController.js
- feature-toggles/manage/manageTogglesService.js
- feature-toggles/manage/permission-select.html
- feature-toggles/manage/permissionSelect.component.js
- feature-toggles/user/userFactory.js
- feature-toggles/utils/messageService.js
- feature-toggles/utils/statesConstants.js
**Feature/Bug description:** Finish the layout and allow the service to load and change the features.
**Solution:** I added the functionality of loading and changing system features to the frontend.
> Create feature manager service layout

- feature-toggles/index.html
- feature-toggles/manage/manage-toggles.css
- feature-toggles/manage/manage-toggles.html
- feature-toggles/manage/permission-select.css
- feature-toggles/manage/permission-select.html
- feature-toggles/manage/permission_select.css
**Feature/Bug description:** Create responsive layout for the feature management service.
**Solution:** Using CSS with media query and grid, I created the responsive layout.
> Create responsive layout to feature toggles service

- ecis
- generate_config.sh
**Feature/Bug description:** The script to generate the configuration files was very complex and broken when a new service was added to the system.
**Solution:** Refactor the script so that it builds the complete configuration file, rather than just replacing the lines.
> Refact ecis script

- backend/admin.py
**Feature/Bug description:** Refactor the handler that creates the features so it does not delete the features already added to the system.
**Solution:** I removed the call from the method that deletes the features of the database and renames the handler that creates the features.
> Refact handler to reset features

- frontend/app.js
- frontend/event/eventDialogController.js
- frontend/test/specs/event/eventDialogCtrlSpec.js
**Feature/Bug description:** Error when create event. fixes #1397
**Solution:** Changed verification of next step when create event.
> Fix create event on desktop

- frontend/manifest.json
**Feature/Bug description:** Add portrait orientation in manifest.json
fixes #1344 
> Add portrait orientation in manifest.json

- frontend/post/post_details.css
- frontend/post/post_details.html
**Feature/Bug description:**  Fix #1396: "Curtir" and "comentar" are out of place in small width mobile screen
**Solution:** Use css grid and remove delete text on mobile. (Following the design document specification)
Admin (can delete):
Regular user:
> Fix "Curtir" and "comentar" button on mobile

- frontend/post/pdf_view.css
- frontend/post/pdf_view.html
- frontend/styles/custom.css
**Feature/Bug description:** PDF viewing while creating the post is broken.
fixes #1364 
**Solution:** Change the layout to use css grid instead of angularjs material.
> Fix pdf item view

- frontend/institution/base_institution.css
**Feature/Bug description:** The menu was broken.
**Solution:** Changed height of the elements.
> Fix menu of institution page on mobile

- frontend/sw.js
- frontend/utils/utils.js
**Feature/Bug description:** The bottom toolbar 
**Solution:** The properties should reset only in mobile displays.
> Fix hide toolbars

- frontend/index.html
- frontend/institution/institutionCardDirective.js
- frontend/institution/institutionController.js
- frontend/institution/institutionService.js
- frontend/requests/request_invitation_dialog.css
- frontend/requests/request_invitation_dialog.html
- frontend/requests/request_invitation_dialog_mobile.html
- frontend/styles/custom.css
**Feature/Bug description:** Request invitation dialog doesn't match with design.
**Solution:**
- Design:
- Before:
- After:
> Fix request invitation dialog

- frontend/post/post_page.html
- frontend/styles/custom.css
> Fix post page

- frontend/home/post_dialog.html
- frontend/post/create_post.css
- frontend/styles/custom.css
**Feature/Bug description:** The layout of the edit post dialog is broken
**Solution:** I fixed the layout CSS
> Fix edit post dialog

- frontend/main/main.html
Fixes #1440 
Bottom bar event icon was different from sidebar event icon.
**Solution:** 
Make them equal.
> changed bottom bar event icon
